/* Generated by Yosys 0.35+7 (git sha1 5691cd095, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

(* hdlname = "\\prim_xilinx_buf" *)
(* dynports =  1  *)
(* DONT_TOUCH = "yes" *)
(* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/prim_xilinx_buf.v:1.26-9.10" *)
module \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000010 (in_i, out_o);
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/prim_xilinx_buf.v:6.22-6.26" *)
  input [1:0] in_i;
  wire [1:0] in_i;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/prim_xilinx_buf.v:7.28-7.33" *)
  output [1:0] out_o;
  wire [1:0] out_o;
  assign out_o = in_i;
endmodule

(* hdlname = "\\prim_xilinx_buf" *)
(* dynports =  1  *)
(* DONT_TOUCH = "yes" *)
(* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/prim_xilinx_buf.v:1.26-9.10" *)
module \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000100 (in_i, out_o);
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/prim_xilinx_buf.v:6.22-6.26" *)
  input [3:0] in_i;
  wire [3:0] in_i;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/prim_xilinx_buf.v:7.28-7.33" *)
  output [3:0] out_o;
  wire [3:0] out_o;
  assign out_o = in_i;
endmodule

(* hdlname = "\\prim_xilinx_buf" *)
(* dynports =  1  *)
(* DONT_TOUCH = "yes" *)
(* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/prim_xilinx_buf.v:1.26-9.10" *)
module \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000110 (in_i, out_o);
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/prim_xilinx_buf.v:6.22-6.26" *)
  input [5:0] in_i;
  wire [5:0] in_i;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/prim_xilinx_buf.v:7.28-7.33" *)
  output [5:0] out_o;
  wire [5:0] out_o;
  assign out_o = in_i;
endmodule

(* hdlname = "\\prim_xilinx_buf" *)
(* dynports =  1  *)
(* DONT_TOUCH = "yes" *)
(* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/prim_xilinx_buf.v:1.26-9.10" *)
module \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000001000 (in_i, out_o);
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/prim_xilinx_buf.v:6.22-6.26" *)
  input [7:0] in_i;
  wire [7:0] in_i;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/prim_xilinx_buf.v:7.28-7.33" *)
  output [7:0] out_o;
  wire [7:0] out_o;
  assign out_o = in_i;
endmodule

(* hdlname = "\\prim_xilinx_buf" *)
(* dynports =  1  *)
(* DONT_TOUCH = "yes" *)
(* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/prim_xilinx_buf.v:1.26-9.10" *)
module \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000010000 (in_i, out_o);
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/prim_xilinx_buf.v:6.22-6.26" *)
  input [15:0] in_i;
  wire [15:0] in_i;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/prim_xilinx_buf.v:7.28-7.33" *)
  output [15:0] out_o;
  wire [15:0] out_o;
  assign out_o = in_i;
endmodule

(* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:1.1-160.10" *)
module aes_masked_inverse_gf2p4_noreuse(b, q, r, t, b_inv);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:0.0-0.0" *)
  (* unused_bits = "1" *)
  wire [1:0] \aes_sbox_canright_pkg_aes_square_gf2p2$func$/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:51$14300.$result ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:0.0-0.0" *)
  (* unused_bits = "1" *)
  wire [1:0] \aes_sbox_canright_pkg_aes_square_gf2p2$func$/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:52$14302.$result ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:8.19-8.20" *)
  input [3:0] b;
  wire [3:0] b;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:135.13-135.19" *)
  wire [1:0] \b0_inv[0] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:135.13-135.19" *)
  wire [1:0] \b0_inv[1] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:135.13-135.19" *)
  wire [1:0] \b0_inv[2] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:135.13-135.19" *)
  wire [1:0] \b0_inv[3] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:136.13-136.23" *)
  wire [1:0] \b0_inv_buf[0] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:136.13-136.23" *)
  wire [1:0] \b0_inv_buf[1] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:136.13-136.23" *)
  wire [1:0] \b0_inv_buf[2] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:136.13-136.23" *)
  wire [1:0] \b0_inv_buf[3] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:133.13-133.19" *)
  wire [1:0] \b1_inv[0] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:133.13-133.19" *)
  wire [1:0] \b1_inv[1] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:133.13-133.19" *)
  wire [1:0] \b1_inv[2] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:133.13-133.19" *)
  wire [1:0] \b1_inv[3] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:134.13-134.23" *)
  wire [1:0] \b1_inv_buf[0] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:134.13-134.23" *)
  wire [1:0] \b1_inv_buf[1] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:134.13-134.23" *)
  wire [1:0] \b1_inv_buf[2] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:134.13-134.23" *)
  wire [1:0] \b1_inv_buf[3] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:12.20-12.25" *)
  output [3:0] b_inv;
  wire [3:0] b_inv;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:87.13-87.14" *)
  wire [1:0] \c[0] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:87.13-87.14" *)
  wire [1:0] \c[1] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:87.13-87.14" *)
  wire [1:0] \c[2] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:87.13-87.14" *)
  wire [1:0] \c[3] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:87.13-87.14" *)
  wire [1:0] \c[4] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:87.13-87.14" *)
  wire [1:0] \c[5] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:88.13-88.18" *)
  wire [1:0] \c_buf[0] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:88.13-88.18" *)
  wire [1:0] \c_buf[1] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:88.13-88.18" *)
  wire [1:0] \c_buf[2] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:88.13-88.18" *)
  wire [1:0] \c_buf[3] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:88.13-88.18" *)
  wire [1:0] \c_buf[4] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:88.13-88.18" *)
  wire [1:0] \c_buf[5] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:31.13-31.22" *)
  wire [1:0] mul_b0_q1;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:81.13-81.26" *)
  wire [1:0] mul_b0_q1_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:107.13-107.24" *)
  wire [1:0] mul_b0_r_sq;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:119.13-119.28" *)
  wire [1:0] mul_b0_r_sq_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:29.13-29.22" *)
  wire [1:0] mul_b1_b0;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:79.13-79.26" *)
  wire [1:0] mul_b1_b0_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:30.13-30.22" *)
  wire [1:0] mul_b1_q0;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:80.13-80.26" *)
  wire [1:0] mul_b1_q0_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:110.13-110.24" *)
  wire [1:0] mul_b1_r_sq;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:126.13-126.28" *)
  wire [1:0] mul_b1_r_sq_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:108.13-108.25" *)
  wire [1:0] mul_q0_c_inv;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:120.13-120.29" *)
  wire [1:0] mul_q0_c_inv_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:109.13-109.24" *)
  wire [1:0] mul_q0_r_sq;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:121.13-121.28" *)
  wire [1:0] mul_q0_r_sq_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:111.13-111.25" *)
  wire [1:0] mul_q1_c_inv;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:127.13-127.29" *)
  wire [1:0] mul_q1_c_inv_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:32.13-32.22" *)
  wire [1:0] mul_q1_q0;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:82.13-82.26" *)
  wire [1:0] mul_q1_q0_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:112.13-112.24" *)
  wire [1:0] mul_q1_r_sq;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:128.13-128.28" *)
  wire [1:0] mul_q1_r_sq_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:9.19-9.20" *)
  input [3:0] q;
  wire [3:0] q;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:10.19-10.20" *)
  input [1:0] r;
  wire [1:0] r;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:27.13-27.27" *)
  wire [1:0] scale_omega2_b;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:73.13-73.31" *)
  wire [1:0] scale_omega2_b_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:28.13-28.27" *)
  wire [1:0] scale_omega2_q;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:74.13-74.31" *)
  wire [1:0] scale_omega2_q_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:11.19-11.20" *)
  input [3:0] t;
  wire [3:0] t;
  assign \aes_sbox_canright_pkg_aes_square_gf2p2$func$/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:51$14300.$result [0] = b[1] ^ b[3];
  assign _000_ = b[0] ^ b[2];
  assign scale_omega2_b[0] = _000_ ^ \aes_sbox_canright_pkg_aes_square_gf2p2$func$/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:51$14300.$result [0];
  assign \aes_sbox_canright_pkg_aes_square_gf2p2$func$/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:52$14302.$result [0] = q[3] ^ q[1];
  assign _001_ = q[2] ^ q[0];
  assign scale_omega2_q[0] = _001_ ^ \aes_sbox_canright_pkg_aes_square_gf2p2$func$/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:52$14302.$result [0];
  assign _002_ = b[1] & b[3];
  assign _003_ = b[3] ^ b[2];
  assign _004_ = b[1] ^ b[0];
  assign _005_ = _004_ & _003_;
  assign mul_b1_b0[1] = _005_ ^ _002_;
  assign _006_ = b[0] & b[2];
  assign mul_b1_b0[0] = _006_ ^ _005_;
  assign _007_ = q[1] & b[3];
  assign _008_ = q[1] ^ q[0];
  assign _009_ = _008_ & _003_;
  assign mul_b1_q0[1] = _009_ ^ _007_;
  assign _010_ = q[0] & b[2];
  assign mul_b1_q0[0] = _010_ ^ _009_;
  assign _011_ = q[3] & b[1];
  assign _012_ = ~(q[3] ^ q[2]);
  assign _013_ = _004_ & ~(_012_);
  assign mul_b0_q1[1] = _013_ ^ _011_;
  assign _014_ = q[2] & b[0];
  assign mul_b0_q1[0] = _014_ ^ _013_;
  assign _015_ = q[3] & q[1];
  assign _016_ = _008_ & ~(_012_);
  assign mul_q1_q0[1] = _016_ ^ _015_;
  assign _017_ = q[2] & q[0];
  assign mul_q1_q0[0] = _017_ ^ _016_;
  assign _018_ = r[0] & b[1];
  assign _019_ = ~(r[0] ^ r[1]);
  assign _020_ = _004_ & ~(_019_);
  assign mul_b0_r_sq[1] = _020_ ^ _018_;
  assign _021_ = r[1] & b[0];
  assign mul_b0_r_sq[0] = _021_ ^ _020_;
  assign _022_ = \c_buf[5] [0] & q[1];
  assign _023_ = ~(\c_buf[5] [0] ^ \c_buf[5] [1]);
  assign _024_ = _008_ & ~(_023_);
  assign mul_q0_c_inv[1] = _024_ ^ _022_;
  assign _025_ = \c_buf[5] [1] & q[0];
  assign mul_q0_c_inv[0] = _025_ ^ _024_;
  assign _026_ = r[0] & q[1];
  assign _027_ = _008_ & ~(_019_);
  assign mul_q0_r_sq[1] = _027_ ^ _026_;
  assign _028_ = r[1] & q[0];
  assign mul_q0_r_sq[0] = _028_ ^ _027_;
  assign _029_ = r[0] & b[3];
  assign _030_ = _003_ & ~(_019_);
  assign mul_b1_r_sq[1] = _030_ ^ _029_;
  assign _031_ = r[1] & b[2];
  assign mul_b1_r_sq[0] = _031_ ^ _030_;
  assign _032_ = \c_buf[5] [0] & q[3];
  assign _033_ = q[3] ^ q[2];
  assign _034_ = _033_ & ~(_023_);
  assign mul_q1_c_inv[1] = _034_ ^ _032_;
  assign _035_ = \c_buf[5] [1] & q[2];
  assign mul_q1_c_inv[0] = _035_ ^ _034_;
  assign _036_ = r[0] & q[3];
  assign _037_ = _033_ & ~(_019_);
  assign mul_q1_r_sq[1] = _037_ ^ _036_;
  assign _038_ = r[1] & q[2];
  assign mul_q1_r_sq[0] = _038_ ^ _037_;
  assign \c[0] [0] = scale_omega2_b_buf[0] ^ r[0];
  assign \c[0] [1] = scale_omega2_b_buf[1] ^ r[1];
  assign \c[1] [0] = scale_omega2_q_buf[0] ^ \c_buf[0] [0];
  assign \c[1] [1] = scale_omega2_q_buf[1] ^ \c_buf[0] [1];
  assign \c[2] [0] = mul_b1_b0_buf[0] ^ \c_buf[1] [0];
  assign \c[2] [1] = mul_b1_b0_buf[1] ^ \c_buf[1] [1];
  assign \c[3] [0] = mul_b1_q0_buf[0] ^ \c_buf[2] [0];
  assign \c[3] [1] = mul_b1_q0_buf[1] ^ \c_buf[2] [1];
  assign \c[4] [0] = mul_b0_q1_buf[0] ^ \c_buf[3] [0];
  assign \c[4] [1] = mul_b0_q1_buf[1] ^ \c_buf[3] [1];
  assign \c[5] [0] = mul_q1_q0_buf[0] ^ \c_buf[4] [0];
  assign \c[5] [1] = mul_q1_q0_buf[1] ^ \c_buf[4] [1];
  assign _039_ = ~(\c_buf[5] [1] & b[0]);
  assign _040_ = _023_ | ~(_004_);
  assign _041_ = _040_ ^ _039_;
  assign \b1_inv[0] [0] = _041_ ^ t[2];
  assign _042_ = \c_buf[5] [0] & b[1];
  assign _043_ = ~(_042_ ^ _040_);
  assign \b1_inv[0] [1] = _043_ ^ t[3];
  assign \b1_inv[1] [0] = mul_b0_r_sq_buf[0] ^ \b1_inv_buf[0] [0];
  assign \b1_inv[1] [1] = mul_b0_r_sq_buf[1] ^ \b1_inv_buf[0] [1];
  assign \b1_inv[2] [0] = mul_q0_c_inv_buf[0] ^ \b1_inv_buf[1] [0];
  assign \b1_inv[2] [1] = mul_q0_c_inv_buf[1] ^ \b1_inv_buf[1] [1];
  assign \b1_inv[3] [0] = mul_q0_r_sq_buf[0] ^ \b1_inv_buf[2] [0];
  assign \b1_inv[3] [1] = mul_q0_r_sq_buf[1] ^ \b1_inv_buf[2] [1];
  assign _044_ = ~(\c_buf[5] [1] & b[2]);
  assign _045_ = _023_ | ~(_003_);
  assign _046_ = _045_ ^ _044_;
  assign \b0_inv[0] [0] = _046_ ^ t[0];
  assign _047_ = \c_buf[5] [0] & b[3];
  assign _048_ = ~(_047_ ^ _045_);
  assign \b0_inv[0] [1] = _048_ ^ t[1];
  assign \b0_inv[1] [0] = mul_b1_r_sq_buf[0] ^ \b0_inv_buf[0] [0];
  assign \b0_inv[1] [1] = mul_b1_r_sq_buf[1] ^ \b0_inv_buf[0] [1];
  assign \b0_inv[2] [0] = mul_q1_c_inv_buf[0] ^ \b0_inv_buf[1] [0];
  assign \b0_inv[2] [1] = mul_q1_c_inv_buf[1] ^ \b0_inv_buf[1] [1];
  assign \b0_inv[3] [0] = mul_q1_r_sq_buf[0] ^ \b0_inv_buf[2] [0];
  assign \b0_inv[3] [1] = mul_q1_r_sq_buf[1] ^ \b0_inv_buf[2] [1];
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:153.33-156.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000010  \gen_a01_inv_buf[0].u_prim_xilinx_buf_b0_inv_i  (
    .in_i(\b0_inv[0] ),
    .out_o(\b0_inv_buf[0] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:149.33-152.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000010  \gen_a01_inv_buf[0].u_prim_xilinx_buf_b1_inv_i  (
    .in_i(\b1_inv[0] ),
    .out_o(\b1_inv_buf[0] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:153.33-156.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000010  \gen_a01_inv_buf[1].u_prim_xilinx_buf_b0_inv_i  (
    .in_i(\b0_inv[1] ),
    .out_o(\b0_inv_buf[1] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:149.33-152.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000010  \gen_a01_inv_buf[1].u_prim_xilinx_buf_b1_inv_i  (
    .in_i(\b1_inv[1] ),
    .out_o(\b1_inv_buf[1] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:153.33-156.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000010  \gen_a01_inv_buf[2].u_prim_xilinx_buf_b0_inv_i  (
    .in_i(\b0_inv[2] ),
    .out_o(\b0_inv_buf[2] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:149.33-152.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000010  \gen_a01_inv_buf[2].u_prim_xilinx_buf_b1_inv_i  (
    .in_i(\b1_inv[2] ),
    .out_o(\b1_inv_buf[2] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:153.33-156.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000010  \gen_a01_inv_buf[3].u_prim_xilinx_buf_b0_inv_i  (
    .in_i(\b0_inv[3] ),
    .out_o(\b0_inv_buf[3] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:149.33-152.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000010  \gen_a01_inv_buf[3].u_prim_xilinx_buf_b1_inv_i  (
    .in_i(\b1_inv[3] ),
    .out_o(\b1_inv_buf[3] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:99.33-102.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000010  \gen_c_buf[0].u_prim_xilinx_buf_c_i  (
    .in_i(\c[0] ),
    .out_o(\c_buf[0] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:99.33-102.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000010  \gen_c_buf[1].u_prim_xilinx_buf_c_i  (
    .in_i(\c[1] ),
    .out_o(\c_buf[1] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:99.33-102.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000010  \gen_c_buf[2].u_prim_xilinx_buf_c_i  (
    .in_i(\c[2] ),
    .out_o(\c_buf[2] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:99.33-102.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000010  \gen_c_buf[3].u_prim_xilinx_buf_c_i  (
    .in_i(\c[3] ),
    .out_o(\c_buf[3] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:99.33-102.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000010  \gen_c_buf[4].u_prim_xilinx_buf_c_i  (
    .in_i(\c[4] ),
    .out_o(\c_buf[4] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:99.33-102.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000010  \gen_c_buf[5].u_prim_xilinx_buf_c_i  (
    .in_i(\c[5] ),
    .out_o(\c_buf[5] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:122.31-125.3" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000110  u_prim_xilinx_buf_mul_bq0 (
    .in_i({ mul_b0_r_sq, mul_q0_c_inv, mul_q0_r_sq }),
    .out_o({ mul_b0_r_sq_buf, mul_q0_c_inv_buf, mul_q0_r_sq_buf })
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:83.31-86.3" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000001000  u_prim_xilinx_buf_mul_bq01 (
    .in_i({ mul_b1_b0, mul_b1_q0, mul_b0_q1, mul_q1_q0 }),
    .out_o({ mul_b1_b0_buf, mul_b1_q0_buf, mul_b0_q1_buf, mul_q1_q0_buf })
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:129.31-132.3" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000110  u_prim_xilinx_buf_mul_bq1 (
    .in_i({ mul_b1_r_sq, mul_q1_c_inv, mul_q1_r_sq }),
    .out_o({ mul_b1_r_sq_buf, mul_q1_c_inv_buf, mul_q1_r_sq_buf })
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:75.31-78.3" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000100  u_prim_xilinx_buf_scale_omega2_bq (
    .in_i({ \aes_sbox_canright_pkg_aes_square_gf2p2$func$/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:51$14300.$result [0], scale_omega2_b[0], \aes_sbox_canright_pkg_aes_square_gf2p2$func$/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:52$14302.$result [0], scale_omega2_q[0] }),
    .out_o({ scale_omega2_b_buf, scale_omega2_q_buf })
  );
  assign b_inv = { \b1_inv_buf[3] , \b0_inv_buf[3]  };
  assign scale_omega2_b[1] = \aes_sbox_canright_pkg_aes_square_gf2p2$func$/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:51$14300.$result [0];
  assign scale_omega2_q[1] = \aes_sbox_canright_pkg_aes_square_gf2p2$func$/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:52$14302.$result [0];
endmodule

(* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:161.1-373.10" *)
module aes_masked_inverse_gf2p8_noreuse(a, m, n, prd, a_inv);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:168.19-168.20" *)
  input [7:0] a;
  wire [7:0] a;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:348.13-348.19" *)
  wire [3:0] \a0_inv[0] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:348.13-348.19" *)
  wire [3:0] \a0_inv[1] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:348.13-348.19" *)
  wire [3:0] \a0_inv[2] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:348.13-348.19" *)
  wire [3:0] \a0_inv[3] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:349.13-349.23" *)
  wire [3:0] \a0_inv_buf[0] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:349.13-349.23" *)
  wire [3:0] \a0_inv_buf[1] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:349.13-349.23" *)
  wire [3:0] \a0_inv_buf[2] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:349.13-349.23" *)
  wire [3:0] \a0_inv_buf[3] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:346.13-346.19" *)
  wire [3:0] \a1_inv[0] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:346.13-346.19" *)
  wire [3:0] \a1_inv[1] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:346.13-346.19" *)
  wire [3:0] \a1_inv[2] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:346.13-346.19" *)
  wire [3:0] \a1_inv[3] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:347.13-347.23" *)
  wire [3:0] \a1_inv_buf[0] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:347.13-347.23" *)
  wire [3:0] \a1_inv_buf[1] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:347.13-347.23" *)
  wire [3:0] \a1_inv_buf[2] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:347.13-347.23" *)
  wire [3:0] \a1_inv_buf[3] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:172.20-172.25" *)
  output [7:0] a_inv;
  wire [7:0] a_inv;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:284.13-284.14" *)
  wire [3:0] \b[0] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:284.13-284.14" *)
  wire [3:0] \b[1] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:284.13-284.14" *)
  wire [3:0] \b[2] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:284.13-284.14" *)
  wire [3:0] \b[3] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:284.13-284.14" *)
  wire [3:0] \b[4] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:284.13-284.14" *)
  wire [3:0] \b[5] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:285.13-285.18" *)
  wire [3:0] \b_buf[0] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:285.13-285.18" *)
  wire [3:0] \b_buf[1] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:285.13-285.18" *)
  wire [3:0] \b_buf[2] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:285.13-285.18" *)
  wire [3:0] \b_buf[3] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:285.13-285.18" *)
  wire [3:0] \b_buf[4] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:285.13-285.18" *)
  wire [3:0] \b_buf[5] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:178.13-178.18" *)
  wire [3:0] b_inv;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:309.13-309.22" *)
  wire [3:0] b_inv_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:169.19-169.20" *)
  input [7:0] m;
  wire [7:0] m;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:314.13-314.25" *)
  wire [3:0] mul_a0_b_inv;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:330.13-330.29" *)
  wire [3:0] mul_a0_b_inv_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:229.13-229.22" *)
  wire [3:0] mul_a0_m1;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:278.13-278.26" *)
  wire [3:0] mul_a0_m1_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:315.13-315.21" *)
  wire [3:0] mul_a0_t;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:331.13-331.25" *)
  wire [3:0] mul_a0_t_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:227.13-227.22" *)
  wire [3:0] mul_a1_a0;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:276.13-276.26" *)
  wire [3:0] mul_a1_a0_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:318.13-318.25" *)
  wire [3:0] mul_a1_b_inv;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:338.13-338.29" *)
  wire [3:0] mul_a1_b_inv_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:228.13-228.22" *)
  wire [3:0] mul_a1_m0;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:277.13-277.26" *)
  wire [3:0] mul_a1_m0_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:319.13-319.21" *)
  wire [3:0] mul_a1_t;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:339.13-339.25" *)
  wire [3:0] mul_a1_t_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:316.13-316.25" *)
  wire [3:0] mul_m0_b_inv;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:332.13-332.29" *)
  wire [3:0] mul_m0_b_inv_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:230.13-230.22" *)
  wire [3:0] mul_m0_m1;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:279.13-279.26" *)
  wire [3:0] mul_m0_m1_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:317.13-317.21" *)
  wire [3:0] mul_m0_t;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:333.13-333.25" *)
  wire [3:0] mul_m0_t_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:320.13-320.25" *)
  wire [3:0] mul_m1_b_inv;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:340.13-340.29" *)
  wire [3:0] mul_m1_b_inv_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:321.13-321.21" *)
  wire [3:0] mul_m1_t;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:341.13-341.25" *)
  wire [3:0] mul_m1_t_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:170.19-170.20" *)
  input [7:0] n;
  wire [7:0] n;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:171.19-171.22" *)
  input [9:0] prd;
  wire [9:0] prd;
  assign _000_ = a[2] & a[6];
  assign _001_ = ~(a[7] ^ a[6]);
  assign _002_ = ~(a[3] ^ a[2]);
  assign _003_ = _002_ | _001_;
  assign _004_ = _003_ ^ _000_;
  assign _005_ = ~(a[5] ^ a[7]);
  assign _006_ = a[1] ^ a[3];
  assign _007_ = _006_ & ~(_005_);
  assign _008_ = a[4] ^ a[6];
  assign _009_ = _008_ ^ _005_;
  assign _010_ = ~(a[0] ^ a[2]);
  assign _011_ = _010_ ^ _006_;
  assign _012_ = _011_ | _009_;
  assign _013_ = ~(_012_ ^ _007_);
  assign _014_ = _008_ & ~(_010_);
  assign _015_ = _014_ ^ _012_;
  assign _016_ = _015_ ^ _013_;
  assign mul_a1_a0[2] = _016_ ^ _004_;
  assign _017_ = a[3] & a[7];
  assign _018_ = _017_ ^ _003_;
  assign mul_a1_a0[3] = _018_ ^ _015_;
  assign _019_ = a[0] & a[4];
  assign _020_ = ~(a[5] ^ a[4]);
  assign _021_ = ~(a[1] ^ a[0]);
  assign _022_ = _021_ | _020_;
  assign _023_ = _022_ ^ _019_;
  assign mul_a1_a0[0] = _023_ ^ _016_;
  assign _024_ = a[1] & a[5];
  assign _025_ = _024_ ^ _022_;
  assign mul_a1_a0[1] = _025_ ^ _015_;
  assign _026_ = m[2] & a[6];
  assign _027_ = ~(m[3] ^ m[2]);
  assign _028_ = _027_ | _001_;
  assign _029_ = _028_ ^ _026_;
  assign _030_ = m[1] ^ m[3];
  assign _031_ = _030_ & ~(_005_);
  assign _032_ = ~(m[0] ^ m[2]);
  assign _033_ = _032_ ^ _030_;
  assign _034_ = _033_ | _009_;
  assign _035_ = ~(_034_ ^ _031_);
  assign _036_ = _008_ & ~(_032_);
  assign _037_ = _036_ ^ _034_;
  assign _038_ = _037_ ^ _035_;
  assign mul_a1_m0[2] = _038_ ^ _029_;
  assign _039_ = m[3] & a[7];
  assign _040_ = _039_ ^ _028_;
  assign mul_a1_m0[3] = _040_ ^ _037_;
  assign _041_ = m[0] & a[4];
  assign _042_ = ~(m[1] ^ m[0]);
  assign _043_ = _042_ | _020_;
  assign _044_ = _043_ ^ _041_;
  assign mul_a1_m0[0] = _044_ ^ _038_;
  assign _045_ = m[1] & a[5];
  assign _046_ = _045_ ^ _043_;
  assign mul_a1_m0[1] = _046_ ^ _037_;
  assign _047_ = m[6] & a[2];
  assign _048_ = ~(m[7] ^ m[6]);
  assign _049_ = _048_ | _002_;
  assign _050_ = _049_ ^ _047_;
  assign _051_ = m[5] ^ m[7];
  assign _052_ = ~(_051_ & _006_);
  assign _053_ = ~(m[4] ^ m[6]);
  assign _054_ = _053_ ^ _051_;
  assign _055_ = _054_ | _011_;
  assign _056_ = _055_ ^ _052_;
  assign _057_ = a[0] ^ a[2];
  assign _058_ = _057_ & ~(_053_);
  assign _059_ = _058_ ^ _055_;
  assign _060_ = _059_ ^ _056_;
  assign mul_a0_m1[2] = _060_ ^ _050_;
  assign _061_ = m[7] & a[3];
  assign _062_ = _061_ ^ _049_;
  assign mul_a0_m1[3] = _062_ ^ _059_;
  assign _063_ = m[4] & a[0];
  assign _064_ = ~(m[5] ^ m[4]);
  assign _065_ = _064_ | _021_;
  assign _066_ = _065_ ^ _063_;
  assign mul_a0_m1[0] = _066_ ^ _060_;
  assign _067_ = m[5] & a[1];
  assign _068_ = _067_ ^ _065_;
  assign mul_a0_m1[1] = _068_ ^ _059_;
  assign _069_ = m[6] & m[2];
  assign _070_ = _048_ | _027_;
  assign _071_ = _070_ ^ _069_;
  assign _072_ = ~(_051_ & _030_);
  assign _073_ = _054_ | _033_;
  assign _074_ = _073_ ^ _072_;
  assign _075_ = m[0] ^ m[2];
  assign _076_ = _075_ & ~(_053_);
  assign _077_ = _076_ ^ _073_;
  assign _078_ = _077_ ^ _074_;
  assign mul_m0_m1[2] = _078_ ^ _071_;
  assign _079_ = m[7] & m[3];
  assign _080_ = _079_ ^ _070_;
  assign mul_m0_m1[3] = _080_ ^ _077_;
  assign _081_ = m[4] & m[0];
  assign _082_ = _064_ | _042_;
  assign _083_ = _082_ ^ _081_;
  assign mul_m0_m1[0] = _083_ ^ _078_;
  assign _084_ = m[5] & m[1];
  assign _085_ = _084_ ^ _082_;
  assign mul_m0_m1[1] = _085_ ^ _077_;
  assign _086_ = b_inv_buf[2] & a[2];
  assign _087_ = ~(b_inv_buf[3] ^ b_inv_buf[2]);
  assign _088_ = _087_ | _002_;
  assign _089_ = _088_ ^ _086_;
  assign _090_ = ~(b_inv_buf[1] ^ b_inv_buf[3]);
  assign _091_ = _006_ & ~(_090_);
  assign _092_ = ~(b_inv_buf[0] ^ b_inv_buf[2]);
  assign _093_ = ~(_092_ ^ _090_);
  assign _094_ = _093_ | _011_;
  assign _095_ = ~(_094_ ^ _091_);
  assign _096_ = _057_ & ~(_092_);
  assign _097_ = _096_ ^ _094_;
  assign _098_ = _097_ ^ _095_;
  assign mul_a0_b_inv[2] = _098_ ^ _089_;
  assign _099_ = b_inv_buf[3] & a[3];
  assign _100_ = _099_ ^ _088_;
  assign mul_a0_b_inv[3] = _100_ ^ _097_;
  assign _101_ = b_inv_buf[0] & a[0];
  assign _102_ = ~(b_inv_buf[1] ^ b_inv_buf[0]);
  assign _103_ = _102_ | _021_;
  assign _104_ = _103_ ^ _101_;
  assign mul_a0_b_inv[0] = _104_ ^ _098_;
  assign _105_ = b_inv_buf[1] & a[1];
  assign _106_ = _105_ ^ _103_;
  assign mul_a0_b_inv[1] = _106_ ^ _097_;
  assign _107_ = prd[8] & a[2];
  assign _108_ = ~(prd[9] ^ prd[8]);
  assign _109_ = _108_ | _002_;
  assign _110_ = _109_ ^ _107_;
  assign _111_ = ~(prd[7] ^ prd[9]);
  assign _112_ = _006_ & ~(_111_);
  assign _113_ = ~(prd[6] ^ prd[8]);
  assign _114_ = ~(_113_ ^ _111_);
  assign _115_ = _114_ | _011_;
  assign _116_ = ~(_115_ ^ _112_);
  assign _117_ = _057_ & ~(_113_);
  assign _118_ = _117_ ^ _115_;
  assign _119_ = _118_ ^ _116_;
  assign mul_a0_t[2] = _119_ ^ _110_;
  assign _120_ = prd[9] & a[3];
  assign _121_ = _120_ ^ _109_;
  assign mul_a0_t[3] = _121_ ^ _118_;
  assign _122_ = prd[6] & a[0];
  assign _123_ = ~(prd[7] ^ prd[6]);
  assign _124_ = _123_ | _021_;
  assign _125_ = _124_ ^ _122_;
  assign mul_a0_t[0] = _125_ ^ _119_;
  assign _126_ = prd[7] & a[1];
  assign _127_ = _126_ ^ _124_;
  assign mul_a0_t[1] = _127_ ^ _118_;
  assign _128_ = b_inv_buf[2] & m[2];
  assign _129_ = _087_ | _027_;
  assign _130_ = _129_ ^ _128_;
  assign _131_ = _090_ | ~(_030_);
  assign _132_ = _093_ | _033_;
  assign _133_ = _132_ ^ _131_;
  assign _134_ = _075_ & ~(_092_);
  assign _135_ = _134_ ^ _132_;
  assign _136_ = _135_ ^ _133_;
  assign mul_m0_b_inv[2] = _136_ ^ _130_;
  assign _137_ = b_inv_buf[3] & m[3];
  assign _138_ = _137_ ^ _129_;
  assign mul_m0_b_inv[3] = _138_ ^ _135_;
  assign _139_ = b_inv_buf[0] & m[0];
  assign _140_ = _102_ | _042_;
  assign _141_ = _140_ ^ _139_;
  assign mul_m0_b_inv[0] = _141_ ^ _136_;
  assign _142_ = b_inv_buf[1] & m[1];
  assign _143_ = _142_ ^ _140_;
  assign mul_m0_b_inv[1] = _143_ ^ _135_;
  assign _144_ = prd[8] & m[2];
  assign _145_ = _108_ | _027_;
  assign _146_ = _145_ ^ _144_;
  assign _147_ = _111_ | ~(_030_);
  assign _148_ = _114_ | _033_;
  assign _149_ = _148_ ^ _147_;
  assign _150_ = _075_ & ~(_113_);
  assign _151_ = _150_ ^ _148_;
  assign _152_ = _151_ ^ _149_;
  assign mul_m0_t[2] = _152_ ^ _146_;
  assign _153_ = prd[9] & m[3];
  assign _154_ = _153_ ^ _145_;
  assign mul_m0_t[3] = _154_ ^ _151_;
  assign _155_ = prd[6] & m[0];
  assign _156_ = _123_ | _042_;
  assign _157_ = _156_ ^ _155_;
  assign mul_m0_t[0] = _157_ ^ _152_;
  assign _158_ = prd[7] & m[1];
  assign _159_ = _158_ ^ _156_;
  assign mul_m0_t[1] = _159_ ^ _151_;
  assign _160_ = b_inv_buf[2] & a[6];
  assign _161_ = _087_ | _001_;
  assign _162_ = _161_ ^ _160_;
  assign _163_ = _090_ | _005_;
  assign _164_ = _093_ | _009_;
  assign _165_ = _164_ ^ _163_;
  assign _166_ = _008_ & ~(_092_);
  assign _167_ = _166_ ^ _164_;
  assign _168_ = _167_ ^ _165_;
  assign mul_a1_b_inv[2] = _168_ ^ _162_;
  assign _169_ = b_inv_buf[3] & a[7];
  assign _170_ = _169_ ^ _161_;
  assign mul_a1_b_inv[3] = _170_ ^ _167_;
  assign _171_ = b_inv_buf[0] & a[4];
  assign _172_ = _102_ | _020_;
  assign _173_ = _172_ ^ _171_;
  assign mul_a1_b_inv[0] = _173_ ^ _168_;
  assign _174_ = b_inv_buf[1] & a[5];
  assign _175_ = _174_ ^ _172_;
  assign mul_a1_b_inv[1] = _175_ ^ _167_;
  assign _176_ = prd[8] & a[6];
  assign _177_ = _108_ | _001_;
  assign _178_ = _177_ ^ _176_;
  assign _179_ = _111_ | _005_;
  assign _180_ = _114_ | _009_;
  assign _181_ = _180_ ^ _179_;
  assign _182_ = _008_ & ~(_113_);
  assign _183_ = _182_ ^ _180_;
  assign _184_ = _183_ ^ _181_;
  assign mul_a1_t[2] = _184_ ^ _178_;
  assign _185_ = prd[9] & a[7];
  assign _186_ = _185_ ^ _177_;
  assign mul_a1_t[3] = _186_ ^ _183_;
  assign _187_ = prd[6] & a[4];
  assign _188_ = _123_ | _020_;
  assign _189_ = _188_ ^ _187_;
  assign mul_a1_t[0] = _189_ ^ _184_;
  assign _190_ = prd[7] & a[5];
  assign _191_ = _190_ ^ _188_;
  assign mul_a1_t[1] = _191_ ^ _183_;
  assign _192_ = b_inv_buf[2] & m[6];
  assign _193_ = _087_ | _048_;
  assign _194_ = _193_ ^ _192_;
  assign _195_ = _090_ | ~(_051_);
  assign _196_ = _093_ | _054_;
  assign _197_ = _196_ ^ _195_;
  assign _198_ = m[4] ^ m[6];
  assign _199_ = _198_ & ~(_092_);
  assign _200_ = _199_ ^ _196_;
  assign _201_ = _200_ ^ _197_;
  assign mul_m1_b_inv[2] = _201_ ^ _194_;
  assign _202_ = b_inv_buf[3] & m[7];
  assign _203_ = _202_ ^ _193_;
  assign mul_m1_b_inv[3] = _203_ ^ _200_;
  assign _204_ = b_inv_buf[0] & m[4];
  assign _205_ = _102_ | _064_;
  assign _206_ = _205_ ^ _204_;
  assign mul_m1_b_inv[0] = _206_ ^ _201_;
  assign _207_ = b_inv_buf[1] & m[5];
  assign _208_ = _207_ ^ _205_;
  assign mul_m1_b_inv[1] = _208_ ^ _200_;
  assign _209_ = prd[8] & m[6];
  assign _210_ = _108_ | _048_;
  assign _211_ = _210_ ^ _209_;
  assign _212_ = _111_ | ~(_051_);
  assign _213_ = _114_ | _054_;
  assign _214_ = _213_ ^ _212_;
  assign _215_ = _198_ & ~(_113_);
  assign _216_ = _215_ ^ _213_;
  assign _217_ = _216_ ^ _214_;
  assign mul_m1_t[2] = _217_ ^ _211_;
  assign _218_ = prd[9] & m[7];
  assign _219_ = _218_ ^ _210_;
  assign mul_m1_t[3] = _219_ ^ _216_;
  assign _220_ = prd[6] & m[4];
  assign _221_ = _123_ | _064_;
  assign _222_ = _221_ ^ _220_;
  assign mul_m1_t[0] = _222_ ^ _217_;
  assign _223_ = prd[7] & m[5];
  assign _224_ = _223_ ^ _221_;
  assign mul_m1_t[1] = _224_ ^ _216_;
  assign _225_ = a[0] ^ a[4];
  assign \b[0] [0] = _225_ ^ prd[2];
  assign _226_ = a[1] ^ a[5];
  assign _227_ = _226_ ^ _225_;
  assign \b[0] [1] = _227_ ^ prd[3];
  assign _228_ = ~(a[3] ^ a[7]);
  assign _229_ = ~(_228_ ^ _226_);
  assign \b[0] [2] = _229_ ^ prd[4];
  assign _230_ = ~(a[2] ^ a[6]);
  assign _231_ = ~(_230_ ^ _225_);
  assign \b[0] [3] = _231_ ^ prd[5];
  assign _232_ = m[4] ^ m[0];
  assign \b[1] [0] = _232_ ^ \b_buf[0] [0];
  assign _233_ = m[5] ^ m[1];
  assign _234_ = _233_ ^ _232_;
  assign \b[1] [1] = _234_ ^ \b_buf[0] [1];
  assign _235_ = ~(m[7] ^ m[3]);
  assign _236_ = ~(_235_ ^ _233_);
  assign \b[1] [2] = _236_ ^ \b_buf[0] [2];
  assign _237_ = ~(m[6] ^ m[2]);
  assign _238_ = ~(_237_ ^ _232_);
  assign \b[1] [3] = _238_ ^ \b_buf[0] [3];
  assign \b[2] [0] = mul_a1_a0_buf[0] ^ \b_buf[1] [0];
  assign \b[2] [1] = mul_a1_a0_buf[1] ^ \b_buf[1] [1];
  assign \b[2] [2] = mul_a1_a0_buf[2] ^ \b_buf[1] [2];
  assign \b[2] [3] = mul_a1_a0_buf[3] ^ \b_buf[1] [3];
  assign \b[3] [0] = mul_a1_m0_buf[0] ^ \b_buf[2] [0];
  assign \b[3] [1] = mul_a1_m0_buf[1] ^ \b_buf[2] [1];
  assign \b[3] [2] = mul_a1_m0_buf[2] ^ \b_buf[2] [2];
  assign \b[3] [3] = mul_a1_m0_buf[3] ^ \b_buf[2] [3];
  assign \b[4] [0] = mul_a0_m1_buf[0] ^ \b_buf[3] [0];
  assign \b[4] [1] = mul_a0_m1_buf[1] ^ \b_buf[3] [1];
  assign \b[4] [2] = mul_a0_m1_buf[2] ^ \b_buf[3] [2];
  assign \b[4] [3] = mul_a0_m1_buf[3] ^ \b_buf[3] [3];
  assign \b[5] [0] = mul_m0_m1_buf[0] ^ \b_buf[4] [0];
  assign \b[5] [1] = mul_m0_m1_buf[1] ^ \b_buf[4] [1];
  assign \b[5] [2] = mul_m0_m1_buf[2] ^ \b_buf[4] [2];
  assign \b[5] [3] = mul_m0_m1_buf[3] ^ \b_buf[4] [3];
  assign \a1_inv[0] [0] = mul_a0_b_inv_buf[0] ^ n[4];
  assign \a1_inv[0] [1] = mul_a0_b_inv_buf[1] ^ n[5];
  assign \a1_inv[0] [2] = mul_a0_b_inv_buf[2] ^ n[6];
  assign \a1_inv[0] [3] = mul_a0_b_inv_buf[3] ^ n[7];
  assign \a1_inv[1] [0] = mul_a0_t_buf[0] ^ \a1_inv_buf[0] [0];
  assign \a1_inv[1] [1] = mul_a0_t_buf[1] ^ \a1_inv_buf[0] [1];
  assign \a1_inv[1] [2] = mul_a0_t_buf[2] ^ \a1_inv_buf[0] [2];
  assign \a1_inv[1] [3] = mul_a0_t_buf[3] ^ \a1_inv_buf[0] [3];
  assign \a1_inv[2] [0] = mul_m0_b_inv_buf[0] ^ \a1_inv_buf[1] [0];
  assign \a1_inv[2] [1] = mul_m0_b_inv_buf[1] ^ \a1_inv_buf[1] [1];
  assign \a1_inv[2] [2] = mul_m0_b_inv_buf[2] ^ \a1_inv_buf[1] [2];
  assign \a1_inv[2] [3] = mul_m0_b_inv_buf[3] ^ \a1_inv_buf[1] [3];
  assign \a1_inv[3] [0] = mul_m0_t_buf[0] ^ \a1_inv_buf[2] [0];
  assign \a1_inv[3] [1] = mul_m0_t_buf[1] ^ \a1_inv_buf[2] [1];
  assign \a1_inv[3] [2] = mul_m0_t_buf[2] ^ \a1_inv_buf[2] [2];
  assign \a1_inv[3] [3] = mul_m0_t_buf[3] ^ \a1_inv_buf[2] [3];
  assign \a0_inv[0] [0] = mul_a1_b_inv_buf[0] ^ n[0];
  assign \a0_inv[0] [1] = mul_a1_b_inv_buf[1] ^ n[1];
  assign \a0_inv[0] [2] = mul_a1_b_inv_buf[2] ^ n[2];
  assign \a0_inv[0] [3] = mul_a1_b_inv_buf[3] ^ n[3];
  assign \a0_inv[1] [0] = mul_a1_t_buf[0] ^ \a0_inv_buf[0] [0];
  assign \a0_inv[1] [1] = mul_a1_t_buf[1] ^ \a0_inv_buf[0] [1];
  assign \a0_inv[1] [2] = mul_a1_t_buf[2] ^ \a0_inv_buf[0] [2];
  assign \a0_inv[1] [3] = mul_a1_t_buf[3] ^ \a0_inv_buf[0] [3];
  assign \a0_inv[2] [0] = mul_m1_b_inv_buf[0] ^ \a0_inv_buf[1] [0];
  assign \a0_inv[2] [1] = mul_m1_b_inv_buf[1] ^ \a0_inv_buf[1] [1];
  assign \a0_inv[2] [2] = mul_m1_b_inv_buf[2] ^ \a0_inv_buf[1] [2];
  assign \a0_inv[2] [3] = mul_m1_b_inv_buf[3] ^ \a0_inv_buf[1] [3];
  assign \a0_inv[3] [0] = mul_m1_t_buf[0] ^ \a0_inv_buf[2] [0];
  assign \a0_inv[3] [1] = mul_m1_t_buf[1] ^ \a0_inv_buf[2] [1];
  assign \a0_inv[3] [2] = mul_m1_t_buf[2] ^ \a0_inv_buf[2] [2];
  assign \a0_inv[3] [3] = mul_m1_t_buf[3] ^ \a0_inv_buf[2] [3];
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:366.33-369.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000100  \gen_a01_inv_buf[0].u_prim_xilinx_buf_a0_inv_i  (
    .in_i(\a0_inv[0] ),
    .out_o(\a0_inv_buf[0] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:362.33-365.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000100  \gen_a01_inv_buf[0].u_prim_xilinx_buf_a1_inv_i  (
    .in_i(\a1_inv[0] ),
    .out_o(\a1_inv_buf[0] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:366.33-369.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000100  \gen_a01_inv_buf[1].u_prim_xilinx_buf_a0_inv_i  (
    .in_i(\a0_inv[1] ),
    .out_o(\a0_inv_buf[1] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:362.33-365.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000100  \gen_a01_inv_buf[1].u_prim_xilinx_buf_a1_inv_i  (
    .in_i(\a1_inv[1] ),
    .out_o(\a1_inv_buf[1] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:366.33-369.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000100  \gen_a01_inv_buf[2].u_prim_xilinx_buf_a0_inv_i  (
    .in_i(\a0_inv[2] ),
    .out_o(\a0_inv_buf[2] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:362.33-365.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000100  \gen_a01_inv_buf[2].u_prim_xilinx_buf_a1_inv_i  (
    .in_i(\a1_inv[2] ),
    .out_o(\a1_inv_buf[2] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:366.33-369.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000100  \gen_a01_inv_buf[3].u_prim_xilinx_buf_a0_inv_i  (
    .in_i(\a0_inv[3] ),
    .out_o(\a0_inv_buf[3] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:362.33-365.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000100  \gen_a01_inv_buf[3].u_prim_xilinx_buf_a1_inv_i  (
    .in_i(\a1_inv[3] ),
    .out_o(\a1_inv_buf[3] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:296.33-299.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000100  \gen_b_buf[0].u_prim_xilinx_buf_b_i  (
    .in_i(\b[0] ),
    .out_o(\b_buf[0] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:296.33-299.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000100  \gen_b_buf[1].u_prim_xilinx_buf_b_i  (
    .in_i(\b[1] ),
    .out_o(\b_buf[1] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:296.33-299.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000100  \gen_b_buf[2].u_prim_xilinx_buf_b_i  (
    .in_i(\b[2] ),
    .out_o(\b_buf[2] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:296.33-299.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000100  \gen_b_buf[3].u_prim_xilinx_buf_b_i  (
    .in_i(\b[3] ),
    .out_o(\b_buf[3] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:296.33-299.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000100  \gen_b_buf[4].u_prim_xilinx_buf_b_i  (
    .in_i(\b[4] ),
    .out_o(\b_buf[4] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:296.33-299.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000100  \gen_b_buf[5].u_prim_xilinx_buf_b_i  (
    .in_i(\b[5] ),
    .out_o(\b_buf[5] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:302.35-308.3" *)
  aes_masked_inverse_gf2p4_noreuse u_aes_masked_inverse_gf2p4 (
    .b(\b_buf[5] ),
    .b_inv(b_inv),
    .q(prd[5:2]),
    .r(prd[1:0]),
    .t(prd[9:6])
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:310.31-313.3" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000100  u_prim_xilinx_buf_b_inv (
    .in_i(b_inv),
    .out_o(b_inv_buf)
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:334.32-337.3" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000010000  u_prim_xilinx_buf_mul_am0 (
    .in_i({ mul_a0_b_inv, mul_a0_t, mul_m0_b_inv, mul_m0_t }),
    .out_o({ mul_a0_b_inv_buf, mul_a0_t_buf, mul_m0_b_inv_buf, mul_m0_t_buf })
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:280.32-283.3" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000010000  u_prim_xilinx_buf_mul_am01 (
    .in_i({ mul_a1_a0, mul_a1_m0, mul_a0_m1, mul_m0_m1 }),
    .out_o({ mul_a1_a0_buf, mul_a1_m0_buf, mul_a0_m1_buf, mul_m0_m1_buf })
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:342.32-345.3" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000010000  u_prim_xilinx_buf_mul_am1 (
    .in_i({ mul_a1_b_inv, mul_a1_t, mul_m1_b_inv, mul_m1_t }),
    .out_o({ mul_a1_b_inv_buf, mul_a1_t_buf, mul_m1_b_inv_buf, mul_m1_t_buf })
  );
  assign a_inv = { \a1_inv_buf[3] , \a0_inv_buf[3]  };
endmodule

(* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox.v:1.1-131.10" *)
(* top =  1  *)
(* hdlname = "\\aes_sbox" *)
module aes_sbox(clk_i, rst_ni, en_i, prd_we_i, out_req_o, out_ack_i, op_i, data_i, mask_i, prd_i, data_o, mask_o, prd_o);
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox.v:17.13-17.18" *)
  input clk_i;
  wire clk_i;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox.v:25.19-25.25" *)
  input [7:0] data_i;
  wire [7:0] data_i;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox.v:29.20-29.26" *)
  output [7:0] data_o;
  wire [7:0] data_o;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox.v:19.13-19.17" *)
  input en_i;
  wire en_i;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox.v:26.19-26.25" *)
  input [7:0] mask_i;
  wire [7:0] mask_i;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox.v:30.20-30.26" *)
  output [7:0] mask_o;
  wire [7:0] mask_o;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox.v:24.19-24.23" *)
  input [1:0] op_i;
  wire [1:0] op_i;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox.v:22.13-22.22" *)
  input out_ack_i;
  wire out_ack_i;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox.v:21.14-21.23" *)
  output out_req_o;
  wire out_req_o;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox.v:28.20-28.25" *)
  input [27:0] prd_i;
  wire [27:0] prd_i;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox.v:31.21-31.26" *)
  output [19:0] prd_o;
  wire [19:0] prd_o;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox.v:20.13-20.21" *)
  input prd_we_i;
  wire prd_we_i;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox.v:18.13-18.19" *)
  input rst_ni;
  wire rst_ni;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox.v:95.38-102.6" *)
  aes_sbox_canright_masked_noreuse \gen_sbox_masked.genblk1.gen_sbox_canright_masked_noreuse.u_aes_sbox  (
    .data_i(data_i),
    .data_o(data_o),
    .mask_i(mask_i),
    .mask_o(mask_o),
    .op_i(op_i),
    .prd_i(prd_i[17:0])
  );
  assign out_req_o = en_i;
  assign prd_o = 20'h00000;
endmodule

(* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:374.1-433.10" *)
module aes_sbox_canright_masked_noreuse(op_i, data_i, mask_i, prd_i, data_o, mask_o);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:384.19-384.25" *)
  input [7:0] data_i;
  wire [7:0] data_i;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:387.20-387.26" *)
  output [7:0] data_o;
  wire [7:0] data_o;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:389.13-389.28" *)
  wire [7:0] in_data_basis_x;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:391.13-391.28" *)
  wire [7:0] in_mask_basis_x;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:385.19-385.25" *)
  input [7:0] mask_i;
  wire [7:0] mask_i;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:388.20-388.26" *)
  output [7:0] mask_o;
  wire [7:0] mask_o;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:383.19-383.23" *)
  input [1:0] op_i;
  wire [1:0] op_i;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:390.13-390.29" *)
  wire [7:0] out_data_basis_x;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:392.13-392.29" *)
  wire [7:0] out_mask_basis_x;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:386.20-386.25" *)
  input [17:0] prd_i;
  wire [17:0] prd_i;
  assign _131_ = ~data_i[0];
  assign _132_ = ~(data_i[3] ^ data_i[6]);
  assign _133_ = _132_ ^ data_i[2];
  assign _134_ = _133_ ^ data_i[1];
  assign _135_ = _134_ ^ _131_;
  assign _136_ = op_i[0] & ~(op_i[1]);
  assign _137_ = ~data_i[1];
  assign _138_ = ~(data_i[6] ^ data_i[5]);
  assign _139_ = _138_ ^ data_i[4];
  assign _140_ = _139_ ^ _137_;
  assign _141_ = _140_ ^ data_i[0];
  assign _142_ = op_i[1] & ~(op_i[0]);
  assign _143_ = _142_ ? _141_ : _135_;
  assign in_data_basis_x[0] = _136_ ? _135_ : _143_;
  assign _144_ = _138_ ^ _131_;
  assign _145_ = ~(data_i[4] ^ data_i[3]);
  assign _146_ = _145_ ^ data_i[0];
  assign _147_ = _142_ ? _146_ : _144_;
  assign in_data_basis_x[1] = _136_ ? _144_ : _147_;
  assign _148_ = ~(data_i[7] ^ data_i[5]);
  assign _149_ = _148_ ^ data_i[2];
  assign _150_ = _142_ ? _149_ : data_i[0];
  assign in_data_basis_x[2] = _136_ ? data_i[0] : _150_;
  assign _151_ = data_i[4] ^ data_i[7];
  assign _152_ = ~(_151_ ^ data_i[3]);
  assign _153_ = _152_ ^ data_i[1];
  assign _154_ = _153_ ^ _131_;
  assign _155_ = ~(data_i[7] ^ data_i[6]);
  assign _156_ = _155_ ^ data_i[4];
  assign _157_ = _142_ ? _156_ : _154_;
  assign in_data_basis_x[3] = _136_ ? _154_ : _157_;
  assign _000_ = _155_ ^ data_i[5];
  assign _001_ = _000_ ^ _131_;
  assign _002_ = data_i[3] ^ data_i[6];
  assign _003_ = _002_ ^ _137_;
  assign _004_ = _003_ ^ data_i[0];
  assign _005_ = _142_ ? _004_ : _001_;
  assign in_data_basis_x[4] = _136_ ? _001_ : _005_;
  assign _006_ = _138_ ^ data_i[1];
  assign _007_ = _006_ ^ _131_;
  assign _008_ = ~(data_i[4] ^ data_i[6]);
  assign _009_ = _142_ ? _008_ : _007_;
  assign in_data_basis_x[5] = _136_ ? _007_ : _009_;
  assign _010_ = _139_ ^ _131_;
  assign _011_ = _008_ ^ data_i[1];
  assign _012_ = _011_ ^ data_i[0];
  assign _013_ = _142_ ? _012_ : _010_;
  assign in_data_basis_x[6] = _136_ ? _010_ : _013_;
  assign _014_ = _000_ ^ data_i[2];
  assign _015_ = _014_ ^ data_i[1];
  assign _016_ = _015_ ^ _131_;
  assign _017_ = _142_ ? _151_ : _016_;
  assign in_data_basis_x[7] = _136_ ? _016_ : _017_;
  assign _018_ = ~mask_i[0];
  assign _019_ = ~(mask_i[3] ^ mask_i[6]);
  assign _020_ = _019_ ^ mask_i[2];
  assign _021_ = _020_ ^ mask_i[1];
  assign _022_ = _021_ ^ _018_;
  assign _023_ = ~(mask_i[5] ^ mask_i[6]);
  assign _024_ = _023_ ^ mask_i[4];
  assign _025_ = _024_ ^ mask_i[1];
  assign _026_ = _025_ ^ _018_;
  assign _027_ = _142_ ? _026_ : _022_;
  assign in_mask_basis_x[0] = _136_ ? _022_ : _027_;
  assign _028_ = _023_ ^ _018_;
  assign _029_ = ~(mask_i[4] ^ mask_i[3]);
  assign _030_ = _029_ ^ _018_;
  assign _031_ = _142_ ? _030_ : _028_;
  assign in_mask_basis_x[1] = _136_ ? _028_ : _031_;
  assign _032_ = mask_i[7] ^ mask_i[5];
  assign _033_ = _032_ ^ mask_i[2];
  assign _034_ = _142_ ? _033_ : mask_i[0];
  assign in_mask_basis_x[2] = _136_ ? mask_i[0] : _034_;
  assign _035_ = mask_i[4] ^ mask_i[7];
  assign _036_ = ~(_035_ ^ mask_i[3]);
  assign _037_ = _036_ ^ mask_i[1];
  assign _038_ = _037_ ^ _018_;
  assign _039_ = ~(mask_i[7] ^ mask_i[6]);
  assign _040_ = ~(_039_ ^ mask_i[4]);
  assign _041_ = _142_ ? _040_ : _038_;
  assign in_mask_basis_x[3] = _136_ ? _038_ : _041_;
  assign _042_ = _039_ ^ mask_i[5];
  assign _043_ = _042_ ^ _018_;
  assign _044_ = _019_ ^ mask_i[1];
  assign _045_ = _044_ ^ _018_;
  assign _046_ = _142_ ? _045_ : _043_;
  assign in_mask_basis_x[4] = _136_ ? _043_ : _046_;
  assign _047_ = _023_ ^ mask_i[1];
  assign _048_ = _047_ ^ _018_;
  assign _049_ = mask_i[4] ^ mask_i[6];
  assign _050_ = _142_ ? _049_ : _048_;
  assign in_mask_basis_x[5] = _136_ ? _048_ : _050_;
  assign _051_ = _024_ ^ _018_;
  assign _052_ = ~(_049_ ^ mask_i[1]);
  assign _053_ = _052_ ^ _018_;
  assign _054_ = _142_ ? _053_ : _051_;
  assign in_mask_basis_x[6] = _136_ ? _051_ : _054_;
  assign _055_ = _042_ ^ mask_i[2];
  assign _056_ = _055_ ^ mask_i[1];
  assign _057_ = _056_ ^ _018_;
  assign _058_ = _142_ ? _035_ : _057_;
  assign in_mask_basis_x[7] = _136_ ? _057_ : _058_;
  assign _059_ = prd_i[7] ^ prd_i[5];
  assign _060_ = _059_ ^ prd_i[2];
  assign out_mask_basis_x[2] = _142_ ? prd_i[0] : _060_;
  assign _061_ = ~prd_i[0];
  assign _062_ = ~(prd_i[4] ^ prd_i[7]);
  assign _063_ = _062_ ^ prd_i[3];
  assign _064_ = _063_ ^ prd_i[1];
  assign _065_ = _064_ ^ _061_;
  assign _066_ = ~(prd_i[7] ^ prd_i[6]);
  assign _067_ = ~(_066_ ^ prd_i[4]);
  assign out_mask_basis_x[3] = _142_ ? _065_ : _067_;
  assign _068_ = ~(prd_i[5] ^ prd_i[6]);
  assign _069_ = _068_ ^ prd_i[1];
  assign _070_ = _069_ ^ _061_;
  assign _071_ = ~(prd_i[4] ^ prd_i[6]);
  assign _072_ = ~_071_;
  assign out_mask_basis_x[5] = _142_ ? _070_ : _072_;
  assign _073_ = ~_062_;
  assign _074_ = _066_ ^ prd_i[5];
  assign _075_ = _074_ ^ prd_i[2];
  assign _076_ = _075_ ^ prd_i[1];
  assign _077_ = _076_ ^ _061_;
  assign out_mask_basis_x[7] = _142_ ? _077_ : _073_;
  assign _078_ = ~(out_data_basis_x[6] ^ out_data_basis_x[4]);
  assign _079_ = _078_ ^ out_data_basis_x[1];
  assign _080_ = _142_ ? out_data_basis_x[2] : _079_;
  assign data_o[0] = _136_ ? _079_ : _080_;
  assign _081_ = ~(out_data_basis_x[4] ^ out_data_basis_x[5]);
  assign _082_ = _081_ ^ out_data_basis_x[1];
  assign _083_ = out_data_basis_x[1] ^ out_data_basis_x[5];
  assign _084_ = _142_ ? _083_ : _082_;
  assign data_o[1] = _136_ ? _082_ : _084_;
  assign _085_ = ~out_data_basis_x[0];
  assign _086_ = ~(out_data_basis_x[6] ^ out_data_basis_x[5]);
  assign _087_ = _086_ ^ out_data_basis_x[3];
  assign _088_ = _087_ ^ out_data_basis_x[2];
  assign _089_ = _088_ ^ _085_;
  assign _090_ = ~out_data_basis_x[1];
  assign _091_ = ~(out_data_basis_x[7] ^ out_data_basis_x[5]);
  assign _092_ = _091_ ^ out_data_basis_x[4];
  assign _093_ = _092_ ^ _090_;
  assign _094_ = _142_ ? _093_ : _089_;
  assign data_o[2] = _136_ ? _089_ : _094_;
  assign _095_ = ~out_data_basis_x[3];
  assign _096_ = ~(out_data_basis_x[6] ^ out_data_basis_x[7]);
  assign _097_ = _096_ ^ out_data_basis_x[5];
  assign _098_ = _097_ ^ out_data_basis_x[4];
  assign _099_ = _098_ ^ _095_;
  assign _100_ = _086_ ^ out_data_basis_x[4];
  assign _101_ = _100_ ^ out_data_basis_x[3];
  assign _102_ = _101_ ^ out_data_basis_x[2];
  assign _103_ = _102_ ^ _090_;
  assign _104_ = _142_ ? _103_ : _099_;
  assign data_o[3] = _136_ ? _099_ : _104_;
  assign _105_ = _091_ ^ _095_;
  assign _106_ = out_data_basis_x[6] ^ out_data_basis_x[1];
  assign _107_ = _142_ ? _106_ : _105_;
  assign data_o[4] = _136_ ? _105_ : _107_;
  assign _108_ = ~(out_data_basis_x[0] ^ out_data_basis_x[6]);
  assign _109_ = _097_ ^ out_data_basis_x[3];
  assign _110_ = _109_ ^ out_data_basis_x[2];
  assign _111_ = _110_ ^ _085_;
  assign _112_ = _142_ ? _111_ : _108_;
  assign data_o[5] = _136_ ? _108_ : _112_;
  assign _113_ = ~(out_data_basis_x[3] ^ out_data_basis_x[7]);
  assign _114_ = _109_ ^ out_data_basis_x[1];
  assign _115_ = _114_ ^ _085_;
  assign _116_ = _142_ ? _115_ : _113_;
  assign data_o[6] = _136_ ? _113_ : _116_;
  assign _117_ = out_data_basis_x[3] ^ out_data_basis_x[5];
  assign _118_ = out_data_basis_x[4] ^ out_data_basis_x[1];
  assign _119_ = _142_ ? _118_ : _117_;
  assign data_o[7] = _136_ ? _117_ : _119_;
  assign _120_ = ~(prd_i[3] ^ prd_i[6]);
  assign _121_ = _120_ ^ prd_i[2];
  assign _122_ = _068_ ^ prd_i[4];
  assign _123_ = _142_ ? _121_ : _122_;
  assign _124_ = _123_ ^ prd_i[1];
  assign out_mask_basis_x[0] = _124_ ^ _061_;
  assign _125_ = ~(prd_i[4] ^ prd_i[3]);
  assign _126_ = _142_ ? _068_ : _125_;
  assign out_mask_basis_x[1] = _126_ ^ _061_;
  assign _127_ = _120_ ^ prd_i[1];
  assign _128_ = _142_ ? _074_ : _127_;
  assign out_mask_basis_x[4] = _128_ ^ _061_;
  assign _129_ = _071_ ^ prd_i[1];
  assign _130_ = _142_ ? _122_ : _129_;
  assign out_mask_basis_x[6] = _130_ ^ _061_;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_47_34/generated/aes_sbox_canright_masked_noreuse.v:423.35-429.3" *)
  aes_masked_inverse_gf2p8_noreuse u_aes_masked_inverse_gf2p8 (
    .a(in_data_basis_x),
    .a_inv(out_data_basis_x),
    .m(in_mask_basis_x),
    .n(out_mask_basis_x),
    .prd(prd_i[17:8])
  );
  assign mask_o = prd_i[7:0];
endmodule
