/* Generated by Yosys 0.35+7 (git sha1 5691cd095, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */




module _x5C_x24paramod_x2424c1c4c69a656d6e1653f476009c3cda79470efb_x5Caes_dom_dep_mul_gf2pn_deloop_x20(clk_i, rst_ni, we_i, a_x, a_y, b_x, b_y, a_x_q, a_y_q, b_x_q, b_y_q, z_0, z_1, a_q, b_q, prd_o);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  
  output [1:0] a_q;
  wire [1:0] a_q;
  
  input [1:0] a_x;
  wire [1:0] a_x;
  
  input [1:0] a_x_q;
  wire [1:0] a_x_q;
  
  input [1:0] a_y;
  wire [1:0] a_y;
  
  input [1:0] a_y_q;
  wire [1:0] a_y_q;
  
  wire [1:0] a_yz0_d;
  
  wire [1:0] a_yz0_q;
  
  wire [1:0] axz0_z1_d;
  
  wire [1:0] axz0_z1_q;
  
  output [1:0] b_q;
  wire [1:0] b_q;
  
  input [1:0] b_x;
  wire [1:0] b_x;
  
  input [1:0] b_x_q;
  wire [1:0] b_x_q;
  
  input [1:0] b_y;
  wire [1:0] b_y;
  
  input [1:0] b_y_q;
  wire [1:0] b_y_q;
  
  wire [1:0] b_yz0_d;
  
  wire [1:0] bxz0_z1_d;
  
  input clk_i;
  wire clk_i;
  
  wire [1:0] _x5Cgen_not_pre_dom_indep_x2Ea_b_x20;
  
  wire [1:0] _x5Cgen_not_pre_dom_indep_x2Ea_b_buf_x20;
  
  wire [1:0] _x5Cgen_not_pre_dom_indep_x2Ea_mul_ax_b_x20;
  
  wire [1:0] _x5Cgen_not_pre_dom_indep_x2Ea_mul_ax_b_buf_x20;
  
  wire [1:0] _x5Cgen_not_pre_dom_indep_x2Eb_b_x20;
  
  wire [1:0] _x5Cgen_not_pre_dom_indep_x2Eb_b_buf_x20;
  
  wire [1:0] _x5Cgen_not_pre_dom_indep_x2Eb_mul_bx_b_x20;
  
  wire [1:0] _x5Cgen_not_pre_dom_indep_x2Eb_mul_bx_b_buf_x20;
  
  wire [1:0] mul_ax_z0;
  
  wire [1:0] mul_ax_z0_buf;
  
  wire [1:0] mul_bx_z0;
  
  wire [1:0] mul_bx_z0_buf;
  
  output [3:0] prd_o;
  wire [3:0] prd_o;
  
  input rst_ni;
  wire rst_ni;
  
  input we_i;
  wire we_i;
  
  input [1:0] z_0;
  wire [1:0] z_0;
  
  input [1:0] z_1;
  wire [1:0] z_1;
  assign a_yz0_d[0] = a_y[0] ^ z_0[0];
  assign a_yz0_d[1] = a_y[1] ^ z_0[1];
  assign b_yz0_d[0] = b_y[0] ^ z_0[0];
  assign b_yz0_d[1] = b_y[1] ^ z_0[1];
  assign axz0_z1_d[0] = z_1[0] ^ mul_ax_z0_buf[0];
  assign axz0_z1_d[1] = z_1[1] ^ mul_ax_z0_buf[1];
  assign bxz0_z1_d[0] = mul_bx_z0_buf[0] ^ z_1[0];
  assign bxz0_z1_d[1] = mul_bx_z0_buf[1] ^ z_1[1];
  assign _02_ = z_0[1] & a_x[1];
  assign _03_ = ~(a_x[1] ^ a_x[0]);
  assign _04_ = z_0[1] ^ z_0[0];
  assign _05_ = _04_ & ~(_03_);
  assign mul_ax_z0[1] = _05_ ^ _02_;
  assign _06_ = z_0[0] & a_x[0];
  assign mul_ax_z0[0] = _06_ ^ _05_;
  assign _07_ = b_x[1] & z_0[1];
  assign _08_ = ~(b_x[1] ^ b_x[0]);
  assign _09_ = _04_ & ~(_08_);
  assign mul_bx_z0[1] = _09_ ^ _07_;
  assign _10_ = b_x[0] & z_0[0];
  assign mul_bx_z0[0] = _10_ ^ _09_;
  assign _x5Cgen_not_pre_dom_indep_x2Ea_b_x20[0] = prd_o[2] ^ a_y_q[0];
  assign _x5Cgen_not_pre_dom_indep_x2Ea_b_x20[1] = prd_o[3] ^ a_y_q[1];
  assign _x5Cgen_not_pre_dom_indep_x2Eb_b_x20[0] = a_yz0_q[0] ^ b_y_q[0];
  assign _x5Cgen_not_pre_dom_indep_x2Eb_b_x20[1] = a_yz0_q[1] ^ b_y_q[1];
  assign _11_ = _x5Cgen_not_pre_dom_indep_x2Ea_b_buf_x20[1] & a_x_q[1];
  assign _12_ = a_x_q[1] ^ a_x_q[0];
  assign _13_ = ~(_x5Cgen_not_pre_dom_indep_x2Ea_b_buf_x20[1] ^ _x5Cgen_not_pre_dom_indep_x2Ea_b_buf_x20[0]);
  assign _14_ = _12_ & ~(_13_);
  assign _x5Cgen_not_pre_dom_indep_x2Ea_mul_ax_b_x20[1] = _14_ ^ _11_;
  assign _15_ = _x5Cgen_not_pre_dom_indep_x2Ea_b_buf_x20[0] & a_x_q[0];
  assign _x5Cgen_not_pre_dom_indep_x2Ea_mul_ax_b_x20[0] = _15_ ^ _14_;
  assign _16_ = _x5Cgen_not_pre_dom_indep_x2Eb_b_buf_x20[1] & b_x_q[1];
  assign _17_ = b_x_q[1] ^ b_x_q[0];
  assign _18_ = ~(_x5Cgen_not_pre_dom_indep_x2Eb_b_buf_x20[1] ^ _x5Cgen_not_pre_dom_indep_x2Eb_b_buf_x20[0]);
  assign _00_ = _17_ & ~(_18_);
  assign _x5Cgen_not_pre_dom_indep_x2Eb_mul_bx_b_x20[1] = _00_ ^ _16_;
  assign _01_ = _x5Cgen_not_pre_dom_indep_x2Eb_b_buf_x20[0] & b_x_q[0];
  assign _x5Cgen_not_pre_dom_indep_x2Eb_mul_bx_b_x20[0] = _01_ ^ _00_;
  assign a_q[0] = _x5Cgen_not_pre_dom_indep_x2Ea_mul_ax_b_buf_x20[0] ^ axz0_z1_q[0];
  assign a_q[1] = _x5Cgen_not_pre_dom_indep_x2Ea_mul_ax_b_buf_x20[1] ^ axz0_z1_q[1];
  assign b_q[0] = _x5Cgen_not_pre_dom_indep_x2Eb_mul_bx_b_buf_x20[0] ^ prd_o[0];
  assign b_q[1] = _x5Cgen_not_pre_dom_indep_x2Eb_mul_bx_b_buf_x20[1] ^ prd_o[1];
  
  _x5C_x24paramod_x5Cprim_xilinx_buf_x5CWidth_x3D32_x2700000000000000000000000000000100_x20 _x5Cgen_not_pre_dom_indep_x2Eu_prim_xilinx_buf_ab_b_x20 (
    .in_i({ _x5Cgen_not_pre_dom_indep_x2Ea_b_x20, _x5Cgen_not_pre_dom_indep_x2Eb_b_x20 }),
    .out_o({ _x5Cgen_not_pre_dom_indep_x2Ea_b_buf_x20, _x5Cgen_not_pre_dom_indep_x2Eb_b_buf_x20 })
  );
  
  _x5C_x24paramod_x5Cprim_xilinx_buf_x5CWidth_x3D32_x2700000000000000000000000000000100_x20 _x5Cgen_not_pre_dom_indep_x2Eu_prim_xilinx_buf_ab_mul_abx_b_x20 (
    .in_i({ _x5Cgen_not_pre_dom_indep_x2Ea_mul_ax_b_x20, _x5Cgen_not_pre_dom_indep_x2Eb_mul_bx_b_x20 }),
    .out_o({ _x5Cgen_not_pre_dom_indep_x2Ea_mul_ax_b_buf_x20, _x5Cgen_not_pre_dom_indep_x2Eb_mul_bx_b_buf_x20 })
  );
  
  _x5C_x24paramod_x5Cprim_xilinx_buf_x5CWidth_x3D32_x2700000000000000000000000000000100_x20 u_prim_xilinx_buf_mul_abx_z0 (
    .in_i({ mul_ax_z0, mul_bx_z0 }),
    .out_o({ mul_ax_z0_buf, mul_bx_z0_buf })
  );
  
  _x5C_x24paramod_x5Cprim_xilinx_flop_en_x5CWidth_x3D32_x2700000000000000000000000000000100_x5CResetValue_x3Ds1_x270_x20 u_prim_xilinx_flop_ab_yz0 (
    .clk_i(clk_i),
    .d_i({ a_yz0_d, b_yz0_d }),
    .en_i(we_i),
    .q_o({ a_yz0_q, prd_o[3:2] }),
    .rst_ni(rst_ni)
  );
  
  _x5C_x24paramod_x5Cprim_xilinx_flop_en_x5CWidth_x3D32_x2700000000000000000000000000000100_x5CResetValue_x3Ds1_x270_x20 u_prim_xilinx_flop_abxz0_z1 (
    .clk_i(clk_i),
    .d_i({ axz0_z1_d, bxz0_z1_d }),
    .en_i(we_i),
    .q_o({ axz0_z1_q, prd_o[1:0] }),
    .rst_ni(rst_ni)
  );
endmodule




module _x5C_x24paramod_x246042b1c7ace30ff79de13c5dcb11899d0e013023_x5Caes_dom_dep_mul_gf2pn_deloop_x20(clk_i, rst_ni, we_i, a_x, a_y, b_x, b_y, a_x_q, a_y_q, b_x_q, b_y_q, z_0, z_1, a_q, b_q, prd_o);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  
  output [3:0] a_q;
  wire [3:0] a_q;
  
  input [3:0] a_x;
  wire [3:0] a_x;
  
  input [3:0] a_x_q;
  wire [3:0] a_x_q;
  
  input [3:0] a_y;
  wire [3:0] a_y;
  
  input [3:0] a_y_q;
  wire [3:0] a_y_q;
  
  wire [3:0] a_yz0_d;
  
  wire [3:0] a_yz0_q;
  
  wire [3:0] axz0_z1_d;
  
  wire [3:0] axz0_z1_q;
  
  output [3:0] b_q;
  wire [3:0] b_q;
  
  input [3:0] b_x;
  wire [3:0] b_x;
  
  input [3:0] b_x_q;
  wire [3:0] b_x_q;
  
  input [3:0] b_y;
  wire [3:0] b_y;
  
  input [3:0] b_y_q;
  wire [3:0] b_y_q;
  
  wire [3:0] b_yz0_d;
  
  wire [3:0] bxz0_z1_d;
  
  input clk_i;
  wire clk_i;
  
  wire [3:0] _x5Cgen_not_pre_dom_indep_x2Ea_b_x20;
  
  wire [3:0] _x5Cgen_not_pre_dom_indep_x2Ea_b_buf_x20;
  
  wire [3:0] _x5Cgen_not_pre_dom_indep_x2Ea_mul_ax_b_x20;
  
  wire [3:0] _x5Cgen_not_pre_dom_indep_x2Ea_mul_ax_b_buf_x20;
  
  wire [3:0] _x5Cgen_not_pre_dom_indep_x2Eb_b_x20;
  
  wire [3:0] _x5Cgen_not_pre_dom_indep_x2Eb_b_buf_x20;
  
  wire [3:0] _x5Cgen_not_pre_dom_indep_x2Eb_mul_bx_b_x20;
  
  wire [3:0] _x5Cgen_not_pre_dom_indep_x2Eb_mul_bx_b_buf_x20;
  
  wire [3:0] mul_ax_z0;
  
  wire [3:0] mul_ax_z0_buf;
  
  wire [3:0] mul_bx_z0;
  
  wire [3:0] mul_bx_z0_buf;
  
  output [7:0] prd_o;
  wire [7:0] prd_o;
  
  input rst_ni;
  wire rst_ni;
  
  input we_i;
  wire we_i;
  
  input [3:0] z_0;
  wire [3:0] z_0;
  
  input [3:0] z_1;
  wire [3:0] z_1;
  assign a_yz0_d[0] = a_y[0] ^ z_0[0];
  assign a_yz0_d[1] = a_y[1] ^ z_0[1];
  assign a_yz0_d[2] = a_y[2] ^ z_0[2];
  assign a_yz0_d[3] = a_y[3] ^ z_0[3];
  assign b_yz0_d[0] = b_y[0] ^ z_0[0];
  assign b_yz0_d[1] = b_y[1] ^ z_0[1];
  assign b_yz0_d[2] = b_y[2] ^ z_0[2];
  assign b_yz0_d[3] = b_y[3] ^ z_0[3];
  assign axz0_z1_d[0] = z_1[0] ^ mul_ax_z0_buf[0];
  assign axz0_z1_d[1] = z_1[1] ^ mul_ax_z0_buf[1];
  assign axz0_z1_d[2] = z_1[2] ^ mul_ax_z0_buf[2];
  assign axz0_z1_d[3] = z_1[3] ^ mul_ax_z0_buf[3];
  assign bxz0_z1_d[0] = mul_bx_z0_buf[0] ^ z_1[0];
  assign bxz0_z1_d[1] = mul_bx_z0_buf[1] ^ z_1[1];
  assign bxz0_z1_d[2] = mul_bx_z0_buf[2] ^ z_1[2];
  assign bxz0_z1_d[3] = mul_bx_z0_buf[3] ^ z_1[3];
  assign _000_ = z_0[2] & a_x[2];
  assign _001_ = a_x[3] ^ a_x[2];
  assign _002_ = ~(z_0[3] ^ z_0[2]);
  assign _003_ = _002_ | ~(_001_);
  assign _004_ = _003_ ^ _000_;
  assign _005_ = ~(a_x[1] ^ a_x[3]);
  assign _006_ = z_0[1] ^ z_0[3];
  assign _007_ = _006_ & ~(_005_);
  assign _008_ = ~(a_x[0] ^ a_x[2]);
  assign _009_ = _008_ ^ _005_;
  assign _010_ = z_0[0] ^ z_0[2];
  assign _011_ = ~(_010_ ^ _006_);
  assign _012_ = _011_ | ~(_009_);
  assign _013_ = ~(_012_ ^ _007_);
  assign _014_ = _010_ & ~(_008_);
  assign _015_ = _014_ ^ _012_;
  assign _016_ = _015_ ^ _013_;
  assign mul_ax_z0[2] = _016_ ^ _004_;
  assign _017_ = z_0[3] & a_x[3];
  assign _018_ = _017_ ^ _003_;
  assign mul_ax_z0[3] = _018_ ^ _015_;
  assign _019_ = z_0[0] & a_x[0];
  assign _020_ = a_x[1] ^ a_x[0];
  assign _021_ = ~(z_0[1] ^ z_0[0]);
  assign _022_ = _021_ | ~(_020_);
  assign _023_ = _022_ ^ _019_;
  assign mul_ax_z0[0] = _023_ ^ _016_;
  assign _024_ = z_0[1] & a_x[1];
  assign _025_ = _024_ ^ _022_;
  assign mul_ax_z0[1] = _025_ ^ _015_;
  assign _026_ = b_x[2] & z_0[2];
  assign _027_ = ~(b_x[3] ^ b_x[2]);
  assign _028_ = _027_ | _002_;
  assign _029_ = _028_ ^ _026_;
  assign _030_ = b_x[1] ^ b_x[3];
  assign _031_ = ~(_030_ & _006_);
  assign _032_ = ~(b_x[0] ^ b_x[2]);
  assign _033_ = _032_ ^ _030_;
  assign _034_ = _033_ | _011_;
  assign _035_ = _034_ ^ _031_;
  assign _036_ = _010_ & ~(_032_);
  assign _037_ = _036_ ^ _034_;
  assign _038_ = _037_ ^ _035_;
  assign mul_bx_z0[2] = _038_ ^ _029_;
  assign _039_ = b_x[3] & z_0[3];
  assign _040_ = _039_ ^ _028_;
  assign mul_bx_z0[3] = _040_ ^ _037_;
  assign _041_ = b_x[0] & z_0[0];
  assign _042_ = ~(b_x[1] ^ b_x[0]);
  assign _043_ = _042_ | _021_;
  assign _044_ = _043_ ^ _041_;
  assign mul_bx_z0[0] = _044_ ^ _038_;
  assign _045_ = b_x[1] & z_0[1];
  assign _046_ = _045_ ^ _043_;
  assign mul_bx_z0[1] = _046_ ^ _037_;
  assign _x5Cgen_not_pre_dom_indep_x2Ea_b_x20[0] = prd_o[4] ^ a_y_q[0];
  assign _x5Cgen_not_pre_dom_indep_x2Ea_b_x20[1] = prd_o[5] ^ a_y_q[1];
  assign _x5Cgen_not_pre_dom_indep_x2Ea_b_x20[2] = prd_o[6] ^ a_y_q[2];
  assign _x5Cgen_not_pre_dom_indep_x2Ea_b_x20[3] = prd_o[7] ^ a_y_q[3];
  assign _x5Cgen_not_pre_dom_indep_x2Eb_b_x20[0] = a_yz0_q[0] ^ b_y_q[0];
  assign _x5Cgen_not_pre_dom_indep_x2Eb_b_x20[1] = a_yz0_q[1] ^ b_y_q[1];
  assign _x5Cgen_not_pre_dom_indep_x2Eb_b_x20[2] = a_yz0_q[2] ^ b_y_q[2];
  assign _x5Cgen_not_pre_dom_indep_x2Eb_b_x20[3] = a_yz0_q[3] ^ b_y_q[3];
  assign _047_ = _x5Cgen_not_pre_dom_indep_x2Ea_b_buf_x20[2] & a_x_q[2];
  assign _048_ = a_x_q[3] ^ a_x_q[2];
  assign _049_ = ~(_x5Cgen_not_pre_dom_indep_x2Ea_b_buf_x20[3] ^ _x5Cgen_not_pre_dom_indep_x2Ea_b_buf_x20[2]);
  assign _050_ = _049_ | ~(_048_);
  assign _051_ = _050_ ^ _047_;
  assign _052_ = ~(a_x_q[1] ^ a_x_q[3]);
  assign _053_ = _x5Cgen_not_pre_dom_indep_x2Ea_b_buf_x20[1] ^ _x5Cgen_not_pre_dom_indep_x2Ea_b_buf_x20[3];
  assign _054_ = _053_ & ~(_052_);
  assign _055_ = ~(a_x_q[0] ^ a_x_q[2]);
  assign _056_ = _055_ ^ _052_;
  assign _057_ = ~(_x5Cgen_not_pre_dom_indep_x2Ea_b_buf_x20[0] ^ _x5Cgen_not_pre_dom_indep_x2Ea_b_buf_x20[2]);
  assign _058_ = _057_ ^ _053_;
  assign _059_ = _058_ | ~(_056_);
  assign _060_ = ~(_059_ ^ _054_);
  assign _061_ = ~(_057_ | _055_);
  assign _062_ = _061_ ^ _059_;
  assign _063_ = _062_ ^ _060_;
  assign _x5Cgen_not_pre_dom_indep_x2Ea_mul_ax_b_x20[2] = _063_ ^ _051_;
  assign _064_ = _x5Cgen_not_pre_dom_indep_x2Ea_b_buf_x20[3] & a_x_q[3];
  assign _065_ = _064_ ^ _050_;
  assign _x5Cgen_not_pre_dom_indep_x2Ea_mul_ax_b_x20[3] = _065_ ^ _062_;
  assign _066_ = _x5Cgen_not_pre_dom_indep_x2Ea_b_buf_x20[0] & a_x_q[0];
  assign _067_ = a_x_q[1] ^ a_x_q[0];
  assign _068_ = ~(_x5Cgen_not_pre_dom_indep_x2Ea_b_buf_x20[1] ^ _x5Cgen_not_pre_dom_indep_x2Ea_b_buf_x20[0]);
  assign _069_ = _068_ | ~(_067_);
  assign _070_ = _069_ ^ _066_;
  assign _x5Cgen_not_pre_dom_indep_x2Ea_mul_ax_b_x20[0] = _070_ ^ _063_;
  assign _071_ = _x5Cgen_not_pre_dom_indep_x2Ea_b_buf_x20[1] & a_x_q[1];
  assign _072_ = _071_ ^ _069_;
  assign _x5Cgen_not_pre_dom_indep_x2Ea_mul_ax_b_x20[1] = _072_ ^ _062_;
  assign _073_ = _x5Cgen_not_pre_dom_indep_x2Eb_b_buf_x20[2] & b_x_q[2];
  assign _074_ = b_x_q[3] ^ b_x_q[2];
  assign _075_ = ~(_x5Cgen_not_pre_dom_indep_x2Eb_b_buf_x20[3] ^ _x5Cgen_not_pre_dom_indep_x2Eb_b_buf_x20[2]);
  assign _076_ = _075_ | ~(_074_);
  assign _077_ = _076_ ^ _073_;
  assign _078_ = ~(b_x_q[1] ^ b_x_q[3]);
  assign _079_ = _x5Cgen_not_pre_dom_indep_x2Eb_b_buf_x20[1] ^ _x5Cgen_not_pre_dom_indep_x2Eb_b_buf_x20[3];
  assign _080_ = _079_ & ~(_078_);
  assign _081_ = ~(b_x_q[0] ^ b_x_q[2]);
  assign _082_ = _081_ ^ _078_;
  assign _083_ = ~(_x5Cgen_not_pre_dom_indep_x2Eb_b_buf_x20[0] ^ _x5Cgen_not_pre_dom_indep_x2Eb_b_buf_x20[2]);
  assign _084_ = _083_ ^ _079_;
  assign _085_ = _084_ | ~(_082_);
  assign _086_ = ~(_085_ ^ _080_);
  assign _087_ = ~(_083_ | _081_);
  assign _088_ = _087_ ^ _085_;
  assign _089_ = _088_ ^ _086_;
  assign _x5Cgen_not_pre_dom_indep_x2Eb_mul_bx_b_x20[2] = _089_ ^ _077_;
  assign _090_ = _x5Cgen_not_pre_dom_indep_x2Eb_b_buf_x20[3] & b_x_q[3];
  assign _091_ = _090_ ^ _076_;
  assign _x5Cgen_not_pre_dom_indep_x2Eb_mul_bx_b_x20[3] = _091_ ^ _088_;
  assign _092_ = _x5Cgen_not_pre_dom_indep_x2Eb_b_buf_x20[0] & b_x_q[0];
  assign _093_ = b_x_q[1] ^ b_x_q[0];
  assign _094_ = ~(_x5Cgen_not_pre_dom_indep_x2Eb_b_buf_x20[1] ^ _x5Cgen_not_pre_dom_indep_x2Eb_b_buf_x20[0]);
  assign _095_ = _094_ | ~(_093_);
  assign _096_ = _095_ ^ _092_;
  assign _x5Cgen_not_pre_dom_indep_x2Eb_mul_bx_b_x20[0] = _096_ ^ _089_;
  assign _097_ = _x5Cgen_not_pre_dom_indep_x2Eb_b_buf_x20[1] & b_x_q[1];
  assign _098_ = _097_ ^ _095_;
  assign _x5Cgen_not_pre_dom_indep_x2Eb_mul_bx_b_x20[1] = _098_ ^ _088_;
  assign a_q[0] = _x5Cgen_not_pre_dom_indep_x2Ea_mul_ax_b_buf_x20[0] ^ axz0_z1_q[0];
  assign a_q[1] = _x5Cgen_not_pre_dom_indep_x2Ea_mul_ax_b_buf_x20[1] ^ axz0_z1_q[1];
  assign a_q[2] = _x5Cgen_not_pre_dom_indep_x2Ea_mul_ax_b_buf_x20[2] ^ axz0_z1_q[2];
  assign a_q[3] = _x5Cgen_not_pre_dom_indep_x2Ea_mul_ax_b_buf_x20[3] ^ axz0_z1_q[3];
  assign b_q[0] = _x5Cgen_not_pre_dom_indep_x2Eb_mul_bx_b_buf_x20[0] ^ prd_o[0];
  assign b_q[1] = _x5Cgen_not_pre_dom_indep_x2Eb_mul_bx_b_buf_x20[1] ^ prd_o[1];
  assign b_q[2] = _x5Cgen_not_pre_dom_indep_x2Eb_mul_bx_b_buf_x20[2] ^ prd_o[2];
  assign b_q[3] = _x5Cgen_not_pre_dom_indep_x2Eb_mul_bx_b_buf_x20[3] ^ prd_o[3];
  
  _x5C_x24paramod_x5Cprim_xilinx_buf_x5CWidth_x3D32_x2700000000000000000000000000001000_x20 _x5Cgen_not_pre_dom_indep_x2Eu_prim_xilinx_buf_ab_b_x20 (
    .in_i({ _x5Cgen_not_pre_dom_indep_x2Ea_b_x20, _x5Cgen_not_pre_dom_indep_x2Eb_b_x20 }),
    .out_o({ _x5Cgen_not_pre_dom_indep_x2Ea_b_buf_x20, _x5Cgen_not_pre_dom_indep_x2Eb_b_buf_x20 })
  );
  
  _x5C_x24paramod_x5Cprim_xilinx_buf_x5CWidth_x3D32_x2700000000000000000000000000001000_x20 _x5Cgen_not_pre_dom_indep_x2Eu_prim_xilinx_buf_ab_mul_abx_b_x20 (
    .in_i({ _x5Cgen_not_pre_dom_indep_x2Ea_mul_ax_b_x20, _x5Cgen_not_pre_dom_indep_x2Eb_mul_bx_b_x20 }),
    .out_o({ _x5Cgen_not_pre_dom_indep_x2Ea_mul_ax_b_buf_x20, _x5Cgen_not_pre_dom_indep_x2Eb_mul_bx_b_buf_x20 })
  );
  
  _x5C_x24paramod_x5Cprim_xilinx_buf_x5CWidth_x3D32_x2700000000000000000000000000001000_x20 u_prim_xilinx_buf_mul_abx_z0 (
    .in_i({ mul_ax_z0, mul_bx_z0 }),
    .out_o({ mul_ax_z0_buf, mul_bx_z0_buf })
  );
  
  _x5C_x24paramod_x5Cprim_xilinx_flop_en_x5CWidth_x3D32_x2700000000000000000000000000001000_x5CResetValue_x3Ds1_x270_x20 u_prim_xilinx_flop_ab_yz0 (
    .clk_i(clk_i),
    .d_i({ a_yz0_d, b_yz0_d }),
    .en_i(we_i),
    .q_o({ a_yz0_q, prd_o[7:4] }),
    .rst_ni(rst_ni)
  );
  
  _x5C_x24paramod_x5Cprim_xilinx_flop_en_x5CWidth_x3D32_x2700000000000000000000000000001000_x5CResetValue_x3Ds1_x270_x20 u_prim_xilinx_flop_abxz0_z1 (
    .clk_i(clk_i),
    .d_i({ axz0_z1_d, bxz0_z1_d }),
    .en_i(we_i),
    .q_o({ axz0_z1_q, prd_o[3:0] }),
    .rst_ni(rst_ni)
  );
endmodule




module _x5C_x24paramod_x5Caes_dom_indep_mul_gf2pn_deloop_x5CNPower_x3Ds32_x2700000000000000000000000000000100_x5CPipeline_x3D1_x271_x20(clk_i, rst_ni, we_i, a_x, a_y, b_x, b_y, z_0, a_q, b_q);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  
  output [3:0] a_q;
  wire [3:0] a_q;
  
  input [3:0] a_x;
  wire [3:0] a_x;
  
  input [3:0] a_y;
  wire [3:0] a_y;
  
  wire [3:0] aq_z0_d;
  
  wire [3:0] aq_z0_q;
  
  output [3:0] b_q;
  wire [3:0] b_q;
  
  input [3:0] b_x;
  wire [3:0] b_x;
  
  input [3:0] b_y;
  wire [3:0] b_y;
  
  wire [3:0] bq_z0_d;
  
  wire [3:0] bq_z0_q;
  
  input clk_i;
  wire clk_i;
  
  wire [3:0] _x5Cgen_pipeline_x2Emul_ax_ay_q_x20;
  
  wire [3:0] _x5Cgen_pipeline_x2Emul_bx_by_q_x20;
  
  wire [3:0] mul_ax_ay_d;
  
  wire [3:0] mul_bx_by_d;
  
  input rst_ni;
  wire rst_ni;
  
  input we_i;
  wire we_i;
  
  input [3:0] z_0;
  wire [3:0] z_0;
  assign _061_ = ~z_0[0];
  assign _062_ = ~(b_y[0] & a_x[0]);
  assign _063_ = ~(a_x[1] ^ a_x[0]);
  assign _064_ = ~(b_y[1] ^ b_y[0]);
  assign _065_ = _064_ | _063_;
  assign _066_ = ~(_065_ ^ _062_);
  assign _067_ = ~(a_x[1] ^ a_x[3]);
  assign _068_ = ~(b_y[1] ^ b_y[3]);
  assign _069_ = _068_ | _067_;
  assign _070_ = a_x[0] ^ a_x[2];
  assign _071_ = _070_ ^ _067_;
  assign _072_ = ~(b_y[0] ^ b_y[2]);
  assign _073_ = ~(_072_ ^ _068_);
  assign _074_ = ~(_073_ | _071_);
  assign _075_ = ~(_074_ ^ _069_);
  assign _076_ = _070_ & ~(_072_);
  assign _077_ = _076_ ^ _074_;
  assign _078_ = _077_ ^ _075_;
  assign _079_ = _078_ ^ _066_;
  assign aq_z0_d[0] = _079_ ^ _061_;
  assign _080_ = ~z_0[1];
  assign _081_ = b_y[1] & a_x[1];
  assign _082_ = _081_ ^ _065_;
  assign _083_ = _082_ ^ _077_;
  assign aq_z0_d[1] = _083_ ^ _080_;
  assign _084_ = ~z_0[2];
  assign _085_ = b_y[2] & a_x[2];
  assign _086_ = ~(a_x[3] ^ a_x[2]);
  assign _087_ = ~(b_y[3] ^ b_y[2]);
  assign _088_ = _087_ | _086_;
  assign _089_ = _088_ ^ _085_;
  assign _090_ = _089_ ^ _078_;
  assign aq_z0_d[2] = _090_ ^ _084_;
  assign _091_ = ~z_0[3];
  assign _092_ = b_y[3] & a_x[3];
  assign _093_ = _092_ ^ _088_;
  assign _094_ = _093_ ^ _077_;
  assign aq_z0_d[3] = _094_ ^ _091_;
  assign _095_ = ~(b_x[0] & a_y[0]);
  assign _000_ = ~(a_y[1] ^ a_y[0]);
  assign _001_ = ~(b_x[1] ^ b_x[0]);
  assign _002_ = _001_ | _000_;
  assign _003_ = ~(_002_ ^ _095_);
  assign _004_ = ~(a_y[1] ^ a_y[3]);
  assign _005_ = ~(b_x[1] ^ b_x[3]);
  assign _006_ = _005_ | _004_;
  assign _007_ = ~(a_y[0] ^ a_y[2]);
  assign _008_ = ~(_007_ ^ _004_);
  assign _009_ = ~(b_x[0] ^ b_x[2]);
  assign _010_ = ~(_009_ ^ _005_);
  assign _011_ = ~(_010_ | _008_);
  assign _012_ = ~(_011_ ^ _006_);
  assign _013_ = ~(_009_ | _007_);
  assign _014_ = _013_ ^ _011_;
  assign _015_ = _014_ ^ _012_;
  assign _016_ = _015_ ^ _003_;
  assign bq_z0_d[0] = _016_ ^ _061_;
  assign _017_ = b_x[1] & a_y[1];
  assign _018_ = _017_ ^ _002_;
  assign _019_ = _018_ ^ _014_;
  assign bq_z0_d[1] = _019_ ^ _080_;
  assign _020_ = b_x[2] & a_y[2];
  assign _021_ = ~(a_y[3] ^ a_y[2]);
  assign _022_ = ~(b_x[3] ^ b_x[2]);
  assign _023_ = _022_ | _021_;
  assign _024_ = _023_ ^ _020_;
  assign _025_ = _024_ ^ _015_;
  assign bq_z0_d[2] = _025_ ^ _084_;
  assign _026_ = b_x[3] & a_y[3];
  assign _027_ = _026_ ^ _023_;
  assign _028_ = _027_ ^ _014_;
  assign bq_z0_d[3] = _028_ ^ _091_;
  assign a_q[0] = aq_z0_q[0] ^ _x5Cgen_pipeline_x2Emul_ax_ay_q_x20[0];
  assign a_q[1] = aq_z0_q[1] ^ _x5Cgen_pipeline_x2Emul_ax_ay_q_x20[1];
  assign a_q[2] = aq_z0_q[2] ^ _x5Cgen_pipeline_x2Emul_ax_ay_q_x20[2];
  assign a_q[3] = aq_z0_q[3] ^ _x5Cgen_pipeline_x2Emul_ax_ay_q_x20[3];
  assign b_q[0] = bq_z0_q[0] ^ _x5Cgen_pipeline_x2Emul_bx_by_q_x20[0];
  assign b_q[1] = bq_z0_q[1] ^ _x5Cgen_pipeline_x2Emul_bx_by_q_x20[1];
  assign b_q[2] = bq_z0_q[2] ^ _x5Cgen_pipeline_x2Emul_bx_by_q_x20[2];
  assign b_q[3] = bq_z0_q[3] ^ _x5Cgen_pipeline_x2Emul_bx_by_q_x20[3];
  assign _029_ = a_y[2] & a_x[2];
  assign _030_ = _021_ | _086_;
  assign _031_ = _030_ ^ _029_;
  assign _032_ = _004_ | _067_;
  assign _033_ = _008_ | _071_;
  assign _034_ = _033_ ^ _032_;
  assign _035_ = _070_ & ~(_007_);
  assign _036_ = _035_ ^ _033_;
  assign _037_ = _036_ ^ _034_;
  assign mul_ax_ay_d[2] = _037_ ^ _031_;
  assign _038_ = a_y[3] & a_x[3];
  assign _039_ = _038_ ^ _030_;
  assign mul_ax_ay_d[3] = _039_ ^ _036_;
  assign _040_ = a_y[0] & a_x[0];
  assign _041_ = _000_ | _063_;
  assign _042_ = _041_ ^ _040_;
  assign mul_ax_ay_d[0] = _042_ ^ _037_;
  assign _043_ = a_y[1] & a_x[1];
  assign _044_ = _043_ ^ _041_;
  assign mul_ax_ay_d[1] = _044_ ^ _036_;
  assign _045_ = b_y[2] & b_x[2];
  assign _046_ = _022_ | _087_;
  assign _047_ = _046_ ^ _045_;
  assign _048_ = _005_ | _068_;
  assign _049_ = _010_ | _073_;
  assign _050_ = _049_ ^ _048_;
  assign _051_ = ~(_009_ | _072_);
  assign _052_ = _051_ ^ _049_;
  assign _053_ = _052_ ^ _050_;
  assign mul_bx_by_d[2] = _053_ ^ _047_;
  assign _054_ = b_y[3] & b_x[3];
  assign _055_ = _054_ ^ _046_;
  assign mul_bx_by_d[3] = _055_ ^ _052_;
  assign _056_ = b_y[0] & b_x[0];
  assign _057_ = _001_ | _064_;
  assign _058_ = _057_ ^ _056_;
  assign mul_bx_by_d[0] = _058_ ^ _053_;
  assign _059_ = b_y[1] & b_x[1];
  assign _060_ = _059_ ^ _057_;
  assign mul_bx_by_d[1] = _060_ ^ _052_;
  
  _x5C_x24paramod_x5Cprim_xilinx_flop_en_x5CWidth_x3D32_x2700000000000000000000000000001000_x5CResetValue_x3Ds1_x270_x20 _x5Cgen_pipeline_x2Eu_prim_xilinx_flop_mul_abx_aby_x20 (
    .clk_i(clk_i),
    .d_i({ mul_ax_ay_d, mul_bx_by_d }),
    .en_i(we_i),
    .q_o({ _x5Cgen_pipeline_x2Emul_ax_ay_q_x20, _x5Cgen_pipeline_x2Emul_bx_by_q_x20 }),
    .rst_ni(rst_ni)
  );
  
  _x5C_x24paramod_x5Cprim_xilinx_flop_en_x5CWidth_x3D32_x2700000000000000000000000000001000_x5CResetValue_x3Ds1_x270_x20 u_prim_xilinx_flop_abq_z0 (
    .clk_i(clk_i),
    .d_i({ aq_z0_d, bq_z0_d }),
    .en_i(we_i),
    .q_o({ aq_z0_q, bq_z0_q }),
    .rst_ni(rst_ni)
  );
endmodule



module _x5C_x24paramod_x5Caes_dom_inverse_gf2p4_deloop_x5CPipelineMul_x3D1_x271_x20(clk_i, rst_ni, we_i, a_gamma, b_gamma, prd_2_i, prd_3_i, a_gamma_inv, b_gamma_inv, prd_2_o, prd_3_o);
  wire _00_;
  wire _01_;
  
  input [3:0] a_gamma;
  wire [3:0] a_gamma;
  
  wire [1:0] a_gamma0_q;
  
  wire [1:0] a_gamma0_qq;
  
  wire [1:0] a_gamma1_gamma0;
  
  wire [1:0] a_gamma1_q;
  
  wire [1:0] a_gamma1_qq;
  
  output [3:0] a_gamma_inv;
  wire [3:0] a_gamma_inv;
  
  wire [1:0] a_gamma_ss_d;
  
  wire [1:0] a_gamma_ss_q;
  
  wire [1:0] a_omega;
  
  wire [1:0] a_omega_buf;
  
  wire [1:0] a_omega_buf_q;
  
  
  wire [1:0] _x5Caes_sbox_canright_pkg_aes_square_gf2p2_x24func_x24_x2Fhome_x2Fxyfv_x2FDesktop_x2Fresearch_topic_x2Fmasked_verify_x2Fcorrectness_verification_toolchain_x2Ftoolchain_build_x2Fsyn_out_x2Faes_sbox_dom_deloop_2025_12_15_00_07_33_x2Fgenerated_x2Faes_sbox_dom_deloop_x2Ev_x3A570_x2417261_x2E_x24result_x20;
  
  input [3:0] b_gamma;
  wire [3:0] b_gamma;
  
  wire [3:0] b_gamma0_omega_prd3;
  
  wire [1:0] b_gamma0_qq;
  
  wire [3:0] b_gamma10_prd2;
  
  wire [1:0] b_gamma1_gamma0;
  
  wire [3:0] b_gamma1_omega_prd3;
  
  wire [1:0] b_gamma1_qq;
  
  output [3:0] b_gamma_inv;
  wire [3:0] b_gamma_inv;
  
  wire [1:0] b_gamma_ss_d;
  
  wire [1:0] b_gamma_ss_q;
  
  wire [1:0] b_omega;
  
  wire [1:0] b_omega_buf;
  
  wire [1:0] b_omega_buf_q;
  
  input clk_i;
  wire clk_i;
  
  input [3:0] prd_2_i;
  wire [3:0] prd_2_i;
  
  output [7:0] prd_2_o;
  wire [7:0] prd_2_o;
  
  input [7:0] prd_3_i;
  wire [7:0] prd_3_i;
  
  output [7:0] prd_3_o;
  wire [7:0] prd_3_o;
  
  input rst_ni;
  wire rst_ni;
  
  input [1:0] we_i;
  wire [1:0] we_i;
  assign a_gamma_ss_d[1] = a_gamma[1] ^ a_gamma[3];
  assign _00_ = a_gamma[0] ^ a_gamma[2];
  assign a_gamma_ss_d[0] = _00_ ^ a_gamma_ss_d[1];
  assign _x5Caes_sbox_canright_pkg_aes_square_gf2p2_x24func_x24_x2Fhome_x2Fxyfv_x2FDesktop_x2Fresearch_topic_x2Fmasked_verify_x2Fcorrectness_verification_toolchain_x2Ftoolchain_build_x2Fsyn_out_x2Faes_sbox_dom_deloop_2025_12_15_00_07_33_x2Fgenerated_x2Faes_sbox_dom_deloop_x2Ev_x3A570_x2417261_x2E_x24result_x20[0] = b_gamma[1] ^ b_gamma[3];
  assign _01_ = b_gamma[0] ^ b_gamma[2];
  assign b_gamma_ss_d[0] = _01_ ^ _x5Caes_sbox_canright_pkg_aes_square_gf2p2_x24func_x24_x2Fhome_x2Fxyfv_x2FDesktop_x2Fresearch_topic_x2Fmasked_verify_x2Fcorrectness_verification_toolchain_x2Ftoolchain_build_x2Fsyn_out_x2Faes_sbox_dom_deloop_2025_12_15_00_07_33_x2Fgenerated_x2Faes_sbox_dom_deloop_x2Ev_x3A570_x2417261_x2E_x24result_x20[0];
  assign a_omega[1] = a_gamma_ss_q[0] ^ a_gamma1_gamma0[0];
  assign a_omega[0] = a_gamma_ss_q[1] ^ a_gamma1_gamma0[1];
  assign b_omega[1] = b_gamma_ss_q[0] ^ b_gamma1_gamma0[0];
  assign b_omega[0] = b_gamma_ss_q[1] ^ b_gamma1_gamma0[1];
  
  _x5C_x24paramod_x5Cprim_xilinx_flop_en_x5CWidth_x3Ds32_x2700000000000000000000000000001000_x5CResetValue_x3Ds1_x270_x20 _x5Cgen_prim_xilinx_flop_omega_gamma10_x2Eu_prim_xilinx_flop_ab_gamma10_q_x20 (
    .clk_i(clk_i),
    .d_i({ a_gamma1_q, a_gamma0_q, prd_2_o[7:6], prd_2_o[3:2] }),
    .en_i(we_i[1]),
    .q_o({ a_gamma1_qq, a_gamma0_qq, b_gamma1_qq, b_gamma0_qq }),
    .rst_ni(rst_ni)
  );
  
  _x5C_x24paramod_x5Cprim_xilinx_flop_en_x5CWidth_x3Ds32_x2700000000000000000000000000000100_x5CResetValue_x3Ds1_x270_x20 _x5Cgen_prim_xilinx_flop_omega_gamma10_x2Eu_prim_xilinx_flop_ab_omega_buf_x20 (
    .clk_i(clk_i),
    .d_i({ a_omega_buf, b_omega_buf }),
    .en_i(we_i[1]),
    .q_o({ a_omega_buf_q, b_omega_buf_q }),
    .rst_ni(rst_ni)
  );
  
  _x5C_x24paramod_x2424c1c4c69a656d6e1653f476009c3cda79470efb_x5Caes_dom_dep_mul_gf2pn_deloop_x20 u_aes_dom_mul_gamma1_gamma0 (
    .a_q(a_gamma1_gamma0),
    .a_x(a_gamma[3:2]),
    .a_x_q(a_gamma1_q),
    .a_y(a_gamma[1:0]),
    .a_y_q(a_gamma0_q),
    .b_q(b_gamma1_gamma0),
    .b_x(b_gamma[3:2]),
    .b_x_q(prd_2_o[7:6]),
    .b_y(b_gamma[1:0]),
    .b_y_q(prd_2_o[3:2]),
    .clk_i(clk_i),
    .prd_o(b_gamma10_prd2),
    .rst_ni(rst_ni),
    .we_i(we_i[0]),
    .z_0(prd_2_i[1:0]),
    .z_1(prd_2_i[3:2])
  );
  
  _x5C_x24paramod_x2424c1c4c69a656d6e1653f476009c3cda79470efb_x5Caes_dom_dep_mul_gf2pn_deloop_x20 u_aes_dom_mul_omega_gamma0 (
    .a_q(a_gamma_inv[3:2]),
    .a_x(a_omega_buf),
    .a_x_q(a_omega_buf_q),
    .a_y(a_gamma0_q),
    .a_y_q(a_gamma0_qq),
    .b_q(b_gamma_inv[3:2]),
    .b_x(b_omega_buf),
    .b_x_q(b_omega_buf_q),
    .b_y(prd_2_o[3:2]),
    .b_y_q(b_gamma0_qq),
    .clk_i(clk_i),
    .prd_o(b_gamma0_omega_prd3),
    .rst_ni(rst_ni),
    .we_i(we_i[1]),
    .z_0(prd_3_i[1:0]),
    .z_1(prd_3_i[3:2])
  );
  
  _x5C_x24paramod_x2424c1c4c69a656d6e1653f476009c3cda79470efb_x5Caes_dom_dep_mul_gf2pn_deloop_x20 u_aes_dom_mul_omega_gamma1 (
    .a_q(a_gamma_inv[1:0]),
    .a_x(a_gamma1_q),
    .a_x_q(a_gamma1_qq),
    .a_y(a_omega_buf),
    .a_y_q(a_omega_buf_q),
    .b_q(b_gamma_inv[1:0]),
    .b_x(prd_2_o[7:6]),
    .b_x_q(b_gamma1_qq),
    .b_y(b_omega_buf),
    .b_y_q(b_omega_buf_q),
    .clk_i(clk_i),
    .prd_o(b_gamma1_omega_prd3),
    .rst_ni(rst_ni),
    .we_i(we_i[1]),
    .z_0(prd_3_i[5:4]),
    .z_1(prd_3_i[7:6])
  );
  
  _x5C_x24paramod_x5Cprim_xilinx_buf_x5CWidth_x3Ds32_x2700000000000000000000000000000100_x20 u_prim_xilinx_buf_ab_omega (
    .in_i({ a_omega, b_omega }),
    .out_o({ a_omega_buf, b_omega_buf })
  );
  
  _x5C_x24paramod_x5Cprim_xilinx_flop_en_x5CWidth_x3Ds32_x2700000000000000000000000000001000_x5CResetValue_x3Ds1_x270_x20 u_prim_xilinx_flop_ab_gamma10 (
    .clk_i(clk_i),
    .d_i({ a_gamma, b_gamma }),
    .en_i(we_i[0]),
    .q_o({ a_gamma1_q, a_gamma0_q, prd_2_o[7:6], prd_2_o[3:2] }),
    .rst_ni(rst_ni)
  );
  
  _x5C_x24paramod_x5Cprim_xilinx_flop_en_x5CWidth_x3Ds32_x2700000000000000000000000000000100_x5CResetValue_x3Ds1_x270_x20 u_prim_xilinx_flop_ab_gamma_ss (
    .clk_i(clk_i),
    .d_i({ a_gamma_ss_d, _x5Caes_sbox_canright_pkg_aes_square_gf2p2_x24func_x24_x2Fhome_x2Fxyfv_x2FDesktop_x2Fresearch_topic_x2Fmasked_verify_x2Fcorrectness_verification_toolchain_x2Ftoolchain_build_x2Fsyn_out_x2Faes_sbox_dom_deloop_2025_12_15_00_07_33_x2Fgenerated_x2Faes_sbox_dom_deloop_x2Ev_x3A570_x2417261_x2E_x24result_x20[0], b_gamma_ss_d[0] }),
    .en_i(we_i[0]),
    .q_o({ a_gamma_ss_q, b_gamma_ss_q }),
    .rst_ni(rst_ni)
  );
  assign b_gamma_ss_d[1] = _x5Caes_sbox_canright_pkg_aes_square_gf2p2_x24func_x24_x2Fhome_x2Fxyfv_x2FDesktop_x2Fresearch_topic_x2Fmasked_verify_x2Fcorrectness_verification_toolchain_x2Ftoolchain_build_x2Fsyn_out_x2Faes_sbox_dom_deloop_2025_12_15_00_07_33_x2Fgenerated_x2Faes_sbox_dom_deloop_x2Ev_x3A570_x2417261_x2E_x24result_x20[0];
  assign { prd_2_o[5:4], prd_2_o[1:0] } = b_gamma10_prd2;
  assign prd_3_o = { b_gamma1_omega_prd3, b_gamma0_omega_prd3 };
endmodule



module _x5C_x24paramod_x5Caes_dom_inverse_gf2p8_deloop_x5CPipelineMul_x3D1_x271_x20(clk_i, rst_ni, we_i, a_y, b_y, prd_i, a_y_inv, b_y_inv, prd_o);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  
  wire [3:0] a_gamma;
  
  wire [3:0] a_gamma_buf;
  
  wire [3:0] a_theta;
  
  input [7:0] a_y;
  wire [7:0] a_y;
  
  wire [3:0] a_y0_q;
  
  wire [3:0] a_y0_qqq;
  
  wire [3:0] a_y1_q;
  
  wire [3:0] a_y1_qqq;
  
  wire [3:0] a_y1_y0;
  
  output [7:0] a_y_inv;
  wire [7:0] a_y_inv;
  
  wire [3:0] a_y_ss_d;
  
  wire [3:0] a_y_ss_q;
  
  wire [3:0] b_gamma;
  
  wire [3:0] b_gamma_buf;
  
  wire [3:0] b_theta;
  
  input [7:0] b_y;
  wire [7:0] b_y;
  
  wire [3:0] b_y0_q;
  
  wire [3:0] b_y0_qqq;
  
  
  wire [7:0] b_y10_prd1;
  
  wire [3:0] b_y1_q;
  
  wire [3:0] b_y1_qqq;
  
  wire [3:0] b_y1_y0;
  
  output [7:0] b_y_inv;
  wire [7:0] b_y_inv;
  
  wire [3:0] b_y_ss_d;
  
  wire [3:0] b_y_ss_q;
  
  input clk_i;
  wire clk_i;
  
  input [27:0] prd_i;
  wire [27:0] prd_i;
  
  output [19:0] prd_o;
  wire [19:0] prd_o;
  
  input rst_ni;
  wire rst_ni;
  
  input [3:0] we_i;
  wire [3:0] we_i;
  assign a_gamma[0] = a_y1_y0[0] ^ a_y_ss_q[0];
  assign a_gamma[1] = a_y1_y0[1] ^ a_y_ss_q[1];
  assign a_gamma[2] = a_y1_y0[2] ^ a_y_ss_q[2];
  assign a_gamma[3] = a_y1_y0[3] ^ a_y_ss_q[3];
  assign b_gamma[0] = b_y1_y0[0] ^ b_y_ss_q[0];
  assign b_gamma[1] = b_y1_y0[1] ^ b_y_ss_q[1];
  assign b_gamma[2] = b_y1_y0[2] ^ b_y_ss_q[2];
  assign b_gamma[3] = b_y1_y0[3] ^ b_y_ss_q[3];
  assign a_y_ss_d[0] = a_y[0] ^ a_y[4];
  assign _00_ = ~(a_y[0] ^ a_y[4]);
  assign _01_ = ~(a_y[2] ^ a_y[6]);
  assign a_y_ss_d[3] = _01_ ^ _00_;
  assign _02_ = ~(a_y[3] ^ a_y[7]);
  assign _03_ = ~(a_y[1] ^ a_y[5]);
  assign a_y_ss_d[2] = _03_ ^ _02_;
  assign a_y_ss_d[1] = _03_ ^ _00_;
  assign b_y_ss_d[0] = b_y[0] ^ b_y[4];
  assign _04_ = ~(b_y[0] ^ b_y[4]);
  assign _05_ = ~(b_y[2] ^ b_y[6]);
  assign b_y_ss_d[3] = _05_ ^ _04_;
  assign _06_ = ~(b_y[3] ^ b_y[7]);
  assign _07_ = ~(b_y[1] ^ b_y[5]);
  assign b_y_ss_d[2] = _07_ ^ _06_;
  assign b_y_ss_d[1] = _07_ ^ _04_;
  
  _x5C_x24paramod_x5Cprim_xilinx_flop_en_x5CWidth_x3Ds32_x2700000000000000000000000000010000_x5CResetValue_x3Ds1_x270_x20 _x5Cgen_prim_xilinx_flop_ab_y10_x2Eu_prim_xilinx_flop_ab_y10_x20 (
    .clk_i(clk_i),
    .d_i({ a_y, b_y }),
    .en_i(we_i[0]),
    .q_o({ a_y1_q, a_y0_q, b_y1_q, b_y0_q }),
    .rst_ni(rst_ni)
  );
  
  _x5C_x24paramod_x5Caes_dom_inverse_gf2p4_deloop_x5CPipelineMul_x3D1_x271_x20 u_aes_dom_inverse_gf2p4 (
    .a_gamma(a_gamma_buf),
    .a_gamma_inv(a_theta),
    .b_gamma(b_gamma_buf),
    .b_gamma_inv(b_theta),
    .clk_i(clk_i),
    .prd_2_i(prd_i[19:16]),
    .prd_2_o(prd_o[15:8]),
    .prd_3_i(prd_i[15:8]),
    .prd_3_o(prd_o[7:0]),
    .rst_ni(rst_ni),
    .we_i(we_i[2:1])
  );
  
  _x5C_x24paramod_x5Caes_dom_indep_mul_gf2pn_deloop_x5CNPower_x3Ds32_x2700000000000000000000000000000100_x5CPipeline_x3D1_x271_x20 u_aes_dom_mul_theta_y0 (
    .a_q(a_y_inv[7:4]),
    .a_x(a_theta),
    .a_y(a_y0_qqq),
    .b_q(b_y_inv[7:4]),
    .b_x(b_theta),
    .b_y(b_y0_qqq),
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .we_i(we_i[3]),
    .z_0(prd_i[3:0])
  );
  
  _x5C_x24paramod_x5Caes_dom_indep_mul_gf2pn_deloop_x5CNPower_x3Ds32_x2700000000000000000000000000000100_x5CPipeline_x3D1_x271_x20 u_aes_dom_mul_theta_y1 (
    .a_q(a_y_inv[3:0]),
    .a_x(a_y1_qqq),
    .a_y(a_theta),
    .b_q(b_y_inv[3:0]),
    .b_x(b_y1_qqq),
    .b_y(b_theta),
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .we_i(we_i[3]),
    .z_0(prd_i[7:4])
  );
  
  _x5C_x24paramod_x246042b1c7ace30ff79de13c5dcb11899d0e013023_x5Caes_dom_dep_mul_gf2pn_deloop_x20 u_aes_dom_mul_y1_y0 (
    .a_q(a_y1_y0),
    .a_x(a_y[7:4]),
    .a_x_q(a_y1_q),
    .a_y(a_y[3:0]),
    .a_y_q(a_y0_q),
    .b_q(b_y1_y0),
    .b_x(b_y[7:4]),
    .b_x_q(b_y1_q),
    .b_y(b_y[3:0]),
    .b_y_q(b_y0_q),
    .clk_i(clk_i),
    .prd_o(b_y10_prd1),
    .rst_ni(rst_ni),
    .we_i(we_i[0]),
    .z_0(prd_i[23:20]),
    .z_1(prd_i[27:24])
  );
  
  _x5C_x24paramod_x5Cprim_xilinx_buf_x5CWidth_x3Ds32_x2700000000000000000000000000001000_x20 u_prim_xilinx_buf_ab_gamma (
    .in_i({ a_gamma, b_gamma }),
    .out_o({ a_gamma_buf, b_gamma_buf })
  );
  
  _x5C_x24paramod_x5Cprim_xilinx_flop_en_x5CWidth_x3Ds32_x2700000000000000000000000000010000_x5CResetValue_x3Ds1_x270_x20 u_prim_xilinx_flop_ab_y10_qqq (
    .clk_i(clk_i),
    .d_i({ a_y, b_y }),
    .en_i(we_i[2]),
    .q_o({ a_y1_qqq, a_y0_qqq, b_y1_qqq, b_y0_qqq }),
    .rst_ni(rst_ni)
  );
  
  _x5C_x24paramod_x5Cprim_xilinx_flop_en_x5CWidth_x3Ds32_x2700000000000000000000000000001000_x5CResetValue_x3Ds1_x270_x20 u_prim_xilinx_flop_ab_y_ss (
    .clk_i(clk_i),
    .d_i({ a_y_ss_d, b_y_ss_d }),
    .en_i(we_i[0]),
    .q_o({ a_y_ss_q, b_y_ss_q }),
    .rst_ni(rst_ni)
  );
  assign prd_o[19:16] = b_y10_prd1[3:0];
endmodule





module _x5C_x24paramod_x5Cprim_xilinx_buf_x5CWidth_x3D32_x2700000000000000000000000000000100_x20(in_i, out_o);
  
  input [3:0] in_i;
  wire [3:0] in_i;
  
  output [3:0] out_o;
  wire [3:0] out_o;
  assign out_o = in_i;
endmodule





module _x5C_x24paramod_x5Cprim_xilinx_buf_x5CWidth_x3D32_x2700000000000000000000000000001000_x20(in_i, out_o);
  
  input [7:0] in_i;
  wire [7:0] in_i;
  
  output [7:0] out_o;
  wire [7:0] out_o;
  assign out_o = in_i;
endmodule





module _x5C_x24paramod_x5Cprim_xilinx_buf_x5CWidth_x3Ds32_x2700000000000000000000000000000100_x20(in_i, out_o);
  
  input [3:0] in_i;
  wire [3:0] in_i;
  
  output [3:0] out_o;
  wire [3:0] out_o;
  assign out_o = in_i;
endmodule





module _x5C_x24paramod_x5Cprim_xilinx_buf_x5CWidth_x3Ds32_x2700000000000000000000000000001000_x20(in_i, out_o);
  
  input [7:0] in_i;
  wire [7:0] in_i;
  
  output [7:0] out_o;
  wire [7:0] out_o;
  assign out_o = in_i;
endmodule





module _x5C_x24paramod_x5Cprim_xilinx_flop_x5CWidth_x3Ds32_x2700000000000000000000000000001000_x5CResetValue_x3Ds1_x270_x20(clk_i, rst_ni, d_i, q_o);
  
  input clk_i;
  wire clk_i;
  
  input [7:0] d_i;
  wire [7:0] d_i;
  
  output [7:0] q_o;
  reg [7:0] q_o;
  
  input rst_ni;
  wire rst_ni;
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[0] <= 1'h0;
    else q_o[0] <= d_i[0];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[1] <= 1'h0;
    else q_o[1] <= d_i[1];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[2] <= 1'h0;
    else q_o[2] <= d_i[2];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[3] <= 1'h0;
    else q_o[3] <= d_i[3];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[4] <= 1'h0;
    else q_o[4] <= d_i[4];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[5] <= 1'h0;
    else q_o[5] <= d_i[5];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[6] <= 1'h0;
    else q_o[6] <= d_i[6];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[7] <= 1'h0;
    else q_o[7] <= d_i[7];
endmodule





module _x5C_x24paramod_x5Cprim_xilinx_flop_en_x5CWidth_x3D32_x2700000000000000000000000000000100_x5CResetValue_x3Ds1_x270_x20(clk_i, rst_ni, en_i, d_i, q_o);
  
  input clk_i;
  wire clk_i;
  
  input [3:0] d_i;
  wire [3:0] d_i;
  
  input en_i;
  wire en_i;
  
  output [3:0] q_o;
  reg [3:0] q_o;
  
  input rst_ni;
  wire rst_ni;
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[0] <= 1'h0;
    else if (en_i) q_o[0] <= d_i[0];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[1] <= 1'h0;
    else if (en_i) q_o[1] <= d_i[1];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[2] <= 1'h0;
    else if (en_i) q_o[2] <= d_i[2];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[3] <= 1'h0;
    else if (en_i) q_o[3] <= d_i[3];
endmodule





module _x5C_x24paramod_x5Cprim_xilinx_flop_en_x5CWidth_x3D32_x2700000000000000000000000000001000_x5CResetValue_x3Ds1_x270_x20(clk_i, rst_ni, en_i, d_i, q_o);
  
  input clk_i;
  wire clk_i;
  
  input [7:0] d_i;
  wire [7:0] d_i;
  
  input en_i;
  wire en_i;
  
  output [7:0] q_o;
  reg [7:0] q_o;
  
  input rst_ni;
  wire rst_ni;
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[0] <= 1'h0;
    else if (en_i) q_o[0] <= d_i[0];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[1] <= 1'h0;
    else if (en_i) q_o[1] <= d_i[1];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[2] <= 1'h0;
    else if (en_i) q_o[2] <= d_i[2];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[3] <= 1'h0;
    else if (en_i) q_o[3] <= d_i[3];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[4] <= 1'h0;
    else if (en_i) q_o[4] <= d_i[4];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[5] <= 1'h0;
    else if (en_i) q_o[5] <= d_i[5];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[6] <= 1'h0;
    else if (en_i) q_o[6] <= d_i[6];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[7] <= 1'h0;
    else if (en_i) q_o[7] <= d_i[7];
endmodule





module _x5C_x24paramod_x5Cprim_xilinx_flop_en_x5CWidth_x3Ds32_x2700000000000000000000000000000100_x5CResetValue_x3Ds1_x270_x20(clk_i, rst_ni, en_i, d_i, q_o);
  
  input clk_i;
  wire clk_i;
  
  input [3:0] d_i;
  wire [3:0] d_i;
  
  input en_i;
  wire en_i;
  
  output [3:0] q_o;
  reg [3:0] q_o;
  
  input rst_ni;
  wire rst_ni;
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[0] <= 1'h0;
    else if (en_i) q_o[0] <= d_i[0];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[1] <= 1'h0;
    else if (en_i) q_o[1] <= d_i[1];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[2] <= 1'h0;
    else if (en_i) q_o[2] <= d_i[2];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[3] <= 1'h0;
    else if (en_i) q_o[3] <= d_i[3];
endmodule





module _x5C_x24paramod_x5Cprim_xilinx_flop_en_x5CWidth_x3Ds32_x2700000000000000000000000000001000_x5CResetValue_x3Ds1_x270_x20(clk_i, rst_ni, en_i, d_i, q_o);
  
  input clk_i;
  wire clk_i;
  
  input [7:0] d_i;
  wire [7:0] d_i;
  
  input en_i;
  wire en_i;
  
  output [7:0] q_o;
  reg [7:0] q_o;
  
  input rst_ni;
  wire rst_ni;
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[0] <= 1'h0;
    else if (en_i) q_o[0] <= d_i[0];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[1] <= 1'h0;
    else if (en_i) q_o[1] <= d_i[1];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[2] <= 1'h0;
    else if (en_i) q_o[2] <= d_i[2];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[3] <= 1'h0;
    else if (en_i) q_o[3] <= d_i[3];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[4] <= 1'h0;
    else if (en_i) q_o[4] <= d_i[4];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[5] <= 1'h0;
    else if (en_i) q_o[5] <= d_i[5];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[6] <= 1'h0;
    else if (en_i) q_o[6] <= d_i[6];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[7] <= 1'h0;
    else if (en_i) q_o[7] <= d_i[7];
endmodule





module _x5C_x24paramod_x5Cprim_xilinx_flop_en_x5CWidth_x3Ds32_x2700000000000000000000000000010000_x5CResetValue_x3Ds1_x270_x20(clk_i, rst_ni, en_i, d_i, q_o);
  
  input clk_i;
  wire clk_i;
  
  input [15:0] d_i;
  wire [15:0] d_i;
  
  input en_i;
  wire en_i;
  
  output [15:0] q_o;
  reg [15:0] q_o;
  
  input rst_ni;
  wire rst_ni;
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[0] <= 1'h0;
    else if (en_i) q_o[0] <= d_i[0];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[1] <= 1'h0;
    else if (en_i) q_o[1] <= d_i[1];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[2] <= 1'h0;
    else if (en_i) q_o[2] <= d_i[2];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[3] <= 1'h0;
    else if (en_i) q_o[3] <= d_i[3];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[4] <= 1'h0;
    else if (en_i) q_o[4] <= d_i[4];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[5] <= 1'h0;
    else if (en_i) q_o[5] <= d_i[5];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[6] <= 1'h0;
    else if (en_i) q_o[6] <= d_i[6];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[7] <= 1'h0;
    else if (en_i) q_o[7] <= d_i[7];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[8] <= 1'h0;
    else if (en_i) q_o[8] <= d_i[8];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[9] <= 1'h0;
    else if (en_i) q_o[9] <= d_i[9];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[10] <= 1'h0;
    else if (en_i) q_o[10] <= d_i[10];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[11] <= 1'h0;
    else if (en_i) q_o[11] <= d_i[11];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[12] <= 1'h0;
    else if (en_i) q_o[12] <= d_i[12];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[13] <= 1'h0;
    else if (en_i) q_o[13] <= d_i[13];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[14] <= 1'h0;
    else if (en_i) q_o[14] <= d_i[14];
  
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) q_o[15] <= 1'h0;
    else if (en_i) q_o[15] <= d_i[15];
endmodule



module aes_sbox_dom_deloop(clk_i, rst_ni, en_i, prd_we_i, out_req_o, out_ack_i, op_i, data_i, mask_i, prd_i, data_o, mask_o, prd_o);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  
  input clk_i;
  wire clk_i;
  
  reg [1:0] count_q;
  
  input [7:0] data_i;
  wire [7:0] data_i;
  
  output [7:0] data_o;
  wire [7:0] data_o;
  
  input en_i;
  wire en_i;
  
  wire [7:0] in_data_basis_x;
  
  wire [7:0] in_mask_basis_x;
  
  input [7:0] mask_i;
  wire [7:0] mask_i;
  
  output [7:0] mask_o;
  wire [7:0] mask_o;
  
  input [1:0] op_i;
  wire [1:0] op_i;
  
  input out_ack_i;
  wire out_ack_i;
  
  wire [7:0] out_data_basis_x;
  
  wire [7:0] out_mask_basis_x;
  
  wire [19:0] out_prd;
  
  output out_req_o;
  wire out_req_o;
  
  wire [7:0] prd1_d;
  
  wire [7:0] prd1_q;
  
  input [27:0] prd_i;
  wire [27:0] prd_i;
  
  output [19:0] prd_o;
  wire [19:0] prd_o;
  
  input prd_we_i;
  wire prd_we_i;
  
  input rst_ni;
  wire rst_ni;
  wire [1:0] we;
  assign _000_ = ~en_i;
  assign _170_ = ~data_i[0];
  assign _001_ = ~(data_i[3] ^ data_i[6]);
  assign _002_ = _001_ ^ data_i[2];
  assign _003_ = _002_ ^ data_i[1];
  assign _004_ = _003_ ^ _170_;
  assign _005_ = op_i[0] & ~(op_i[1]);
  assign _006_ = ~data_i[1];
  assign _007_ = ~(data_i[6] ^ data_i[5]);
  assign _008_ = _007_ ^ data_i[4];
  assign _009_ = _008_ ^ _006_;
  assign _010_ = _009_ ^ data_i[0];
  assign _011_ = op_i[1] & ~(op_i[0]);
  assign _012_ = _011_ ? _010_ : _004_;
  assign in_data_basis_x[0] = _005_ ? _004_ : _012_;
  assign _013_ = _007_ ^ _170_;
  assign _014_ = ~(data_i[4] ^ data_i[3]);
  assign _015_ = _014_ ^ data_i[0];
  assign _016_ = _011_ ? _015_ : _013_;
  assign in_data_basis_x[1] = _005_ ? _013_ : _016_;
  assign _017_ = ~(data_i[7] ^ data_i[5]);
  assign _018_ = _017_ ^ data_i[2];
  assign _019_ = _011_ ? _018_ : data_i[0];
  assign in_data_basis_x[2] = _005_ ? data_i[0] : _019_;
  assign _020_ = data_i[4] ^ data_i[7];
  assign _021_ = ~(_020_ ^ data_i[3]);
  assign _022_ = _021_ ^ data_i[1];
  assign _023_ = _022_ ^ _170_;
  assign _024_ = ~(data_i[7] ^ data_i[6]);
  assign _025_ = _024_ ^ data_i[4];
  assign _026_ = _011_ ? _025_ : _023_;
  assign in_data_basis_x[3] = _005_ ? _023_ : _026_;
  assign _027_ = _024_ ^ data_i[5];
  assign _028_ = _027_ ^ _170_;
  assign _029_ = data_i[3] ^ data_i[6];
  assign _030_ = _029_ ^ _006_;
  assign _031_ = _030_ ^ data_i[0];
  assign _032_ = _011_ ? _031_ : _028_;
  assign in_data_basis_x[4] = _005_ ? _028_ : _032_;
  assign _033_ = _007_ ^ data_i[1];
  assign _034_ = _033_ ^ _170_;
  assign _035_ = ~(data_i[4] ^ data_i[6]);
  assign _036_ = _011_ ? _035_ : _034_;
  assign in_data_basis_x[5] = _005_ ? _034_ : _036_;
  assign _037_ = _008_ ^ _170_;
  assign _038_ = _035_ ^ data_i[1];
  assign _039_ = _038_ ^ data_i[0];
  assign _040_ = _011_ ? _039_ : _037_;
  assign in_data_basis_x[6] = _005_ ? _037_ : _040_;
  assign _041_ = _027_ ^ data_i[2];
  assign _042_ = _041_ ^ data_i[1];
  assign _043_ = _042_ ^ _170_;
  assign _044_ = _011_ ? _020_ : _043_;
  assign in_data_basis_x[7] = _005_ ? _043_ : _044_;
  assign _045_ = ~mask_i[0];
  assign _046_ = ~(mask_i[3] ^ mask_i[6]);
  assign _047_ = _046_ ^ mask_i[2];
  assign _048_ = _047_ ^ mask_i[1];
  assign _049_ = _048_ ^ _045_;
  assign _050_ = ~(mask_i[5] ^ mask_i[6]);
  assign _051_ = _050_ ^ mask_i[4];
  assign _052_ = _051_ ^ mask_i[1];
  assign _053_ = _052_ ^ _045_;
  assign _054_ = _011_ ? _053_ : _049_;
  assign in_mask_basis_x[0] = _005_ ? _049_ : _054_;
  assign _055_ = _050_ ^ _045_;
  assign _056_ = ~(mask_i[4] ^ mask_i[3]);
  assign _057_ = _056_ ^ _045_;
  assign _058_ = _011_ ? _057_ : _055_;
  assign in_mask_basis_x[1] = _005_ ? _055_ : _058_;
  assign _059_ = mask_i[7] ^ mask_i[5];
  assign _060_ = _059_ ^ mask_i[2];
  assign _061_ = _011_ ? _060_ : mask_i[0];
  assign in_mask_basis_x[2] = _005_ ? mask_i[0] : _061_;
  assign _062_ = mask_i[4] ^ mask_i[7];
  assign _063_ = ~(_062_ ^ mask_i[3]);
  assign _064_ = _063_ ^ mask_i[1];
  assign _065_ = _064_ ^ _045_;
  assign _066_ = ~(mask_i[7] ^ mask_i[6]);
  assign _067_ = ~(_066_ ^ mask_i[4]);
  assign _068_ = _011_ ? _067_ : _065_;
  assign in_mask_basis_x[3] = _005_ ? _065_ : _068_;
  assign _069_ = _066_ ^ mask_i[5];
  assign _070_ = _069_ ^ _045_;
  assign _071_ = _046_ ^ mask_i[1];
  assign _072_ = _071_ ^ _045_;
  assign _073_ = _011_ ? _072_ : _070_;
  assign in_mask_basis_x[4] = _005_ ? _070_ : _073_;
  assign _074_ = _050_ ^ mask_i[1];
  assign _075_ = _074_ ^ _045_;
  assign _076_ = mask_i[4] ^ mask_i[6];
  assign _077_ = _011_ ? _076_ : _075_;
  assign in_mask_basis_x[5] = _005_ ? _075_ : _077_;
  assign _078_ = _051_ ^ _045_;
  assign _079_ = ~(_076_ ^ mask_i[1]);
  assign _080_ = _079_ ^ _045_;
  assign _081_ = _011_ ? _080_ : _078_;
  assign in_mask_basis_x[6] = _005_ ? _078_ : _081_;
  assign _082_ = _069_ ^ mask_i[2];
  assign _083_ = _082_ ^ mask_i[1];
  assign _084_ = _083_ ^ _045_;
  assign _085_ = _011_ ? _062_ : _084_;
  assign in_mask_basis_x[7] = _005_ ? _084_ : _085_;
  assign _086_ = ~(out_data_basis_x[4] ^ out_data_basis_x[6]);
  assign _087_ = _086_ ^ out_data_basis_x[1];
  assign _088_ = _011_ ? out_data_basis_x[2] : _087_;
  assign data_o[0] = _005_ ? _087_ : _088_;
  assign _089_ = ~(out_data_basis_x[5] ^ out_data_basis_x[4]);
  assign _090_ = _089_ ^ out_data_basis_x[1];
  assign _091_ = out_data_basis_x[5] ^ out_data_basis_x[1];
  assign _092_ = _011_ ? _091_ : _090_;
  assign data_o[1] = _005_ ? _090_ : _092_;
  assign _093_ = ~out_data_basis_x[0];
  assign _094_ = ~(out_data_basis_x[5] ^ out_data_basis_x[6]);
  assign _095_ = _094_ ^ out_data_basis_x[3];
  assign _096_ = _095_ ^ out_data_basis_x[2];
  assign _097_ = _096_ ^ _093_;
  assign _098_ = ~out_data_basis_x[1];
  assign _099_ = ~(out_data_basis_x[7] ^ out_data_basis_x[5]);
  assign _100_ = _099_ ^ out_data_basis_x[4];
  assign _101_ = _100_ ^ _098_;
  assign _102_ = _011_ ? _101_ : _097_;
  assign data_o[2] = _005_ ? _097_ : _102_;
  assign _103_ = ~out_data_basis_x[3];
  assign _104_ = ~(out_data_basis_x[7] ^ out_data_basis_x[6]);
  assign _105_ = _104_ ^ out_data_basis_x[5];
  assign _106_ = _105_ ^ out_data_basis_x[4];
  assign _107_ = _106_ ^ _103_;
  assign _108_ = _094_ ^ out_data_basis_x[4];
  assign _109_ = _108_ ^ out_data_basis_x[3];
  assign _110_ = _109_ ^ out_data_basis_x[2];
  assign _111_ = _110_ ^ _098_;
  assign _112_ = _011_ ? _111_ : _107_;
  assign data_o[3] = _005_ ? _107_ : _112_;
  assign _113_ = _099_ ^ _103_;
  assign _114_ = out_data_basis_x[1] ^ out_data_basis_x[6];
  assign _115_ = _011_ ? _114_ : _113_;
  assign data_o[4] = _005_ ? _113_ : _115_;
  assign _116_ = ~(out_data_basis_x[0] ^ out_data_basis_x[6]);
  assign _117_ = _105_ ^ out_data_basis_x[3];
  assign _118_ = _117_ ^ out_data_basis_x[2];
  assign _119_ = _118_ ^ _093_;
  assign _120_ = _011_ ? _119_ : _116_;
  assign data_o[5] = _005_ ? _116_ : _120_;
  assign _121_ = ~(out_data_basis_x[7] ^ out_data_basis_x[3]);
  assign _122_ = _117_ ^ out_data_basis_x[1];
  assign _123_ = _122_ ^ _093_;
  assign _124_ = _011_ ? _123_ : _121_;
  assign data_o[6] = _005_ ? _121_ : _124_;
  assign _125_ = out_data_basis_x[3] ^ out_data_basis_x[5];
  assign _126_ = out_data_basis_x[1] ^ out_data_basis_x[4];
  assign _127_ = _011_ ? _126_ : _125_;
  assign data_o[7] = _005_ ? _125_ : _127_;
  assign _128_ = ~out_mask_basis_x[1];
  assign _129_ = ~(out_mask_basis_x[4] ^ out_mask_basis_x[6]);
  assign _130_ = _129_ ^ _128_;
  assign _131_ = _011_ ? out_mask_basis_x[2] : _130_;
  assign mask_o[0] = _005_ ? _130_ : _131_;
  assign _132_ = ~(out_mask_basis_x[5] ^ out_mask_basis_x[4]);
  assign _133_ = _132_ ^ _128_;
  assign _134_ = out_mask_basis_x[5] ^ out_mask_basis_x[1];
  assign _135_ = _011_ ? _134_ : _133_;
  assign mask_o[1] = _005_ ? _133_ : _135_;
  assign _136_ = ~out_mask_basis_x[0];
  assign _137_ = ~(out_mask_basis_x[5] ^ out_mask_basis_x[6]);
  assign _138_ = _137_ ^ out_mask_basis_x[3];
  assign _139_ = _138_ ^ out_mask_basis_x[2];
  assign _140_ = _139_ ^ _136_;
  assign _141_ = ~(out_mask_basis_x[7] ^ out_mask_basis_x[5]);
  assign _142_ = _141_ ^ out_mask_basis_x[4];
  assign _143_ = _142_ ^ _128_;
  assign _144_ = _011_ ? _143_ : _140_;
  assign mask_o[2] = _005_ ? _140_ : _144_;
  assign _145_ = ~out_mask_basis_x[3];
  assign _146_ = ~(out_mask_basis_x[7] ^ out_mask_basis_x[6]);
  assign _147_ = _146_ ^ out_mask_basis_x[5];
  assign _148_ = _147_ ^ out_mask_basis_x[4];
  assign _149_ = _148_ ^ _145_;
  assign _150_ = _137_ ^ out_mask_basis_x[4];
  assign _151_ = _150_ ^ out_mask_basis_x[3];
  assign _152_ = _151_ ^ out_mask_basis_x[2];
  assign _153_ = _152_ ^ _128_;
  assign _154_ = _011_ ? _153_ : _149_;
  assign mask_o[3] = _005_ ? _149_ : _154_;
  assign _155_ = _141_ ^ _145_;
  assign _156_ = out_mask_basis_x[1] ^ out_mask_basis_x[6];
  assign _157_ = _011_ ? _156_ : _155_;
  assign mask_o[4] = _005_ ? _155_ : _157_;
  assign _158_ = out_mask_basis_x[0] ^ out_mask_basis_x[6];
  assign _159_ = _147_ ^ out_mask_basis_x[3];
  assign _160_ = _159_ ^ out_mask_basis_x[2];
  assign _161_ = _160_ ^ _136_;
  assign _162_ = _011_ ? _161_ : _158_;
  assign mask_o[5] = _005_ ? _158_ : _162_;
  assign _163_ = out_mask_basis_x[7] ^ out_mask_basis_x[3];
  assign _164_ = _159_ ^ out_mask_basis_x[1];
  assign _165_ = _164_ ^ _136_;
  assign _166_ = _011_ ? _165_ : _163_;
  assign mask_o[6] = _005_ ? _163_ : _166_;
  assign _167_ = out_mask_basis_x[3] ^ out_mask_basis_x[5];
  assign _168_ = out_mask_basis_x[1] ^ out_mask_basis_x[4];
  assign _169_ = _011_ ? _168_ : _167_;
  assign mask_o[7] = _005_ ? _167_ : _169_;
  assign prd1_d[0] = prd_we_i ? prd_i[0] : prd1_q[0];
  assign prd1_d[1] = prd_we_i ? prd_i[1] : prd1_q[1];
  assign prd1_d[2] = prd_we_i ? prd_i[2] : prd1_q[2];
  assign prd1_d[3] = prd_we_i ? prd_i[3] : prd1_q[3];
  assign prd1_d[4] = prd_we_i ? prd_i[4] : prd1_q[4];
  assign prd1_d[5] = prd_we_i ? prd_i[5] : prd1_q[5];
  assign prd1_d[6] = prd_we_i ? prd_i[6] : prd1_q[6];
  assign prd1_d[7] = prd_we_i ? prd_i[7] : prd1_q[7];
  assign we[0] = count_q[0] & en_i;
  assign we[1] = count_q[1] & en_i;
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) count_q[0] <= 1'h1;
    else count_q[0] <= _000_;
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) count_q[1] <= 1'h0;
    else count_q[1] <= en_i;
  
  _x5C_x24paramod_x5Caes_dom_inverse_gf2p8_deloop_x5CPipelineMul_x3D1_x271_x20 u_aes_dom_inverse_gf2p8 (
    .a_y(in_data_basis_x),
    .a_y_inv(out_data_basis_x),
    .b_y(in_mask_basis_x),
    .b_y_inv(out_mask_basis_x),
    .clk_i(clk_i),
    .prd_i({ prd1_q, prd_i[11:8], prd_i[19:12], prd_i[27:20] }),
    .prd_o(out_prd),
    .rst_ni(rst_ni),
    .we_i({ 2'h0, we })
  );
  
  _x5C_x24paramod_x5Cprim_xilinx_flop_x5CWidth_x3Ds32_x2700000000000000000000000000001000_x5CResetValue_x3Ds1_x270_x20 u_prim_xilinx_flop_prd1_q (
    .clk_i(clk_i),
    .d_i(prd1_d),
    .q_o(prd1_q),
    .rst_ni(rst_ni)
  );
  assign out_req_o = 1'h0;
  assign prd_o = { out_prd[7:0], out_prd[15:8], out_prd[19:16] };
endmodule
