/* Generated by Yosys 0.35+7 (git sha1 5691cd095, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

(* hdlname = "\\prim_xilinx_buf" *)
(* dynports =  1  *)
(* DONT_TOUCH = "yes" *)
(* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/prim_xilinx_buf.v:1.26-9.10" *)
module \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000010 (in_i, out_o);
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/prim_xilinx_buf.v:6.22-6.26" *)
  input [1:0] in_i;
  wire [1:0] in_i;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/prim_xilinx_buf.v:7.28-7.33" *)
  output [1:0] out_o;
  wire [1:0] out_o;
  assign out_o = in_i;
endmodule

(* hdlname = "\\prim_xilinx_buf" *)
(* dynports =  1  *)
(* DONT_TOUCH = "yes" *)
(* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/prim_xilinx_buf.v:1.26-9.10" *)
module \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000100 (in_i, out_o);
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/prim_xilinx_buf.v:6.22-6.26" *)
  input [3:0] in_i;
  wire [3:0] in_i;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/prim_xilinx_buf.v:7.28-7.33" *)
  output [3:0] out_o;
  wire [3:0] out_o;
  assign out_o = in_i;
endmodule

(* hdlname = "\\prim_xilinx_buf" *)
(* dynports =  1  *)
(* DONT_TOUCH = "yes" *)
(* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/prim_xilinx_buf.v:1.26-9.10" *)
module \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000110 (in_i, out_o);
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/prim_xilinx_buf.v:6.22-6.26" *)
  input [5:0] in_i;
  wire [5:0] in_i;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/prim_xilinx_buf.v:7.28-7.33" *)
  output [5:0] out_o;
  wire [5:0] out_o;
  assign out_o = in_i;
endmodule

(* hdlname = "\\prim_xilinx_buf" *)
(* dynports =  1  *)
(* DONT_TOUCH = "yes" *)
(* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/prim_xilinx_buf.v:1.26-9.10" *)
module \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000001000 (in_i, out_o);
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/prim_xilinx_buf.v:6.22-6.26" *)
  input [7:0] in_i;
  wire [7:0] in_i;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/prim_xilinx_buf.v:7.28-7.33" *)
  output [7:0] out_o;
  wire [7:0] out_o;
  assign out_o = in_i;
endmodule

(* hdlname = "\\prim_xilinx_buf" *)
(* dynports =  1  *)
(* DONT_TOUCH = "yes" *)
(* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/prim_xilinx_buf.v:1.26-9.10" *)
module \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000001100 (in_i, out_o);
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/prim_xilinx_buf.v:6.22-6.26" *)
  input [11:0] in_i;
  wire [11:0] in_i;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/prim_xilinx_buf.v:7.28-7.33" *)
  output [11:0] out_o;
  wire [11:0] out_o;
  assign out_o = in_i;
endmodule

(* hdlname = "\\prim_xilinx_buf" *)
(* dynports =  1  *)
(* DONT_TOUCH = "yes" *)
(* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/prim_xilinx_buf.v:1.26-9.10" *)
module \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000010000 (in_i, out_o);
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/prim_xilinx_buf.v:6.22-6.26" *)
  input [15:0] in_i;
  wire [15:0] in_i;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/prim_xilinx_buf.v:7.28-7.33" *)
  output [15:0] out_o;
  wire [15:0] out_o;
  assign out_o = in_i;
endmodule

(* hdlname = "\\prim_xilinx_xor2" *)
(* dynports =  1  *)
(* DONT_TOUCH = "yes" *)
(* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/prim_xilinx_xor2.v:1.26-11.10" *)
module \$paramod\prim_xilinx_xor2\Width=s32'00000000000000000000000000000010 (in0_i, in1_i, out_o);
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/prim_xilinx_xor2.v:7.22-7.27" *)
  input [1:0] in0_i;
  wire [1:0] in0_i;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/prim_xilinx_xor2.v:8.22-8.27" *)
  input [1:0] in1_i;
  wire [1:0] in1_i;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/prim_xilinx_xor2.v:9.28-9.33" *)
  output [1:0] out_o;
  wire [1:0] out_o;
  assign out_o[0] = in1_i[0] ^ in0_i[0];
  assign out_o[1] = in1_i[1] ^ in0_i[1];
endmodule

(* hdlname = "\\prim_xilinx_xor2" *)
(* dynports =  1  *)
(* DONT_TOUCH = "yes" *)
(* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/prim_xilinx_xor2.v:1.26-11.10" *)
module \$paramod\prim_xilinx_xor2\Width=s32'00000000000000000000000000000100 (in0_i, in1_i, out_o);
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/prim_xilinx_xor2.v:7.22-7.27" *)
  input [3:0] in0_i;
  wire [3:0] in0_i;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/prim_xilinx_xor2.v:8.22-8.27" *)
  input [3:0] in1_i;
  wire [3:0] in1_i;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/prim_xilinx_xor2.v:9.28-9.33" *)
  output [3:0] out_o;
  wire [3:0] out_o;
  assign out_o[0] = in1_i[0] ^ in0_i[0];
  assign out_o[1] = in1_i[1] ^ in0_i[1];
  assign out_o[2] = in1_i[2] ^ in0_i[2];
  assign out_o[3] = in1_i[3] ^ in0_i[3];
endmodule

(* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:1.1-178.10" *)
module aes_masked_inverse_gf2p4(b, q, r, m1, b_inv);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:0.0-0.0" *)
  (* unused_bits = "1" *)
  wire [1:0] \aes_sbox_canright_pkg_aes_square_gf2p2$func$/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:77$14304.$result ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:0.0-0.0" *)
  (* unused_bits = "1" *)
  wire [1:0] \aes_sbox_canright_pkg_aes_square_gf2p2$func$/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:78$14306.$result ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:8.19-8.20" *)
  input [3:0] b;
  wire [3:0] b;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:153.13-153.19" *)
  wire [1:0] \b0_inv[0] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:153.13-153.19" *)
  wire [1:0] \b0_inv[1] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:153.13-153.19" *)
  wire [1:0] \b0_inv[2] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:153.13-153.19" *)
  wire [1:0] \b0_inv[3] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:154.13-154.23" *)
  wire [1:0] \b0_inv_buf[0] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:154.13-154.23" *)
  wire [1:0] \b0_inv_buf[1] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:154.13-154.23" *)
  wire [1:0] \b0_inv_buf[2] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:154.13-154.23" *)
  wire [1:0] \b0_inv_buf[3] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:151.13-151.19" *)
  wire [1:0] \b1_inv[0] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:151.13-151.19" *)
  wire [1:0] \b1_inv[1] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:151.13-151.19" *)
  wire [1:0] \b1_inv[2] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:151.13-151.19" *)
  wire [1:0] \b1_inv[3] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:152.13-152.23" *)
  wire [1:0] \b1_inv_buf[0] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:152.13-152.23" *)
  wire [1:0] \b1_inv_buf[1] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:152.13-152.23" *)
  wire [1:0] \b1_inv_buf[2] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:152.13-152.23" *)
  wire [1:0] \b1_inv_buf[3] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:12.20-12.25" *)
  output [3:0] b_inv;
  wire [3:0] b_inv;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:113.13-113.19" *)
  wire [1:0] c1_inv;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:114.13-114.19" *)
  wire [1:0] c2_inv;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:91.13-91.14" *)
  wire [1:0] \c[0] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:91.13-91.14" *)
  wire [1:0] \c[1] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:91.13-91.14" *)
  wire [1:0] \c[2] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:91.13-91.14" *)
  wire [1:0] \c[3] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:91.13-91.14" *)
  wire [1:0] \c[4] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:91.13-91.14" *)
  wire [1:0] \c[5] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:92.13-92.18" *)
  wire [1:0] \c_buf[0] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:92.13-92.18" *)
  wire [1:0] \c_buf[1] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:92.13-92.18" *)
  wire [1:0] \c_buf[2] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:92.13-92.18" *)
  wire [1:0] \c_buf[3] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:92.13-92.18" *)
  wire [1:0] \c_buf[4] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:92.13-92.18" *)
  wire [1:0] \c_buf[5] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:11.19-11.21" *)
  input [3:0] m1;
  wire [3:0] m1;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:135.13-135.26" *)
  wire [1:0] mul_b0_c1_inv;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:143.13-143.30" *)
  wire [1:0] mul_b0_c1_inv_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:27.13-27.22" *)
  wire [1:0] mul_b0_q1;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:49.13-49.26" *)
  wire [1:0] mul_b0_q1_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:58.13-58.22" *)
  wire [1:0] mul_b1_b0;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:86.13-86.26" *)
  wire [1:0] mul_b1_b0_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:137.13-137.26" *)
  wire [1:0] mul_b1_c2_inv;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:145.13-145.30" *)
  wire [1:0] mul_b1_c2_inv_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:28.13-28.22" *)
  wire [1:0] mul_b1_q0;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:50.13-50.26" *)
  wire [1:0] mul_b1_q0_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:136.13-136.26" *)
  wire [1:0] mul_q0_c1_inv;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:144.13-144.30" *)
  wire [1:0] mul_q0_c1_inv_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:138.13-138.26" *)
  wire [1:0] mul_q1_c2_inv;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:146.13-146.30" *)
  wire [1:0] mul_q1_c2_inv_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:29.13-29.22" *)
  wire [1:0] mul_q1_q0;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:51.13-51.26" *)
  wire [1:0] mul_q1_q0_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:9.19-9.20" *)
  input [3:0] q;
  wire [3:0] q;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:10.19-10.20" *)
  input [1:0] r;
  wire [1:0] r;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:56.13-56.27" *)
  wire [1:0] scale_omega2_b;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:80.13-80.31" *)
  wire [1:0] scale_omega2_b_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:57.13-57.27" *)
  wire [1:0] scale_omega2_q;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:81.13-81.31" *)
  wire [1:0] scale_omega2_q_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:112.13-112.22" *)
  wire [1:0] xor_q0_q1;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:111.13-111.24" *)
  wire [1:0] xor_q1_r_sq;
  assign _000_ = q[3] & b[1];
  assign _001_ = b[1] ^ b[0];
  assign _002_ = q[3] ^ q[2];
  assign _003_ = _002_ & _001_;
  assign mul_b0_q1[1] = _003_ ^ _000_;
  assign _004_ = q[2] & b[0];
  assign mul_b0_q1[0] = _004_ ^ _003_;
  assign _005_ = q[1] & b[3];
  assign _006_ = b[3] ^ b[2];
  assign _007_ = ~(q[1] ^ q[0]);
  assign _008_ = _006_ & ~(_007_);
  assign mul_b1_q0[1] = _008_ ^ _005_;
  assign _009_ = q[0] & b[2];
  assign mul_b1_q0[0] = _009_ ^ _008_;
  assign _010_ = q[1] & q[3];
  assign _011_ = _002_ & ~(_007_);
  assign mul_q1_q0[1] = _011_ ^ _010_;
  assign _012_ = q[0] & q[2];
  assign mul_q1_q0[0] = _012_ ^ _011_;
  assign \aes_sbox_canright_pkg_aes_square_gf2p2$func$/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:77$14304.$result [0] = b[3] ^ b[1];
  assign _013_ = b[2] ^ b[0];
  assign scale_omega2_b[0] = _013_ ^ \aes_sbox_canright_pkg_aes_square_gf2p2$func$/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:77$14304.$result [0];
  assign \aes_sbox_canright_pkg_aes_square_gf2p2$func$/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:78$14306.$result [0] = q[1] ^ q[3];
  assign _014_ = q[0] ^ q[2];
  assign scale_omega2_q[0] = _014_ ^ \aes_sbox_canright_pkg_aes_square_gf2p2$func$/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:78$14306.$result [0];
  assign _015_ = b[3] & b[1];
  assign _016_ = _006_ & _001_;
  assign mul_b1_b0[1] = _016_ ^ _015_;
  assign _017_ = b[2] & b[0];
  assign mul_b1_b0[0] = _017_ ^ _016_;
  assign _018_ = c1_inv[1] & b[1];
  assign _019_ = ~(c1_inv[1] ^ c1_inv[0]);
  assign _020_ = _001_ & ~(_019_);
  assign mul_b0_c1_inv[1] = _020_ ^ _018_;
  assign _021_ = c1_inv[0] & b[0];
  assign mul_b0_c1_inv[0] = _021_ ^ _020_;
  assign _022_ = c1_inv[1] & q[1];
  assign _023_ = ~(_019_ | _007_);
  assign mul_q0_c1_inv[1] = _023_ ^ _022_;
  assign _024_ = c1_inv[0] & q[0];
  assign mul_q0_c1_inv[0] = _024_ ^ _023_;
  assign _025_ = c2_inv[1] & b[3];
  assign _026_ = ~(c2_inv[1] ^ c2_inv[0]);
  assign _027_ = _006_ & ~(_026_);
  assign mul_b1_c2_inv[1] = _027_ ^ _025_;
  assign _028_ = c2_inv[0] & b[2];
  assign mul_b1_c2_inv[0] = _028_ ^ _027_;
  assign _029_ = c2_inv[1] & q[3];
  assign _030_ = _002_ & ~(_026_);
  assign mul_q1_c2_inv[1] = _030_ ^ _029_;
  assign _031_ = c2_inv[0] & q[2];
  assign mul_q1_c2_inv[0] = _031_ ^ _030_;
  assign \c[0] [0] = scale_omega2_b_buf[0] ^ r[0];
  assign \c[0] [1] = scale_omega2_b_buf[1] ^ r[1];
  assign \c[1] [0] = scale_omega2_q_buf[0] ^ \c_buf[0] [0];
  assign \c[1] [1] = scale_omega2_q_buf[1] ^ \c_buf[0] [1];
  assign \c[2] [0] = mul_b1_b0_buf[0] ^ \c_buf[1] [0];
  assign \c[2] [1] = mul_b1_b0_buf[1] ^ \c_buf[1] [1];
  assign \c[3] [0] = mul_b1_q0_buf[0] ^ \c_buf[2] [0];
  assign \c[3] [1] = mul_b1_q0_buf[1] ^ \c_buf[2] [1];
  assign \c[4] [0] = mul_b0_q1_buf[0] ^ \c_buf[3] [0];
  assign \c[4] [1] = mul_b0_q1_buf[1] ^ \c_buf[3] [1];
  assign \c[5] [0] = mul_q1_q0_buf[0] ^ \c_buf[4] [0];
  assign \c[5] [1] = mul_q1_q0_buf[1] ^ \c_buf[4] [1];
  assign \b1_inv[0] [0] = mul_b0_c1_inv_buf[0] ^ m1[2];
  assign \b1_inv[0] [1] = mul_b0_c1_inv_buf[1] ^ m1[3];
  assign \b1_inv[1] [0] = \b1_inv_buf[0] [0] ^ mul_b0_q1_buf[0];
  assign \b1_inv[1] [1] = \b1_inv_buf[0] [1] ^ mul_b0_q1_buf[1];
  assign \b1_inv[2] [0] = mul_q0_c1_inv_buf[0] ^ \b1_inv_buf[1] [0];
  assign \b1_inv[2] [1] = mul_q0_c1_inv_buf[1] ^ \b1_inv_buf[1] [1];
  assign \b1_inv[3] [0] = \b1_inv_buf[2] [0] ^ mul_q1_q0_buf[0];
  assign \b1_inv[3] [1] = \b1_inv_buf[2] [1] ^ mul_q1_q0_buf[1];
  assign \b0_inv[0] [0] = mul_b1_c2_inv_buf[0] ^ m1[0];
  assign \b0_inv[0] [1] = mul_b1_c2_inv_buf[1] ^ m1[1];
  assign \b0_inv[1] [0] = \b0_inv_buf[0] [0] ^ mul_b1_q0_buf[0];
  assign \b0_inv[1] [1] = \b0_inv_buf[0] [1] ^ mul_b1_q0_buf[1];
  assign \b0_inv[2] [0] = mul_q1_c2_inv_buf[0] ^ \b0_inv_buf[1] [0];
  assign \b0_inv[2] [1] = mul_q1_c2_inv_buf[1] ^ \b0_inv_buf[1] [1];
  assign \b0_inv[3] [0] = \b0_inv_buf[2] [0] ^ mul_q1_q0_buf[0];
  assign \b0_inv[3] [1] = \b0_inv_buf[2] [1] ^ mul_q1_q0_buf[1];
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:171.33-174.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000010  \gen_a01_inv_buf[0].u_prim_xilinx_buf_b0_inv_i  (
    .in_i(\b0_inv[0] ),
    .out_o(\b0_inv_buf[0] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:167.33-170.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000010  \gen_a01_inv_buf[0].u_prim_xilinx_buf_b1_inv_i  (
    .in_i(\b1_inv[0] ),
    .out_o(\b1_inv_buf[0] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:171.33-174.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000010  \gen_a01_inv_buf[1].u_prim_xilinx_buf_b0_inv_i  (
    .in_i(\b0_inv[1] ),
    .out_o(\b0_inv_buf[1] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:167.33-170.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000010  \gen_a01_inv_buf[1].u_prim_xilinx_buf_b1_inv_i  (
    .in_i(\b1_inv[1] ),
    .out_o(\b1_inv_buf[1] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:171.33-174.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000010  \gen_a01_inv_buf[2].u_prim_xilinx_buf_b0_inv_i  (
    .in_i(\b0_inv[2] ),
    .out_o(\b0_inv_buf[2] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:167.33-170.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000010  \gen_a01_inv_buf[2].u_prim_xilinx_buf_b1_inv_i  (
    .in_i(\b1_inv[2] ),
    .out_o(\b1_inv_buf[2] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:171.33-174.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000010  \gen_a01_inv_buf[3].u_prim_xilinx_buf_b0_inv_i  (
    .in_i(\b0_inv[3] ),
    .out_o(\b0_inv_buf[3] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:167.33-170.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000010  \gen_a01_inv_buf[3].u_prim_xilinx_buf_b1_inv_i  (
    .in_i(\b1_inv[3] ),
    .out_o(\b1_inv_buf[3] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:103.33-106.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000010  \gen_c_buf[0].u_prim_xilinx_buf_c_i  (
    .in_i(\c[0] ),
    .out_o(\c_buf[0] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:103.33-106.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000010  \gen_c_buf[1].u_prim_xilinx_buf_c_i  (
    .in_i(\c[1] ),
    .out_o(\c_buf[1] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:103.33-106.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000010  \gen_c_buf[2].u_prim_xilinx_buf_c_i  (
    .in_i(\c[2] ),
    .out_o(\c_buf[2] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:103.33-106.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000010  \gen_c_buf[3].u_prim_xilinx_buf_c_i  (
    .in_i(\c[3] ),
    .out_o(\c_buf[3] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:103.33-106.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000010  \gen_c_buf[4].u_prim_xilinx_buf_c_i  (
    .in_i(\c[4] ),
    .out_o(\c_buf[4] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:103.33-106.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000010  \gen_c_buf[5].u_prim_xilinx_buf_c_i  (
    .in_i(\c[5] ),
    .out_o(\c_buf[5] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:125.32-129.3" *)
  \$paramod\prim_xilinx_xor2\Width=s32'00000000000000000000000000000010  u_prim_c1_inv (
    .in0_i(xor_q1_r_sq),
    .in1_i({ \c_buf[5] [0], \c_buf[5] [1] }),
    .out_o(c1_inv)
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:130.32-134.3" *)
  \$paramod\prim_xilinx_xor2\Width=s32'00000000000000000000000000000010  u_prim_c2_inv (
    .in0_i(c1_inv),
    .in1_i(xor_q0_q1),
    .out_o(c2_inv)
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:87.31-90.3" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000010  u_prim_xilinx_buf_mul_b1_b0 (
    .in_i(mul_b1_b0),
    .out_o(mul_b1_b0_buf)
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:52.31-55.3" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000110  u_prim_xilinx_buf_mul_bq01 (
    .in_i({ mul_b0_q1, mul_b1_q0, mul_q1_q0 }),
    .out_o({ mul_b0_q1_buf, mul_b1_q0_buf, mul_q1_q0_buf })
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:147.31-150.3" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000001000  u_prim_xilinx_buf_mul_bq01_c12_inv (
    .in_i({ mul_b0_c1_inv, mul_q0_c1_inv, mul_b1_c2_inv, mul_q1_c2_inv }),
    .out_o({ mul_b0_c1_inv_buf, mul_q0_c1_inv_buf, mul_b1_c2_inv_buf, mul_q1_c2_inv_buf })
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:82.31-85.3" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000100  u_prim_xilinx_buf_scale_omega2_bq (
    .in_i({ \aes_sbox_canright_pkg_aes_square_gf2p2$func$/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:77$14304.$result [0], scale_omega2_b[0], \aes_sbox_canright_pkg_aes_square_gf2p2$func$/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:78$14306.$result [0], scale_omega2_q[0] }),
    .out_o({ scale_omega2_b_buf, scale_omega2_q_buf })
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:120.32-124.3" *)
  \$paramod\prim_xilinx_xor2\Width=s32'00000000000000000000000000000010  u_prim_xor_q0_q1 (
    .in0_i(q[1:0]),
    .in1_i(q[3:2]),
    .out_o(xor_q0_q1)
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:115.32-119.3" *)
  \$paramod\prim_xilinx_xor2\Width=s32'00000000000000000000000000000010  u_prim_xor_q1_r_sq (
    .in0_i(q[3:2]),
    .in1_i({ r[0], r[1] }),
    .out_o(xor_q1_r_sq)
  );
  assign b_inv = { \b1_inv_buf[3] , \b0_inv_buf[3]  };
  assign scale_omega2_b[1] = \aes_sbox_canright_pkg_aes_square_gf2p2$func$/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:77$14304.$result [0];
  assign scale_omega2_q[1] = \aes_sbox_canright_pkg_aes_square_gf2p2$func$/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:78$14306.$result [0];
endmodule

(* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:179.1-387.10" *)
module aes_masked_inverse_gf2p8(a, m, n, a_inv);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:185.19-185.20" *)
  input [7:0] a;
  wire [7:0] a;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:362.13-362.19" *)
  wire [3:0] \a0_inv[0] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:362.13-362.19" *)
  wire [3:0] \a0_inv[1] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:362.13-362.19" *)
  wire [3:0] \a0_inv[2] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:362.13-362.19" *)
  wire [3:0] \a0_inv[3] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:363.13-363.23" *)
  wire [3:0] \a0_inv_buf[0] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:363.13-363.23" *)
  wire [3:0] \a0_inv_buf[1] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:363.13-363.23" *)
  wire [3:0] \a0_inv_buf[2] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:363.13-363.23" *)
  wire [3:0] \a0_inv_buf[3] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:360.13-360.19" *)
  wire [3:0] \a1_inv[0] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:360.13-360.19" *)
  wire [3:0] \a1_inv[1] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:360.13-360.19" *)
  wire [3:0] \a1_inv[2] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:360.13-360.19" *)
  wire [3:0] \a1_inv[3] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:361.13-361.23" *)
  wire [3:0] \a1_inv_buf[0] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:361.13-361.23" *)
  wire [3:0] \a1_inv_buf[1] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:361.13-361.23" *)
  wire [3:0] \a1_inv_buf[2] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:361.13-361.23" *)
  wire [3:0] \a1_inv_buf[3] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:188.20-188.25" *)
  output [7:0] a_inv;
  wire [7:0] a_inv;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:333.13-333.19" *)
  wire [3:0] b2_inv;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:302.13-302.14" *)
  wire [3:0] \b[0] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:302.13-302.14" *)
  wire [3:0] \b[1] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:302.13-302.14" *)
  wire [3:0] \b[2] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:302.13-302.14" *)
  wire [3:0] \b[3] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:302.13-302.14" *)
  wire [3:0] \b[4] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:302.13-302.14" *)
  wire [3:0] \b[5] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:303.13-303.18" *)
  wire [3:0] \b_buf[0] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:303.13-303.18" *)
  wire [3:0] \b_buf[1] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:303.13-303.18" *)
  wire [3:0] \b_buf[2] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:303.13-303.18" *)
  wire [3:0] \b_buf[3] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:303.13-303.18" *)
  wire [3:0] \b_buf[4] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:303.13-303.18" *)
  wire [3:0] \b_buf[5] ;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:194.13-194.18" *)
  wire [3:0] b_inv;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:327.13-327.22" *)
  wire [3:0] b_inv_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:186.19-186.20" *)
  input [7:0] m;
  wire [7:0] m;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:344.13-344.25" *)
  wire [3:0] mul_a0_b_inv;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:352.13-352.29" *)
  wire [3:0] mul_a0_b_inv_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:206.13-206.22" *)
  wire [3:0] mul_a0_m1;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:253.13-253.26" *)
  wire [3:0] mul_a0_m1_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:295.13-295.22" *)
  wire [3:0] mul_a1_a0;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:297.13-297.26" *)
  wire [3:0] mul_a1_a0_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:346.13-346.26" *)
  wire [3:0] mul_a1_b2_inv;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:354.13-354.30" *)
  wire [3:0] mul_a1_b2_inv_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:207.13-207.22" *)
  wire [3:0] mul_a1_m0;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:254.13-254.26" *)
  wire [3:0] mul_a1_m0_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:345.13-345.25" *)
  wire [3:0] mul_m0_b_inv;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:353.13-353.29" *)
  wire [3:0] mul_m0_b_inv_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:208.13-208.22" *)
  wire [3:0] mul_m0_m1;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:255.13-255.26" *)
  wire [3:0] mul_m0_m1_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:347.13-347.26" *)
  wire [3:0] mul_m1_b2_inv;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:355.13-355.30" *)
  wire [3:0] mul_m1_b2_inv_buf;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:187.19-187.20" *)
  input [7:0] n;
  wire [7:0] n;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:332.13-332.22" *)
  wire [3:0] xor_m1_m0;
  assign _000_ = m[6] & a[2];
  assign _001_ = ~(a[3] ^ a[2]);
  assign _002_ = ~(m[7] ^ m[6]);
  assign _003_ = _002_ | _001_;
  assign _004_ = _003_ ^ _000_;
  assign _005_ = ~(a[1] ^ a[3]);
  assign _006_ = m[5] ^ m[7];
  assign _007_ = _006_ & ~(_005_);
  assign _008_ = a[0] ^ a[2];
  assign _009_ = _008_ ^ _005_;
  assign _010_ = ~(m[4] ^ m[6]);
  assign _011_ = _010_ ^ _006_;
  assign _012_ = _011_ | _009_;
  assign _013_ = ~(_012_ ^ _007_);
  assign _014_ = _008_ & ~(_010_);
  assign _015_ = _014_ ^ _012_;
  assign _016_ = _015_ ^ _013_;
  assign mul_a0_m1[2] = _016_ ^ _004_;
  assign _017_ = m[7] & a[3];
  assign _018_ = _017_ ^ _003_;
  assign mul_a0_m1[3] = _018_ ^ _015_;
  assign _019_ = m[4] & a[0];
  assign _020_ = ~(a[1] ^ a[0]);
  assign _021_ = ~(m[5] ^ m[4]);
  assign _022_ = _021_ | _020_;
  assign _023_ = _022_ ^ _019_;
  assign mul_a0_m1[0] = _023_ ^ _016_;
  assign _024_ = m[5] & a[1];
  assign _025_ = _024_ ^ _022_;
  assign mul_a0_m1[1] = _025_ ^ _015_;
  assign _026_ = m[2] & a[6];
  assign _027_ = ~(a[7] ^ a[6]);
  assign _028_ = ~(m[3] ^ m[2]);
  assign _029_ = _028_ | _027_;
  assign _030_ = _029_ ^ _026_;
  assign _031_ = ~(a[5] ^ a[7]);
  assign _032_ = ~(m[1] ^ m[3]);
  assign _033_ = _032_ | _031_;
  assign _034_ = a[4] ^ a[6];
  assign _035_ = _034_ ^ _031_;
  assign _036_ = m[1] ^ m[3];
  assign _037_ = ~(m[0] ^ m[2]);
  assign _038_ = _037_ ^ _036_;
  assign _039_ = _038_ | _035_;
  assign _040_ = _039_ ^ _033_;
  assign _041_ = _034_ & ~(_037_);
  assign _042_ = _041_ ^ _039_;
  assign _043_ = _042_ ^ _040_;
  assign mul_a1_m0[2] = _043_ ^ _030_;
  assign _044_ = m[3] & a[7];
  assign _045_ = _044_ ^ _029_;
  assign mul_a1_m0[3] = _045_ ^ _042_;
  assign _046_ = m[0] & a[4];
  assign _047_ = ~(a[5] ^ a[4]);
  assign _048_ = ~(m[1] ^ m[0]);
  assign _049_ = _048_ | _047_;
  assign _050_ = _049_ ^ _046_;
  assign mul_a1_m0[0] = _050_ ^ _043_;
  assign _051_ = m[1] & a[5];
  assign _052_ = _051_ ^ _049_;
  assign mul_a1_m0[1] = _052_ ^ _042_;
  assign _053_ = m[2] & m[6];
  assign _054_ = _028_ | _002_;
  assign _055_ = _054_ ^ _053_;
  assign _056_ = ~(_036_ & _006_);
  assign _057_ = _038_ | _011_;
  assign _058_ = _057_ ^ _056_;
  assign _059_ = m[4] ^ m[6];
  assign _060_ = _059_ & ~(_037_);
  assign _061_ = _060_ ^ _057_;
  assign _062_ = _061_ ^ _058_;
  assign mul_m0_m1[2] = _062_ ^ _055_;
  assign _063_ = m[3] & m[7];
  assign _064_ = _063_ ^ _054_;
  assign mul_m0_m1[3] = _064_ ^ _061_;
  assign _065_ = m[0] & m[4];
  assign _066_ = _048_ | _021_;
  assign _067_ = _066_ ^ _065_;
  assign mul_m0_m1[0] = _067_ ^ _062_;
  assign _068_ = m[1] & m[5];
  assign _069_ = _068_ ^ _066_;
  assign mul_m0_m1[1] = _069_ ^ _061_;
  assign _070_ = a[6] & a[2];
  assign _071_ = _027_ | _001_;
  assign _072_ = _071_ ^ _070_;
  assign _073_ = _031_ | _005_;
  assign _074_ = _035_ | _009_;
  assign _075_ = _074_ ^ _073_;
  assign _076_ = _034_ & _008_;
  assign _077_ = _076_ ^ _074_;
  assign _078_ = _077_ ^ _075_;
  assign mul_a1_a0[2] = _078_ ^ _072_;
  assign _079_ = a[7] & a[3];
  assign _080_ = _079_ ^ _071_;
  assign mul_a1_a0[3] = _080_ ^ _077_;
  assign _081_ = a[4] & a[0];
  assign _082_ = _047_ | _020_;
  assign _083_ = _082_ ^ _081_;
  assign mul_a1_a0[0] = _083_ ^ _078_;
  assign _084_ = a[5] & a[1];
  assign _085_ = _084_ ^ _082_;
  assign mul_a1_a0[1] = _085_ ^ _077_;
  assign _086_ = b_inv_buf[2] & a[2];
  assign _087_ = ~(b_inv_buf[3] ^ b_inv_buf[2]);
  assign _088_ = _087_ | _001_;
  assign _089_ = _088_ ^ _086_;
  assign _090_ = ~(b_inv_buf[1] ^ b_inv_buf[3]);
  assign _091_ = _090_ | _005_;
  assign _092_ = ~(b_inv_buf[0] ^ b_inv_buf[2]);
  assign _093_ = ~(_092_ ^ _090_);
  assign _094_ = _093_ | _009_;
  assign _095_ = _094_ ^ _091_;
  assign _096_ = _008_ & ~(_092_);
  assign _097_ = _096_ ^ _094_;
  assign _098_ = _097_ ^ _095_;
  assign mul_a0_b_inv[2] = _098_ ^ _089_;
  assign _099_ = b_inv_buf[3] & a[3];
  assign _100_ = _099_ ^ _088_;
  assign mul_a0_b_inv[3] = _100_ ^ _097_;
  assign _101_ = b_inv_buf[0] & a[0];
  assign _102_ = ~(b_inv_buf[1] ^ b_inv_buf[0]);
  assign _103_ = _102_ | _020_;
  assign _104_ = _103_ ^ _101_;
  assign mul_a0_b_inv[0] = _104_ ^ _098_;
  assign _105_ = b_inv_buf[1] & a[1];
  assign _106_ = _105_ ^ _103_;
  assign mul_a0_b_inv[1] = _106_ ^ _097_;
  assign _107_ = b_inv_buf[2] & m[2];
  assign _108_ = _087_ | _028_;
  assign _109_ = _108_ ^ _107_;
  assign _110_ = _090_ | _032_;
  assign _111_ = _093_ | _038_;
  assign _112_ = _111_ ^ _110_;
  assign _113_ = ~(_092_ | _037_);
  assign _114_ = _113_ ^ _111_;
  assign _115_ = _114_ ^ _112_;
  assign mul_m0_b_inv[2] = _115_ ^ _109_;
  assign _116_ = b_inv_buf[3] & m[3];
  assign _117_ = _116_ ^ _108_;
  assign mul_m0_b_inv[3] = _117_ ^ _114_;
  assign _118_ = b_inv_buf[0] & m[0];
  assign _119_ = _102_ | _048_;
  assign _120_ = _119_ ^ _118_;
  assign mul_m0_b_inv[0] = _120_ ^ _115_;
  assign _121_ = b_inv_buf[1] & m[1];
  assign _122_ = _121_ ^ _119_;
  assign mul_m0_b_inv[1] = _122_ ^ _114_;
  assign _123_ = b2_inv[2] & a[6];
  assign _124_ = ~(b2_inv[3] ^ b2_inv[2]);
  assign _125_ = _124_ | _027_;
  assign _126_ = _125_ ^ _123_;
  assign _127_ = ~(b2_inv[1] ^ b2_inv[3]);
  assign _128_ = _127_ | _031_;
  assign _129_ = ~(b2_inv[0] ^ b2_inv[2]);
  assign _130_ = ~(_129_ ^ _127_);
  assign _131_ = _130_ | _035_;
  assign _132_ = _131_ ^ _128_;
  assign _133_ = _034_ & ~(_129_);
  assign _134_ = _133_ ^ _131_;
  assign _135_ = _134_ ^ _132_;
  assign mul_a1_b2_inv[2] = _135_ ^ _126_;
  assign _136_ = b2_inv[3] & a[7];
  assign _137_ = _136_ ^ _125_;
  assign mul_a1_b2_inv[3] = _137_ ^ _134_;
  assign _138_ = b2_inv[0] & a[4];
  assign _139_ = ~(b2_inv[1] ^ b2_inv[0]);
  assign _140_ = _139_ | _047_;
  assign _141_ = _140_ ^ _138_;
  assign mul_a1_b2_inv[0] = _141_ ^ _135_;
  assign _142_ = b2_inv[1] & a[5];
  assign _143_ = _142_ ^ _140_;
  assign mul_a1_b2_inv[1] = _143_ ^ _134_;
  assign _144_ = b2_inv[2] & m[6];
  assign _145_ = _124_ | _002_;
  assign _146_ = _145_ ^ _144_;
  assign _147_ = _127_ | ~(_006_);
  assign _148_ = _130_ | _011_;
  assign _149_ = _148_ ^ _147_;
  assign _150_ = _059_ & ~(_129_);
  assign _151_ = _150_ ^ _148_;
  assign _152_ = _151_ ^ _149_;
  assign mul_m1_b2_inv[2] = _152_ ^ _146_;
  assign _153_ = b2_inv[3] & m[7];
  assign _154_ = _153_ ^ _145_;
  assign mul_m1_b2_inv[3] = _154_ ^ _151_;
  assign _155_ = b2_inv[0] & m[4];
  assign _156_ = _139_ | _021_;
  assign _157_ = _156_ ^ _155_;
  assign mul_m1_b2_inv[0] = _157_ ^ _152_;
  assign _158_ = b2_inv[1] & m[5];
  assign _159_ = _158_ ^ _156_;
  assign mul_m1_b2_inv[1] = _159_ ^ _151_;
  assign _160_ = a[4] ^ a[0];
  assign \b[0] [0] = _160_ ^ n[4];
  assign _161_ = a[5] ^ a[1];
  assign _162_ = _161_ ^ _160_;
  assign \b[0] [1] = _162_ ^ n[5];
  assign _163_ = ~(a[7] ^ a[3]);
  assign _164_ = ~(_163_ ^ _161_);
  assign \b[0] [2] = _164_ ^ n[6];
  assign _165_ = ~(a[6] ^ a[2]);
  assign _166_ = ~(_165_ ^ _160_);
  assign \b[0] [3] = _166_ ^ n[7];
  assign _167_ = m[0] ^ m[4];
  assign \b[1] [0] = _167_ ^ \b_buf[0] [0];
  assign _168_ = m[1] ^ m[5];
  assign _169_ = _168_ ^ _167_;
  assign \b[1] [1] = _169_ ^ \b_buf[0] [1];
  assign _170_ = ~(m[3] ^ m[7]);
  assign _171_ = ~(_170_ ^ _168_);
  assign \b[1] [2] = _171_ ^ \b_buf[0] [2];
  assign _172_ = ~(m[2] ^ m[6]);
  assign _173_ = ~(_172_ ^ _167_);
  assign \b[1] [3] = _173_ ^ \b_buf[0] [3];
  assign \b[2] [0] = mul_a1_a0_buf[0] ^ \b_buf[1] [0];
  assign \b[2] [1] = mul_a1_a0_buf[1] ^ \b_buf[1] [1];
  assign \b[2] [2] = mul_a1_a0_buf[2] ^ \b_buf[1] [2];
  assign \b[2] [3] = mul_a1_a0_buf[3] ^ \b_buf[1] [3];
  assign \b[3] [0] = mul_a1_m0_buf[0] ^ \b_buf[2] [0];
  assign \b[3] [1] = mul_a1_m0_buf[1] ^ \b_buf[2] [1];
  assign \b[3] [2] = mul_a1_m0_buf[2] ^ \b_buf[2] [2];
  assign \b[3] [3] = mul_a1_m0_buf[3] ^ \b_buf[2] [3];
  assign \b[4] [0] = mul_a0_m1_buf[0] ^ \b_buf[3] [0];
  assign \b[4] [1] = mul_a0_m1_buf[1] ^ \b_buf[3] [1];
  assign \b[4] [2] = mul_a0_m1_buf[2] ^ \b_buf[3] [2];
  assign \b[4] [3] = mul_a0_m1_buf[3] ^ \b_buf[3] [3];
  assign \b[5] [0] = mul_m0_m1_buf[0] ^ \b_buf[4] [0];
  assign \b[5] [1] = mul_m0_m1_buf[1] ^ \b_buf[4] [1];
  assign \b[5] [2] = mul_m0_m1_buf[2] ^ \b_buf[4] [2];
  assign \b[5] [3] = mul_m0_m1_buf[3] ^ \b_buf[4] [3];
  assign \a1_inv[0] [0] = mul_a0_b_inv_buf[0] ^ n[4];
  assign \a1_inv[0] [1] = mul_a0_b_inv_buf[1] ^ n[5];
  assign \a1_inv[0] [2] = mul_a0_b_inv_buf[2] ^ n[6];
  assign \a1_inv[0] [3] = mul_a0_b_inv_buf[3] ^ n[7];
  assign \a1_inv[1] [0] = \a1_inv_buf[0] [0] ^ mul_a0_m1_buf[0];
  assign \a1_inv[1] [1] = \a1_inv_buf[0] [1] ^ mul_a0_m1_buf[1];
  assign \a1_inv[1] [2] = \a1_inv_buf[0] [2] ^ mul_a0_m1_buf[2];
  assign \a1_inv[1] [3] = \a1_inv_buf[0] [3] ^ mul_a0_m1_buf[3];
  assign \a1_inv[2] [0] = mul_m0_b_inv_buf[0] ^ \a1_inv_buf[1] [0];
  assign \a1_inv[2] [1] = mul_m0_b_inv_buf[1] ^ \a1_inv_buf[1] [1];
  assign \a1_inv[2] [2] = mul_m0_b_inv_buf[2] ^ \a1_inv_buf[1] [2];
  assign \a1_inv[2] [3] = mul_m0_b_inv_buf[3] ^ \a1_inv_buf[1] [3];
  assign \a1_inv[3] [0] = \a1_inv_buf[2] [0] ^ mul_m0_m1_buf[0];
  assign \a1_inv[3] [1] = \a1_inv_buf[2] [1] ^ mul_m0_m1_buf[1];
  assign \a1_inv[3] [2] = \a1_inv_buf[2] [2] ^ mul_m0_m1_buf[2];
  assign \a1_inv[3] [3] = \a1_inv_buf[2] [3] ^ mul_m0_m1_buf[3];
  assign \a0_inv[0] [0] = mul_a1_b2_inv_buf[0] ^ n[0];
  assign \a0_inv[0] [1] = mul_a1_b2_inv_buf[1] ^ n[1];
  assign \a0_inv[0] [2] = mul_a1_b2_inv_buf[2] ^ n[2];
  assign \a0_inv[0] [3] = mul_a1_b2_inv_buf[3] ^ n[3];
  assign \a0_inv[1] [0] = \a0_inv_buf[0] [0] ^ mul_a1_m0_buf[0];
  assign \a0_inv[1] [1] = \a0_inv_buf[0] [1] ^ mul_a1_m0_buf[1];
  assign \a0_inv[1] [2] = \a0_inv_buf[0] [2] ^ mul_a1_m0_buf[2];
  assign \a0_inv[1] [3] = \a0_inv_buf[0] [3] ^ mul_a1_m0_buf[3];
  assign \a0_inv[2] [0] = mul_m1_b2_inv_buf[0] ^ \a0_inv_buf[1] [0];
  assign \a0_inv[2] [1] = mul_m1_b2_inv_buf[1] ^ \a0_inv_buf[1] [1];
  assign \a0_inv[2] [2] = mul_m1_b2_inv_buf[2] ^ \a0_inv_buf[1] [2];
  assign \a0_inv[2] [3] = mul_m1_b2_inv_buf[3] ^ \a0_inv_buf[1] [3];
  assign \a0_inv[3] [0] = \a0_inv_buf[2] [0] ^ mul_m0_m1_buf[0];
  assign \a0_inv[3] [1] = \a0_inv_buf[2] [1] ^ mul_m0_m1_buf[1];
  assign \a0_inv[3] [2] = \a0_inv_buf[2] [2] ^ mul_m0_m1_buf[2];
  assign \a0_inv[3] [3] = \a0_inv_buf[2] [3] ^ mul_m0_m1_buf[3];
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:380.33-383.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000100  \gen_a01_inv_buf[0].u_prim_xilinx_buf_a0_inv_i  (
    .in_i(\a0_inv[0] ),
    .out_o(\a0_inv_buf[0] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:376.33-379.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000100  \gen_a01_inv_buf[0].u_prim_xilinx_buf_a1_inv_i  (
    .in_i(\a1_inv[0] ),
    .out_o(\a1_inv_buf[0] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:380.33-383.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000100  \gen_a01_inv_buf[1].u_prim_xilinx_buf_a0_inv_i  (
    .in_i(\a0_inv[1] ),
    .out_o(\a0_inv_buf[1] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:376.33-379.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000100  \gen_a01_inv_buf[1].u_prim_xilinx_buf_a1_inv_i  (
    .in_i(\a1_inv[1] ),
    .out_o(\a1_inv_buf[1] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:380.33-383.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000100  \gen_a01_inv_buf[2].u_prim_xilinx_buf_a0_inv_i  (
    .in_i(\a0_inv[2] ),
    .out_o(\a0_inv_buf[2] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:376.33-379.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000100  \gen_a01_inv_buf[2].u_prim_xilinx_buf_a1_inv_i  (
    .in_i(\a1_inv[2] ),
    .out_o(\a1_inv_buf[2] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:380.33-383.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000100  \gen_a01_inv_buf[3].u_prim_xilinx_buf_a0_inv_i  (
    .in_i(\a0_inv[3] ),
    .out_o(\a0_inv_buf[3] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:376.33-379.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000100  \gen_a01_inv_buf[3].u_prim_xilinx_buf_a1_inv_i  (
    .in_i(\a1_inv[3] ),
    .out_o(\a1_inv_buf[3] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:314.33-317.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000100  \gen_b_buf[0].u_prim_xilinx_buf_b_i  (
    .in_i(\b[0] ),
    .out_o(\b_buf[0] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:314.33-317.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000100  \gen_b_buf[1].u_prim_xilinx_buf_b_i  (
    .in_i(\b[1] ),
    .out_o(\b_buf[1] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:314.33-317.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000100  \gen_b_buf[2].u_prim_xilinx_buf_b_i  (
    .in_i(\b[2] ),
    .out_o(\b_buf[2] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:314.33-317.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000100  \gen_b_buf[3].u_prim_xilinx_buf_b_i  (
    .in_i(\b[3] ),
    .out_o(\b_buf[3] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:314.33-317.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000100  \gen_b_buf[4].u_prim_xilinx_buf_b_i  (
    .in_i(\b[4] ),
    .out_o(\b_buf[4] )
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:314.33-317.5" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000100  \gen_b_buf[5].u_prim_xilinx_buf_b_i  (
    .in_i(\b[5] ),
    .out_o(\b_buf[5] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:320.27-326.3" *)
  aes_masked_inverse_gf2p4 u_aes_masked_inverse_gf2p4 (
    .b(\b_buf[5] ),
    .b_inv(b_inv),
    .m1(m[7:4]),
    .q(n[7:4]),
    .r(m[7:6])
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:328.31-331.3" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000100  u_prim_xilinx_buf_b_inv (
    .in_i(b_inv),
    .out_o(b_inv_buf)
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:298.31-301.3" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000000100  u_prim_xilinx_buf_mul_am01 (
    .in_i(mul_a1_a0),
    .out_o(mul_a1_a0_buf)
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:256.32-259.3" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000001100  u_prim_xilinx_buf_mul_bq01 (
    .in_i({ mul_a0_m1, mul_a1_m0, mul_m0_m1 }),
    .out_o({ mul_a0_m1_buf, mul_a1_m0_buf, mul_m0_m1_buf })
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:356.32-359.3" *)
  \$paramod\prim_xilinx_buf\Width=s32'00000000000000000000000000010000  u_prim_xilinx_buf_mul_bq01_c12_inv (
    .in_i({ mul_a0_b_inv, mul_m0_b_inv, mul_a1_b2_inv, mul_m1_b2_inv }),
    .out_o({ mul_a0_b_inv_buf, mul_m0_b_inv_buf, mul_a1_b2_inv_buf, mul_m1_b2_inv_buf })
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:339.32-343.3" *)
  \$paramod\prim_xilinx_xor2\Width=s32'00000000000000000000000000000100  u_prim_xor_b2_inv (
    .in0_i(b_inv_buf),
    .in1_i(xor_m1_m0),
    .out_o(b2_inv)
  );
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:334.32-338.3" *)
  \$paramod\prim_xilinx_xor2\Width=s32'00000000000000000000000000000100  u_prim_xor_m1_m0 (
    .in0_i(m[7:4]),
    .in1_i(m[3:0]),
    .out_o(xor_m1_m0)
  );
  assign a_inv = { \a1_inv_buf[3] , \a0_inv_buf[3]  };
endmodule

(* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox.v:1.1-131.10" *)
(* top =  1  *)
(* hdlname = "\\aes_sbox" *)
module aes_sbox(clk_i, rst_ni, en_i, prd_we_i, out_req_o, out_ack_i, op_i, data_i, mask_i, prd_i, data_o, mask_o, prd_o);
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox.v:17.13-17.18" *)
  input clk_i;
  wire clk_i;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox.v:25.19-25.25" *)
  input [7:0] data_i;
  wire [7:0] data_i;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox.v:29.20-29.26" *)
  output [7:0] data_o;
  wire [7:0] data_o;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox.v:19.13-19.17" *)
  input en_i;
  wire en_i;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox.v:26.19-26.25" *)
  input [7:0] mask_i;
  wire [7:0] mask_i;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox.v:30.20-30.26" *)
  output [7:0] mask_o;
  wire [7:0] mask_o;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox.v:24.19-24.23" *)
  input [1:0] op_i;
  wire [1:0] op_i;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox.v:22.13-22.22" *)
  input out_ack_i;
  wire out_ack_i;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox.v:21.14-21.23" *)
  output out_req_o;
  wire out_req_o;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox.v:28.20-28.25" *)
  input [27:0] prd_i;
  wire [27:0] prd_i;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox.v:31.21-31.26" *)
  output [19:0] prd_o;
  wire [19:0] prd_o;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox.v:20.13-20.21" *)
  input prd_we_i;
  wire prd_we_i;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox.v:18.13-18.19" *)
  input rst_ni;
  wire rst_ni;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox.v:112.30-119.6" *)
  aes_sbox_canright_masked \gen_sbox_masked.genblk1.gen_sbox_canright_masked.u_aes_sbox  (
    .data_i(data_i),
    .data_o(data_o),
    .mask_i(mask_i),
    .mask_o(mask_o),
    .op_i(op_i),
    .prd_i(prd_i[7:0])
  );
  assign out_req_o = en_i;
  assign prd_o = 20'h00000;
endmodule

(* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:388.1-444.10" *)
module aes_sbox_canright_masked(op_i, data_i, mask_i, prd_i, data_o, mask_o);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:398.19-398.25" *)
  input [7:0] data_i;
  wire [7:0] data_i;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:401.20-401.26" *)
  output [7:0] data_o;
  wire [7:0] data_o;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:403.13-403.28" *)
  wire [7:0] in_data_basis_x;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:405.13-405.28" *)
  wire [7:0] in_mask_basis_x;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:399.19-399.25" *)
  input [7:0] mask_i;
  wire [7:0] mask_i;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:402.20-402.26" *)
  output [7:0] mask_o;
  wire [7:0] mask_o;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:397.19-397.23" *)
  input [1:0] op_i;
  wire [1:0] op_i;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:404.13-404.29" *)
  wire [7:0] out_data_basis_x;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:406.13-406.29" *)
  wire [7:0] out_mask_basis_x;
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:400.19-400.24" *)
  input [7:0] prd_i;
  wire [7:0] prd_i;
  assign _131_ = ~data_i[0];
  assign _132_ = ~(data_i[3] ^ data_i[6]);
  assign _133_ = _132_ ^ data_i[2];
  assign _134_ = _133_ ^ data_i[1];
  assign _135_ = _134_ ^ _131_;
  assign _136_ = op_i[0] & ~(op_i[1]);
  assign _137_ = ~data_i[1];
  assign _138_ = ~(data_i[6] ^ data_i[5]);
  assign _139_ = _138_ ^ data_i[4];
  assign _140_ = _139_ ^ _137_;
  assign _141_ = _140_ ^ data_i[0];
  assign _142_ = op_i[1] & ~(op_i[0]);
  assign _143_ = _142_ ? _141_ : _135_;
  assign in_data_basis_x[0] = _136_ ? _135_ : _143_;
  assign _144_ = _138_ ^ _131_;
  assign _145_ = ~(data_i[4] ^ data_i[3]);
  assign _146_ = _145_ ^ data_i[0];
  assign _147_ = _142_ ? _146_ : _144_;
  assign in_data_basis_x[1] = _136_ ? _144_ : _147_;
  assign _148_ = ~(data_i[7] ^ data_i[5]);
  assign _149_ = _148_ ^ data_i[2];
  assign _150_ = _142_ ? _149_ : data_i[0];
  assign in_data_basis_x[2] = _136_ ? data_i[0] : _150_;
  assign _151_ = data_i[4] ^ data_i[7];
  assign _152_ = ~(_151_ ^ data_i[3]);
  assign _153_ = _152_ ^ data_i[1];
  assign _154_ = _153_ ^ _131_;
  assign _155_ = ~(data_i[7] ^ data_i[6]);
  assign _156_ = _155_ ^ data_i[4];
  assign _157_ = _142_ ? _156_ : _154_;
  assign in_data_basis_x[3] = _136_ ? _154_ : _157_;
  assign _000_ = _155_ ^ data_i[5];
  assign _001_ = _000_ ^ _131_;
  assign _002_ = data_i[3] ^ data_i[6];
  assign _003_ = _002_ ^ _137_;
  assign _004_ = _003_ ^ data_i[0];
  assign _005_ = _142_ ? _004_ : _001_;
  assign in_data_basis_x[4] = _136_ ? _001_ : _005_;
  assign _006_ = _138_ ^ data_i[1];
  assign _007_ = _006_ ^ _131_;
  assign _008_ = ~(data_i[4] ^ data_i[6]);
  assign _009_ = _142_ ? _008_ : _007_;
  assign in_data_basis_x[5] = _136_ ? _007_ : _009_;
  assign _010_ = _139_ ^ _131_;
  assign _011_ = _008_ ^ data_i[1];
  assign _012_ = _011_ ^ data_i[0];
  assign _013_ = _142_ ? _012_ : _010_;
  assign in_data_basis_x[6] = _136_ ? _010_ : _013_;
  assign _014_ = _000_ ^ data_i[2];
  assign _015_ = _014_ ^ data_i[1];
  assign _016_ = _015_ ^ _131_;
  assign _017_ = _142_ ? _151_ : _016_;
  assign in_data_basis_x[7] = _136_ ? _016_ : _017_;
  assign _018_ = ~mask_i[0];
  assign _019_ = ~(mask_i[3] ^ mask_i[6]);
  assign _020_ = _019_ ^ mask_i[2];
  assign _021_ = _020_ ^ mask_i[1];
  assign _022_ = _021_ ^ _018_;
  assign _023_ = ~(mask_i[5] ^ mask_i[6]);
  assign _024_ = _023_ ^ mask_i[4];
  assign _025_ = _024_ ^ mask_i[1];
  assign _026_ = _025_ ^ _018_;
  assign _027_ = _142_ ? _026_ : _022_;
  assign in_mask_basis_x[0] = _136_ ? _022_ : _027_;
  assign _028_ = _023_ ^ _018_;
  assign _029_ = ~(mask_i[4] ^ mask_i[3]);
  assign _030_ = _029_ ^ _018_;
  assign _031_ = _142_ ? _030_ : _028_;
  assign in_mask_basis_x[1] = _136_ ? _028_ : _031_;
  assign _032_ = mask_i[7] ^ mask_i[5];
  assign _033_ = _032_ ^ mask_i[2];
  assign _034_ = _142_ ? _033_ : mask_i[0];
  assign in_mask_basis_x[2] = _136_ ? mask_i[0] : _034_;
  assign _035_ = mask_i[4] ^ mask_i[7];
  assign _036_ = ~(_035_ ^ mask_i[3]);
  assign _037_ = _036_ ^ mask_i[1];
  assign _038_ = _037_ ^ _018_;
  assign _039_ = ~(mask_i[7] ^ mask_i[6]);
  assign _040_ = ~(_039_ ^ mask_i[4]);
  assign _041_ = _142_ ? _040_ : _038_;
  assign in_mask_basis_x[3] = _136_ ? _038_ : _041_;
  assign _042_ = _039_ ^ mask_i[5];
  assign _043_ = _042_ ^ _018_;
  assign _044_ = _019_ ^ mask_i[1];
  assign _045_ = _044_ ^ _018_;
  assign _046_ = _142_ ? _045_ : _043_;
  assign in_mask_basis_x[4] = _136_ ? _043_ : _046_;
  assign _047_ = _023_ ^ mask_i[1];
  assign _048_ = _047_ ^ _018_;
  assign _049_ = mask_i[4] ^ mask_i[6];
  assign _050_ = _142_ ? _049_ : _048_;
  assign in_mask_basis_x[5] = _136_ ? _048_ : _050_;
  assign _051_ = _024_ ^ _018_;
  assign _052_ = ~(_049_ ^ mask_i[1]);
  assign _053_ = _052_ ^ _018_;
  assign _054_ = _142_ ? _053_ : _051_;
  assign in_mask_basis_x[6] = _136_ ? _051_ : _054_;
  assign _055_ = _042_ ^ mask_i[2];
  assign _056_ = _055_ ^ mask_i[1];
  assign _057_ = _056_ ^ _018_;
  assign _058_ = _142_ ? _035_ : _057_;
  assign in_mask_basis_x[7] = _136_ ? _057_ : _058_;
  assign _059_ = prd_i[7] ^ prd_i[5];
  assign _060_ = _059_ ^ prd_i[2];
  assign out_mask_basis_x[2] = _142_ ? prd_i[0] : _060_;
  assign _061_ = ~prd_i[0];
  assign _062_ = ~(prd_i[4] ^ prd_i[7]);
  assign _063_ = _062_ ^ prd_i[3];
  assign _064_ = _063_ ^ prd_i[1];
  assign _065_ = _064_ ^ _061_;
  assign _066_ = ~(prd_i[7] ^ prd_i[6]);
  assign _067_ = ~(_066_ ^ prd_i[4]);
  assign out_mask_basis_x[3] = _142_ ? _065_ : _067_;
  assign _068_ = ~(prd_i[5] ^ prd_i[6]);
  assign _069_ = _068_ ^ prd_i[1];
  assign _070_ = _069_ ^ _061_;
  assign _071_ = ~(prd_i[4] ^ prd_i[6]);
  assign _072_ = ~_071_;
  assign out_mask_basis_x[5] = _142_ ? _070_ : _072_;
  assign _073_ = ~_062_;
  assign _074_ = _066_ ^ prd_i[5];
  assign _075_ = _074_ ^ prd_i[2];
  assign _076_ = _075_ ^ prd_i[1];
  assign _077_ = _076_ ^ _061_;
  assign out_mask_basis_x[7] = _142_ ? _077_ : _073_;
  assign _078_ = ~(out_data_basis_x[4] ^ out_data_basis_x[6]);
  assign _079_ = _078_ ^ out_data_basis_x[1];
  assign _080_ = _142_ ? out_data_basis_x[2] : _079_;
  assign data_o[0] = _136_ ? _079_ : _080_;
  assign _081_ = ~(out_data_basis_x[5] ^ out_data_basis_x[4]);
  assign _082_ = _081_ ^ out_data_basis_x[1];
  assign _083_ = out_data_basis_x[5] ^ out_data_basis_x[1];
  assign _084_ = _142_ ? _083_ : _082_;
  assign data_o[1] = _136_ ? _082_ : _084_;
  assign _085_ = ~out_data_basis_x[0];
  assign _086_ = ~(out_data_basis_x[5] ^ out_data_basis_x[6]);
  assign _087_ = _086_ ^ out_data_basis_x[3];
  assign _088_ = _087_ ^ out_data_basis_x[2];
  assign _089_ = _088_ ^ _085_;
  assign _090_ = ~out_data_basis_x[1];
  assign _091_ = ~(out_data_basis_x[7] ^ out_data_basis_x[5]);
  assign _092_ = _091_ ^ out_data_basis_x[4];
  assign _093_ = _092_ ^ _090_;
  assign _094_ = _142_ ? _093_ : _089_;
  assign data_o[2] = _136_ ? _089_ : _094_;
  assign _095_ = ~out_data_basis_x[3];
  assign _096_ = ~(out_data_basis_x[7] ^ out_data_basis_x[6]);
  assign _097_ = _096_ ^ out_data_basis_x[5];
  assign _098_ = _097_ ^ out_data_basis_x[4];
  assign _099_ = _098_ ^ _095_;
  assign _100_ = _086_ ^ out_data_basis_x[4];
  assign _101_ = _100_ ^ out_data_basis_x[3];
  assign _102_ = _101_ ^ out_data_basis_x[2];
  assign _103_ = _102_ ^ _090_;
  assign _104_ = _142_ ? _103_ : _099_;
  assign data_o[3] = _136_ ? _099_ : _104_;
  assign _105_ = _091_ ^ _095_;
  assign _106_ = out_data_basis_x[1] ^ out_data_basis_x[6];
  assign _107_ = _142_ ? _106_ : _105_;
  assign data_o[4] = _136_ ? _105_ : _107_;
  assign _108_ = ~(out_data_basis_x[0] ^ out_data_basis_x[6]);
  assign _109_ = _097_ ^ out_data_basis_x[3];
  assign _110_ = _109_ ^ out_data_basis_x[2];
  assign _111_ = _110_ ^ _085_;
  assign _112_ = _142_ ? _111_ : _108_;
  assign data_o[5] = _136_ ? _108_ : _112_;
  assign _113_ = ~(out_data_basis_x[7] ^ out_data_basis_x[3]);
  assign _114_ = _109_ ^ out_data_basis_x[1];
  assign _115_ = _114_ ^ _085_;
  assign _116_ = _142_ ? _115_ : _113_;
  assign data_o[6] = _136_ ? _113_ : _116_;
  assign _117_ = out_data_basis_x[3] ^ out_data_basis_x[5];
  assign _118_ = out_data_basis_x[1] ^ out_data_basis_x[4];
  assign _119_ = _142_ ? _118_ : _117_;
  assign data_o[7] = _136_ ? _117_ : _119_;
  assign _120_ = ~(prd_i[3] ^ prd_i[6]);
  assign _121_ = _120_ ^ prd_i[2];
  assign _122_ = _068_ ^ prd_i[4];
  assign _123_ = _142_ ? _121_ : _122_;
  assign _124_ = _123_ ^ prd_i[1];
  assign out_mask_basis_x[0] = _124_ ^ _061_;
  assign _125_ = ~(prd_i[4] ^ prd_i[3]);
  assign _126_ = _142_ ? _068_ : _125_;
  assign out_mask_basis_x[1] = _126_ ^ _061_;
  assign _127_ = _120_ ^ prd_i[1];
  assign _128_ = _142_ ? _074_ : _127_;
  assign out_mask_basis_x[4] = _128_ ^ _061_;
  assign _129_ = _071_ ^ prd_i[1];
  assign _130_ = _142_ ? _122_ : _129_;
  assign out_mask_basis_x[6] = _130_ ^ _061_;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/xyfv/Desktop/research_topic/masked_verify/correctness_verification_toolchain/toolchain_build/syn_out/aes_sbox_2025_03_11_00_44_20/generated/aes_sbox_canright_masked.v:435.27-440.3" *)
  aes_masked_inverse_gf2p8 u_aes_masked_inverse_gf2p8 (
    .a(in_data_basis_x),
    .a_inv(out_data_basis_x),
    .m(in_mask_basis_x),
    .n(out_mask_basis_x)
  );
  assign mask_o = prd_i;
endmodule
