
USING_YOSYS_NAMESPACE

using namespace MV_BACKEND; 

const pool<string> MV_BACKEND::mv_keywords() {
    static const pool<string> res = {
        // TODO: fill in mv keywords 
    };
    return res;
}

// initialize variables
bool noglitch;

struct MvBackend : public Backend {
    Mvbackend() : Backend("mv", "generate MV file from RTLIL design for verification") { }
    void help() override {
        // TODO: add help message
        log("\n");
        log("    write_mv [options] [filename]\n");
        log("\n");
        log("Generate MV file from RTLIL design for verification.\n");
        log("\n");
        log("    -noglitch\n");
        log("        Disable glitch modeling when generating MV file.\n");
        log("\n");

    }
    void execute(std::ostream *&f, std::string filename, std::vector<std::string> args, RTLIL::Design *design) override {
        log_header(design, "Executing MV backend.\n");

        // TODO: Process arguments
        // EXTEND: Arguments 

        noglitch = false;

        std::string verilog_frontend = "verilog -nooverwrite -noblackbox";

        size_t argidx; 
        for (argidx = 1; argidx < args.size(); argidx++) {
            std::string arg = args[argidx];
            if (arg == "-noglitch") {
                noglitch = true;
                continue;
            }
            cmd_error(args, argidx, "Unknown option or option in arguments.");
        }
        extra_args(f, filename, args, argidx); // write file content to ostream f 
        
        *f << stringf("/* Generated by Yosys_expr based on %s */\n", yosys_maybe_version());

        // TODO: Implement MV backend logic

        // first get simcells.v, transform into expr formation 

        RTLIL::Design *simcells_lib = new RTLIL::Design; 

        Frontend::frontend_call(simcells_lib, nullptr, "", verilog_frontend);


        // then calculate leak expr and add to hardware file 

        // finally write mv program to ostream f 


    }
}